use super::types::{
    Arity, Associativity, Exactness, Fixity, NumericSupport, OperatorClass, OperatorId,
    OperatorSpec, OperatorSymbolSurface, OperatorSyntax, OperatorTypingRule, OperatorWordSurface,
};

pub const OPERATORS: &[OperatorSpec] = &[
    OperatorSpec { id: OperatorId::Multiply, class: OperatorClass::Arithmetic, syntax: OperatorSyntax::SymbolOnly(OperatorSymbolSurface::Multiply), semantic_op: "multiply", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 70, associativity: Associativity::Left, typing: &[OperatorTypingRule::DimensionalByDimensionless], input_sorts: "exact dimensional times exact dimensionless", result_sort: "exact dimensional", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "a non-dimensionless multiplicand is a type error", spoken: "times", mutation_classes: "precedence, associativity, constant-folding, parenthesis, scale-adjustment", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::Divide, class: OperatorClass::Arithmetic, syntax: OperatorSyntax::SymbolOnly(OperatorSymbolSurface::Divide), semantic_op: "divide", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 70, associativity: Associativity::Left, typing: &[OperatorTypingRule::LikeDimensionRatio, OperatorTypingRule::DimensionalByDimensionless], input_sorts: "exact over exact like-dimension", result_sort: "Ratio or scaled exact", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "division by zero is INVALID; unlike dimensions are a type error", spoken: "divided by", mutation_classes: "precedence, associativity, constant-folding, parenthesis, division-by-zero, scale-adjustment", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::Add, class: OperatorClass::Arithmetic, syntax: OperatorSyntax::SymbolOnly(OperatorSymbolSurface::Add), semantic_op: "add", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 60, associativity: Associativity::Left, typing: &[OperatorTypingRule::PercentAdjustment, OperatorTypingRule::SameUnit], input_sorts: "exact same-unit pair", result_sort: "exact same-unit", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "cross-unit operands are a type error", spoken: "plus", mutation_classes: "precedence, associativity, constant-folding, parenthesis, unit-checking", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::Subtract, class: OperatorClass::Arithmetic, syntax: OperatorSyntax::SymbolOnly(OperatorSymbolSurface::Subtract), semantic_op: "subtract", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 60, associativity: Associativity::Left, typing: &[OperatorTypingRule::PercentDifference, OperatorTypingRule::PercentAdjustment, OperatorTypingRule::WallObservationDifference, OperatorTypingRule::SameUnit], input_sorts: "exact same-unit pair", result_sort: "exact same-unit", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "cross-unit operands are a type error", spoken: "minus", mutation_classes: "precedence, associativity, constant-folding, parenthesis, unit-checking", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::Equal, class: OperatorClass::Comparison, syntax: OperatorSyntax::WordWithSymbolAlias(OperatorWordSurface::Is, OperatorSymbolSurface::Equal), semantic_op: "equal", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", spoken: "is", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::NotEqual, class: OperatorClass::Comparison, syntax: OperatorSyntax::WordWithSymbolAlias(OperatorWordSurface::IsNot, OperatorSymbolSurface::NotEqual), semantic_op: "not-equal", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", spoken: "is not", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::LessThan, class: OperatorClass::Comparison, syntax: OperatorSyntax::WordWithSymbolAlias(OperatorWordSurface::IsLessThan, OperatorSymbolSurface::LessThan), semantic_op: "less-than", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", spoken: "is less than", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::AtMost, class: OperatorClass::Comparison, syntax: OperatorSyntax::WordWithSymbolAlias(OperatorWordSurface::IsAtMost, OperatorSymbolSurface::AtMost), semantic_op: "at-most", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", spoken: "is at most", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::MoreThan, class: OperatorClass::Comparison, syntax: OperatorSyntax::WordWithSymbolAlias(OperatorWordSurface::IsMoreThan, OperatorSymbolSurface::MoreThan), semantic_op: "more-than", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", spoken: "is more than", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::AtLeast, class: OperatorClass::Comparison, syntax: OperatorSyntax::WordWithSymbolAlias(OperatorWordSurface::IsAtLeast, OperatorSymbolSurface::AtLeast), semantic_op: "at-least", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", spoken: "is at least", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: OperatorId::Not, class: OperatorClass::Logical, syntax: OperatorSyntax::WordOnly(OperatorWordSurface::Not), semantic_op: "logical-not", arity: Arity::Unary, fixity: Fixity::Prefix, precedence: 40, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::TruthUnary], input_sorts: "truth value", result_sort: "Truth", exactness: Exactness::NotApplicable, overflow: "none", exception: "none; K3 total", spoken: "not", mutation_classes: "precedence, parenthesis", numeric_support: NumericSupport::NotApplicable },
    OperatorSpec { id: OperatorId::And, class: OperatorClass::Logical, syntax: OperatorSyntax::WordOnly(OperatorWordSurface::And), semantic_op: "logical-and", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 30, associativity: Associativity::Left, typing: &[OperatorTypingRule::TruthBinary], input_sorts: "truth values", result_sort: "Truth", exactness: Exactness::NotApplicable, overflow: "none", exception: "none; K3 total", spoken: "and", mutation_classes: "precedence, associativity, parenthesis", numeric_support: NumericSupport::NotApplicable },
    OperatorSpec { id: OperatorId::Or, class: OperatorClass::Logical, syntax: OperatorSyntax::WordOnly(OperatorWordSurface::Or), semantic_op: "logical-or", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 20, associativity: Associativity::Left, typing: &[OperatorTypingRule::TruthBinary], input_sorts: "truth values", result_sort: "Truth", exactness: Exactness::NotApplicable, overflow: "none", exception: "none; K3 total", spoken: "or", mutation_classes: "precedence, associativity, parenthesis", numeric_support: NumericSupport::NotApplicable },
];
