//! Frozen clean-room BatQL operator facts (V1 operator surface).
//!
//! OperatorSpec is the single source of concrete operator relationships:
//! typed identity (`OperatorId`), typed source syntax (`OperatorSyntax` over
//! the closed word and symbol surface inventories), arity, fixity, precedence,
//! associativity, sorts, exactness, and the projected catalog / surface /
//! grammar / formatting / spoken / numeric tables generated by
//! `bootstrap/project.py`. It owns operator-related grammar fragments and
//! tables only. It does NOT own function, MATCH, declaration, or the general
//! lexical grammar, which remain authored in `companion/BATQL_LANGUAGE.md`.
//!
//! DEC-060 remains the authored arithmetic and operator decision; this module
//! is the concrete fact authority that decision points to. Approximate numeric
//! values exist as typed values (DEC-069, docs/37), but no current ordinary
//! operator admits raw approximate operands; a future qualified operator
//! profile requires explicit admission, sound error or interval propagation,
//! and a language-change record.
//!
//! The source-surface law (5.5E3j): arithmetic operators are symbol-only,
//! comparisons are canonical word phrases with exact symbolic aliases, and
//! logical operators are word-only in every source density. Both surfaces of
//! one comparison lower to the same `OperatorId` — an alias never creates a
//! parallel semantic operation. The formatter always emits
//! `OperatorSyntax::canonical_token`; `spoken` remains a narration projection
//! and is never accepted source syntax.

mod inventory;
mod types;

pub use types::{
    Arity, Associativity, Exactness, Fixity, NumericSupport, OperatorClass, OperatorId,
    OperatorSpec, OperatorSymbolSurface, OperatorSyntax, OperatorTypingRule, OperatorWordSurface,
};
pub use inventory::OPERATORS;
