use super::*;

/// No oracle, no promotion. No named obligation, no promotion. No killed mutant
/// or equivalent hostile evidence, no promotion. No proof receipt, no trust.
pub const EDGES: &[EdgeSpec] = &[
    EdgeSpec { importer: PackageId::MacBat, importee: PackageId::MacBatCompiler, class: EdgeClass::Required, profile: "compile" },
    EdgeSpec { importer: PackageId::BatPak, importee: PackageId::MacBat, class: EdgeClass::Required, profile: "derive" },
    EdgeSpec { importer: PackageId::SyncBat, importee: PackageId::BatPak, class: EdgeClass::Required, profile: "runtime" },
    EdgeSpec { importer: PackageId::BatQl, importee: PackageId::BatPak, class: EdgeClass::Required, profile: "compiler" },
    EdgeSpec { importer: PackageId::NetBat, importee: PackageId::BatPak, class: EdgeClass::Required, profile: "transport-contract" },
    EdgeSpec { importer: PackageId::NetBat, importee: PackageId::SyncBat, class: EdgeClass::Required, profile: "runtime-entrypoints" },
    EdgeSpec { importer: PackageId::BatPakCli, importee: PackageId::BatPak, class: EdgeClass::Required, profile: "core" },
    EdgeSpec { importer: PackageId::BatPakCli, importee: PackageId::SyncBat, class: EdgeClass::Required, profile: "runtime" },
    EdgeSpec { importer: PackageId::BatPakCli, importee: PackageId::BatQl, class: EdgeClass::Required, profile: "compiler" },
    EdgeSpec { importer: PackageId::BatPakCli, importee: PackageId::NetBat, class: EdgeClass::OptionalProfile, profile: "serve" },
    EdgeSpec { importer: PackageId::TestPak, importee: PackageId::MacBatCompiler, class: EdgeClass::DevOnly, profile: "proof" },
    EdgeSpec { importer: PackageId::TestPak, importee: PackageId::MacBat, class: EdgeClass::DevOnly, profile: "proof" },
    EdgeSpec { importer: PackageId::TestPak, importee: PackageId::BatPak, class: EdgeClass::DevOnly, profile: "proof" },
    EdgeSpec { importer: PackageId::TestPak, importee: PackageId::SyncBat, class: EdgeClass::DevOnly, profile: "proof" },
    EdgeSpec { importer: PackageId::TestPak, importee: PackageId::BatQl, class: EdgeClass::DevOnly, profile: "proof" },
    EdgeSpec { importer: PackageId::TestPak, importee: PackageId::NetBat, class: EdgeClass::DevOnly, profile: "proof" },
    EdgeSpec { importer: PackageId::BatPakExamples, importee: PackageId::BatPak, class: EdgeClass::Required, profile: "example" },
    EdgeSpec { importer: PackageId::BatPakExamples, importee: PackageId::SyncBat, class: EdgeClass::Required, profile: "example" },
    EdgeSpec { importer: PackageId::BatPakExamples, importee: PackageId::BatQl, class: EdgeClass::Required, profile: "example" },
];

pub const REQUIRED_DOCS: &[&str] = &[
    "README.md",
    "SPEC.sha256",
    "AGENTS.md",
    "docs/00_CONSTITUTION.md",
    "docs/01_FACTORY.md",
    "docs/02_SYSTEM_MODEL.md",
    "docs/03_REPOSITORY_AND_PACKAGES.md",
    "docs/04_TYPE_SYSTEM_AND_SOURCE_LAYOUT.md",
    "docs/05_STORAGE_FBAT_AND_TILES.md",
    "docs/06_MACBAT.md",
    "docs/07_PAKVM_ISA.md",
    "docs/08_SYNCBAT_RUNTIME.md",
    "docs/09_BVISOR.md",
    "docs/10_WORLD_IMAGES_AND_PORTS.md",
    "docs/11_NETBAT.md",
    "docs/12_TESTPAK.md",
    "docs/13_BATQL_CONTRACT.md",
    "docs/14_RECEIPTS_AND_EXPLANATION.md",
    "docs/15_SCHEMA_CODEC_AND_MIGRATION.md",
    "docs/16_IDENTITY_TIME_AND_NAVIGATION.md",
    "docs/17_DELIVERY_AND_CONCURRENCY.md",
    "docs/18_DATA_ORIENTED_ECS.md",
    "docs/19_SECURITY_MODEL.md",
    "docs/20_DEPENDENCY_SOVEREIGNTY.md",
    "docs/21_LEGACY_SEMANTIC_OBLIGATIONS.md",
    "docs/22_MIGRATION_AND_CUTOVER.md",
    "docs/23_BOOTSTRAP_AND_SELF_HOSTING.md",
    "docs/24_GAUNTLET.md",
    "docs/25_IMPLEMENTATION_GATES.md",
    "docs/26_COMMAND_PLANE.md",
    "docs/27_WORKFLOW.md",
    "docs/28_SELF_EXPLAINING_REPOSITORY.md",
    "docs/29_STATUS_AND_SUPERSESSION.md",
    "docs/30_DECISION_AND_REJECTION_LEDGER.md",
    "docs/31_FINAL_CONTRADICTION_AUDIT.md",
    "docs/32_IMPLEMENTATION_CONSTANTS.md",
    "docs/33_AGENT_FINISH_LINE_CHECKLIST.md",
    "docs/34_LEGACY_INVARIANT_COVERAGE.md",
    "docs/35_CRYPTO_AND_SECRET_AUTHORITY.md",
    "docs/36_PUBLIC_API_CI_AND_RELEASE.md",
    "docs/37_NUMERIC_SEMANTICS_AND_AUTHORITY.md",
    "docs/38_DYNAMIC_VERIFICATION_AND_CONFORMANCE.md",
    "docs/39_SPROUTING_NURSERY_AND_PROMOTION.md",
    "docs/GUARANTEE_GRAPH.generated.md",
    "companion/BATQL_LANGUAGE.md",
    "spec/architecture.rs",
    "spec/invariants.rs",
    "spec/dispositions.rs",
    "spec/legacy_obligations.rs",
    "spec/legacy_invariant_coverage.rs",
    "spec/operators.rs",
    "spec/guarantees.rs",
    "spec/gates.rs",
    "spec/pakvm_isa.rs",
    "spec/syncbat_firewall.rs",
    "spec/lib.rs",
    "spec/reconciliation.rs",
    "spec/proof.rs",
    "spec/toolchain.rs",
    "spec/commands.rs",
    "spec/compiler_assumptions.rs",
    "spec/contracts.rs",
    "spec/corpus.rs",
    "spec/generated_views.rs",
    "spec/bootstrap_output.rs",
    "spec/bootstrap_qualification.rs",
    "spec/tier0_cross_run.rs",
    "spec/identities.rs",
    "spec/mutation.rs",
    "spec/promotion.rs",
    "rust-toolchain.toml",
    "bootstrap/README.md",
    "bootstrap/seedcheck.rs",
    "bootstrap/receiptcheck.rs",
    "bootstrap/materialize.rs",
    "bootstrap/audit.py",
    "bootstrap/freeze.py",
    "bootstrap/project.py",
    "spec/README.md",
];

pub const FORBIDDEN_TARGET_PATHS: &[&str] = &[
    "crates/filebat",
    "crates/bat-vm",
    "crates/batpak-core",
    "crates/core",
    "crates/hostbat",
    "crates/bvisor",
    "crates/pakvm",
    "crates/vpak",
    "crates/testkit",
    "tools/xtask",
    "tools/integrity",
    "corpus",
    "fixtures",
];

