//! Pass 5 lowering for the `VariantInventory` contract kind.
//!
//! Emits a single inherent-impl item carrying the generated variant table:
//!
//! ```ignore
//! impl #impl_generics #Enum #ty_generics #where_clause {
//!     /// Every variant, in declaration order …
//!     pub const ALL: [Self; #N] = [ Self::#A, Self::#B, … ];
//! }
//! ```
//!
//! This is a `::core`/`::std`-only surface — the emitted tokens reference no
//! family crate root (only `Self`, a `pub const`, and a core array literal), so
//! the single edge resolves through [`CratePathRef::CoreStd`] and the lowering
//! never touches a [`crate::hygiene::CratePath`]. Byte-parity target: the
//! `#[derive(AllVariants)]` const from the legacy `macros` crate.

use crate::diagnostic::Diagnostics;
use crate::emit::item_model::{EmittedItem, EmittedItemModel, ItemNode};
use crate::hygiene::LoweringContext;
use crate::identity::{ContractId, EmittedItemId, LoweringRole};
use crate::ir::variant_inventory::VariantInventoryIr;
use crate::lowering::{ContractLowering, CratePathRef, LoweringEdge, LoweringPlan};
use crate::origin::OriginEdge;
use quote::quote;

/// The single role a `VariantInventory` contract lowers to.
const ROLE: LoweringRole = LoweringRole::VariantInventoryConst;

/// Lowering entry for the `VariantInventory` contract kind. Implements the
/// [`ContractLowering`] extension seam; the Pass 5 dispatcher in
/// `lowering::plan` routes the `ContractKindIr::VariantInventory` arm here.
pub struct VariantInventoryLowering;

impl ContractLowering for VariantInventoryLowering {
    type Ir = VariantInventoryIr;

    fn plan(ir: &VariantInventoryIr, ctx: &LoweringContext<'_>) -> Result<LoweringPlan, Diagnostics> {
        let contract = ctx.contract.clone();
        let ident = &ir.ident;
        let (impl_generics, ty_generics, where_clause) = ir.generics.split_for_impl();
        let idents = &ir.variants;
        let count = idents.len();

        // The full impl header tail after the `impl` keyword — exactly the
        // legacy derive's `impl #impl_generics #ident #ty_generics #where_clause`
        // shape, so generic unit-only enums keep compiling (parity law:
        // every currently-accepted input stays accepted).
        let self_ty = quote! { #impl_generics #ident #ty_generics #where_clause };
        let body = quote! {
            /// Every variant, in declaration order. Generated by
            /// `#[derive(VariantInventory)]`, so it can never drift from the enum.
            pub const ALL: [Self; #count] = [ #(Self::#idents),* ];
        };

        let user_span = ir.ident.span();

        let item = EmittedItem {
            id: EmittedItemId::new(0),
            role: ROLE,
            sort_key: "ALL".to_owned(),
            node: ItemNode::InherentImpl { self_ty, body },
            origin: origin_edge(&contract, user_span),
        };

        let edge = LoweringEdge {
            role: ROLE,
            target: CratePathRef::CoreStd,
            origin: origin_edge(&contract, user_span),
        };

        let model = EmittedItemModel {
            contract: contract.clone(),
            items: vec![item],
        };

        Ok(LoweringPlan {
            contract,
            model,
            edges: vec![edge],
        })
    }
}

/// Convenience delegator for the Pass 5 dispatcher, mirroring the free-`plan`
/// call shape used by the other per-kind lowerings.
///
/// # Errors
///
/// Propagates any [`Diagnostics`] produced while planning the contract.
pub fn plan(ir: &VariantInventoryIr, ctx: &LoweringContext<'_>) -> Result<LoweringPlan, Diagnostics> {
    <VariantInventoryLowering as ContractLowering>::plan(ir, ctx)
}

/// Build the origin edge for the single emitted const item. `emitted` is a
/// local placeholder id — Pass 6 `emit::finalize` re-assigns dense ids in
/// source order and assembles the authoritative origin map.
fn origin_edge(contract: &ContractId, user_span: proc_macro2::Span) -> OriginEdge {
    OriginEdge {
        emitted: EmittedItemId::new(0),
        contract: contract.clone(),
        lowering: ROLE,
        declaration_field: None,
        user_span,
    }
}
