//! Frozen clean-room architecture decision facts.

use crate::gates::GateId;
use crate::guarantees::GuaranteeLifetime;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Disposition {
    Keep,
    Lock,
    Kill,
    Supersede,
    Demote,
    Defer,
    OpenImplementation,
    RetainAsEvidence,
}

impl Disposition {
    /// The one lawful DEC lifetime derivation (5.5D4b authority closure).
    ///
    /// A DecisionSpec declares no lifetime field, so a lifetime is DERIVED from
    /// the authored disposition here — in the typed owner — and nowhere else. No
    /// projector may supply it.
    ///
    /// `Kill` is Permanent, not historical: a prohibition stays active permanent
    /// law even though the rejected mechanism is dead. `Defer` is Permanent
    /// policy excluding the subject from V1 until a new ruling reopens it, not an
    /// unfinished construction obligation.
    pub const fn guarantee_lifetime(self) -> GuaranteeLifetime {
        match self {
            Disposition::Lock
            | Disposition::Keep
            | Disposition::Kill
            | Disposition::Defer => GuaranteeLifetime::Permanent,
            Disposition::OpenImplementation => GuaranteeLifetime::UntilGate,
            Disposition::Demote => GuaranteeLifetime::UntilCompatibilityExpiry,
            Disposition::Supersede | Disposition::RetainAsEvidence => {
                GuaranteeLifetime::HistoricalCoverageOnly
            }
        }
    }
}

/// The semantic contexts in which a retired vocabulary term may still appear.
/// Ordinary authoritative material and production/config source are NOT here:
/// those require an inline `[STALE-REF: DEC-...]` marker to name a stale term.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StaleContext {
    DecisionLedger,
    RejectionRecord,
    SupersessionGuide,
    LegacyEvidence,
    MigrationCompatibility,
    TestFixture,
    GeneratedProjection,
}

/// What a decision actually does. The class -- not the title, ID range, document
/// section, or keyword -- decides whether the row must name an implementation or
/// qualification gate (DEC-072).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DecisionClass {
    /// Implementation-bearing architecture: structure a gate must realize.
    Architecture,
    /// A capability the product exposes.
    Capability,
    /// A compatibility window, historical reader, or interop posture.
    Compatibility,
    /// A repository rule enforced by tooling at a gate.
    Enforcement,
    /// A record of a past outcome; carries no forward implementation obligation.
    HistoricalReceipt,
    /// Freezes a public or internal name only.
    Naming,
    /// Owner and law fixed; the mechanism or constant is selected at its gate.
    ImplementationPosture,
}

impl DecisionClass {
    /// Implementation-bearing classes must name at least one gate. There is no
    /// "architecture, but perhaps not implementation-bearing" escape hatch: a
    /// row that only records an outcome is a HistoricalReceipt, and a row that
    /// only freezes a name is Naming.
    pub const fn requires_gate(self) -> bool {
        match self {
            DecisionClass::Architecture
            | DecisionClass::Capability
            | DecisionClass::Compatibility
            | DecisionClass::Enforcement
            | DecisionClass::ImplementationPosture => true,
            DecisionClass::HistoricalReceipt | DecisionClass::Naming => false,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DecisionSpec {
    pub id: &'static str,
    pub class: DecisionClass,
    pub gates: &'static [GateId],
    pub disposition: Disposition,
    pub subject: &'static str,
    pub successor: &'static str,
    /// Retired names for the concept this decision killed/superseded/demoted.
    /// Populated only on decisions that retire vocabulary; the stale-term
    /// matcher is DERIVED from these fields, never hand-maintained beside them.
    pub stale_aliases: &'static [&'static str],
    /// Contexts in which those aliases may lawfully appear without a STALE-REF.
    pub stale_allowed_contexts: &'static [StaleContext],
    /// The clean successor a reader should use instead.
    pub replacement_contract: Option<&'static str>,
}

pub const DECISIONS: &[DecisionSpec] = &[
    DecisionSpec { id: "DEC-001", class: DecisionClass::HistoricalReceipt, gates: &[], disposition: Disposition::Lock, subject: "Pass 1 machine-centered architecture", successor: "Base of final v1", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-002", class: DecisionClass::HistoricalReceipt, gates: &[], disposition: Disposition::RetainAsEvidence, subject: "Pass 2 package-stratified architecture", successor: "Useful ideas salvaged individually; package map rejected", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-003", class: DecisionClass::Architecture, gates: &[GateId::G2], disposition: Disposition::Kill, subject: "Separate storage-format package", successor: ".fbat remains owned by batpak", stale_aliases: &["FileBat", "filebat package", "file-bat crate", "separate storage-format package"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence], replacement_contract: Some(".fbat remains the BatPak-owned journal format") },
    DecisionSpec { id: "DEC-004", class: DecisionClass::Architecture, gates: &[GateId::G5], disposition: Disposition::Kill, subject: "Standalone runtime VM package", successor: "PakVM and Bvisor live inside SyncBat", stale_aliases: &["standalone Bat VM", "bat-vm package", "standalone runtime VM package"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence], replacement_contract: Some("PakVM and Bvisor live inside SyncBat") },
    DecisionSpec { id: "DEC-005", class: DecisionClass::Naming, gates: &[GateId::G0], disposition: Disposition::Supersede, subject: "VPak as machine name", successor: "PakVM is machine; .vpak is package extension", stale_aliases: &["VPak machine", "VPak as the machine name"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence], replacement_contract: Some("PakVM is the machine and .vpak is the package extension") },
    DecisionSpec { id: "DEC-006", class: DecisionClass::Architecture, gates: &[GateId::G5], disposition: Disposition::Lock, subject: "SyncBat internal shape", successor: "runtime, pakvm, bvisor, world, port", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-007", class: DecisionClass::Architecture, gates: &[GateId::G0], disposition: Disposition::Kill, subject: "Universal type directory", successor: "Root concept file + same-name directory", stale_aliases: &["universal type drawer", "src/_types", "_types drawer"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence], replacement_contract: Some("Root concept file plus same-name directory") },
    DecisionSpec { id: "DEC-008", class: DecisionClass::Architecture, gates: &[GateId::G0], disposition: Disposition::Kill, subject: "Universal tables/systems/ports/kernels tree", successor: "Put mechanics under the concept they serve", stale_aliases: &["universal layer-folder tree"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence], replacement_contract: Some("Mechanics live under the concept they serve") },
    DecisionSpec { id: "DEC-009", class: DecisionClass::Architecture, gates: &[GateId::G0], disposition: Disposition::Supersede, subject: "HostBat", successor: "WorldImage, ProgramImage, lifecycle events, ProcessContract, NetBat", stale_aliases: &["HostBat", "HostBat shell", "Host composition shell", "HostBat compatibility path"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence], replacement_contract: Some("WorldImage, ProgramImage, lifecycle events, ProcessContract, and NetBat") },
    DecisionSpec { id: "DEC-010", class: DecisionClass::Architecture, gates: &[GateId::G5], disposition: Disposition::Supersede, subject: "Bvisor OS backend product matrix", successor: "Capability/attempt membrane over PakVM", stale_aliases: &["OS-backend Bvisor", "OS backend matrix", "platform sandbox backend matrix"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence], replacement_contract: Some("Capability and attempt membrane over PakVM") },
    DecisionSpec { id: "DEC-011", class: DecisionClass::Architecture, gates: &[GateId::G2], disposition: Disposition::Keep, subject: ".fbat", successor: "BatPak append-oriented source-truth format", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-012", class: DecisionClass::Architecture, gates: &[GateId::G5], disposition: Disposition::Keep, subject: ".vpak", successor: "Immutable WorldImage package format", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-013", class: DecisionClass::Architecture, gates: &[GateId::G4], disposition: Disposition::Keep, subject: "BatQL compiler package", successor: "Independent frontend over BatPak image contracts", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-014", class: DecisionClass::Architecture, gates: &[GateId::G3], disposition: Disposition::Lock, subject: "TestPak role tree", successor: "Role folders; proof classes are metadata", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-015", class: DecisionClass::Architecture, gates: &[GateId::G3], disposition: Disposition::Lock, subject: "Muterprater scope", successor: "Mutation testing only inside TestPak, across exactly three frozen lanes: SemanticIr mutates BatPak-owned semantic structures and needs no per-candidate Rust compile while the reference interpreter executes the mutant and an independent evidence route judges it, SelectableCompiled compiles one test-profile shard holding many candidate slots where one stable mutation identity selects one slot per isolated process and activation is recorded as evidence rather than assumed, and CompilerBacked runs implementation-sensitive candidates under real rustc semantics without claiming a homegrown evaluator equals rustc; Muterprater owns mutation identity discovery typed plan lane selection test selection activation evidence result classification freshness receipts and promotion proposals while nextest owns isolated test-process execution and rustc owns Rust compilation semantics and compiler-backed differential tooling stays an independent backend until a qualification receipt admits its retirement; every planned mutation reaches one of the eight terminal MutationResult categories and nothing silently leaves the denominator; candidates land under target/muterprater/candidates as disposable derived material with no canonical direct-write path into tracked source, and promotion is a separate admitted action requiring an independent oracle a named invariant or documented proof gap a killed real semantic mutant or equivalent hostile evidence and an auditable proof receipt", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-016", class: DecisionClass::Enforcement, gates: &[GateId::G0], disposition: Disposition::Keep, subject: "Status/supersession metadata", successor: "Required on all docs", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-017", class: DecisionClass::Capability, gates: &[GateId::G6], disposition: Disposition::Keep, subject: "Bounded push + durable pull", successor: "Core delivery doctrine", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-018", class: DecisionClass::Capability, gates: &[GateId::G2], disposition: Disposition::Keep, subject: "K3", successor: "Truth/decision handling only where unresolved data matters", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-019", class: DecisionClass::Capability, gates: &[GateId::G4], disposition: Disposition::Keep, subject: "NC¹ circuit lowering", successor: "Eligible bounded decision fragments only", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-020", class: DecisionClass::Compatibility, gates: &[GateId::G2], disposition: Disposition::Demote, subject: "Serde/MessagePack", successor: "Interop and historical readers, not new semantic authority", stale_aliases: &["Serde as event-contract authority", "Serde supertrait on event contract"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence, StaleContext::MigrationCompatibility], replacement_contract: Some("Interop and historical readers only") },
    DecisionSpec { id: "DEC-021", class: DecisionClass::ImplementationPosture, gates: &[GateId::G6], disposition: Disposition::Demote, subject: "Flume", successor: "Private reference mechanism during topology-by-topology succession", stale_aliases: &["raw Flume receiver", "public Flume receiver"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence, StaleContext::MigrationCompatibility], replacement_contract: Some("Mailbox, Completion, Broadcast, and Permit contracts") },
    DecisionSpec { id: "DEC-022", class: DecisionClass::ImplementationPosture, gates: &[GateId::G2], disposition: Disposition::Demote, subject: "UUID crate", successor: "Differential oracle until owned generator closes", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-023", class: DecisionClass::ImplementationPosture, gates: &[GateId::G5], disposition: Disposition::Defer, subject: "Arbitrary native/Wasm guest execution", successor: "Future external-effect adapter only after real adopter", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-024", class: DecisionClass::Capability, gates: &[GateId::G5], disposition: Disposition::Keep, subject: "Artifact/content plane", successor: "Concern and port; no public bundle extension yet", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-025", class: DecisionClass::Architecture, gates: &[GateId::G7], disposition: Disposition::Keep, subject: "Thin CLI package", successor: "Binary adapter only, no semantic ownership", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-040", class: DecisionClass::Architecture, gates: &[GateId::G0, GateId::G5], disposition: Disposition::Lock, subject: "BatPak and SyncBat semantic profiles", successor: "no_std + alloc; host mechanisms stay in explicit std/browser adapters", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-041", class: DecisionClass::Architecture, gates: &[GateId::G0], disposition: Disposition::Lock, subject: "Cargo package batpak", successor: "The real semantic and durable library, not an empty umbrella; repository and library share the product name", stale_aliases: &["empty product umbrella", "meaning-free umbrella"], stale_allowed_contexts: &[StaleContext::DecisionLedger, StaleContext::RejectionRecord, StaleContext::SupersessionGuide, StaleContext::LegacyEvidence], replacement_contract: Some("batpak is the real semantic and durable library") },
    DecisionSpec { id: "DEC-042", class: DecisionClass::ImplementationPosture, gates: &[GateId::G2], disposition: Disposition::Defer, subject: "BatDenseRecord representation", successor: "Requires a sealed-image or measured-kernel adopter; not part of the initial native authority path", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-043", class: DecisionClass::Architecture, gates: &[GateId::G0], disposition: Disposition::Lock, subject: "Examples package batpak-examples", successor: "Public-surface witness at examples/; publish is false; owns no semantic law; no TestPak dependency; production APIs only; observable output; executed through TestPak orchestration", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-044", class: DecisionClass::Architecture, gates: &[GateId::G3], disposition: Disposition::Lock, subject: "TestPak sole corpus and fixture home", successor: "crates/testpak/corpus and crates/testpak/fixtures own frozen assets; root corpus/ and fixtures/ are forbidden; no canonical package-local mirrors", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-045", class: DecisionClass::Architecture, gates: &[GateId::G3], disposition: Disposition::Lock, subject: "TestPak binary target", successor: "The testpak package ships src/lib.rs and src/bin/testpak.rs; the root justfile projects cargo run -p testpak; no separate command crate", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-046", class: DecisionClass::Architecture, gates: &[GateId::G0], disposition: Disposition::Lock, subject: "Workspace version train", successor: "1.0.0-alpha.1 implementation train; publishable production packages ship lockstep to 1.0.0; versions below the train are rejected", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-047", class: DecisionClass::Architecture, gates: &[GateId::G0], disposition: Disposition::Lock, subject: "Default feature behavior", successor: "batpak and syncbat default to std with useful native usability; no_std via default-features false; std must not activate the threaded browser encryption mapping or interop adapter zoo", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-048", class: DecisionClass::HistoricalReceipt, gates: &[], disposition: Disposition::Lock, subject: "Orphan clean-room cutover", successor: "cleanroom is orphan with zero parents; legacy/main owns the final legacy source lineage; legacy-pre-cleanroom is the immutable legacy tag; no source merge graft cherry-pick or subtree import crosses; behavior crosses only through LEG obligations and clean witnesses; legacy source 6c4a46f8; clean-room base ada284a0", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-049", class: DecisionClass::Capability, gates: &[GateId::G5], disposition: Disposition::Lock, subject: "Declared WorldImage entrypoint invocation", successor: "InvokeEntrypoint executes a ProgramImage bound by an admitted WorldImage entrypoint; persistent deployment; ASK or DO; effects only when the entrypoint contract declares them; capability from the WorldImage grant; a request cannot substitute a foreign ProgramImage while keeping entrypoint authority; identity binds WorldImageId WorldInterfaceHash EntrypointId ProgramImageId InvocationId AttemptId", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-050", class: DecisionClass::Capability, gates: &[GateId::G4, GateId::G5], disposition: Disposition::Lock, subject: "Ephemeral query ProgramImage invocation", successor: "ExecuteQueryProgram executes a client-supplied canonical query-only ProgramImage ephemerally under a server-issued read-only query capability envelope; effects process installation and lifecycle hooks forbidden; the server validates the image independently and client compilation grants no trust; response binds ProgramImageId query authority digest historical cut source generation completeness proof disposition actual work result digest and receipt; ALLOW DENY DEFER may be data but never drive an effect", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-051", class: DecisionClass::Architecture, gates: &[GateId::G4], disposition: Disposition::Lock, subject: "Source compilation and raw-BatQL authority boundary", successor: "BatQL source text is authoring input never executable authority; PakVM executes validated ProgramImages not source; ordinary NetBat permits InvokeEntrypoint and ExecuteQueryProgram and rejects CompileAndExecuteRawBatQL EvalText and ExecuteSource; source compilation is a separately admitted dev and admin CompilerPort not available to guests not implied by NetBat access and absent from the default server profile; it emits ProgramImage plus CompilationReceipt through the ordinary validation and admission path so source identity is provenance not runtime authority", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-052", class: DecisionClass::Architecture, gates: &[GateId::G2], disposition: Disposition::Lock, subject: "Integrity role separation", successor: "Checksum32 ContentDigest CommitmentDigest MacTag Signature and ExternalAnchor are six distinct types; a checksum never implies authority; an unkeyed digest never authenticates its own expected value", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-053", class: DecisionClass::Architecture, gates: &[GateId::G2], disposition: Disposition::Lock, subject: "Secret authority vocabulary and no homemade crypto", successor: "batpak::secret owns KeyScope KeyId KeyGeneration KeyBackendId KeyState ShredTransition RotationId RewrapId and AntiRollbackPolicy; encrypted payloads require a qualified AEAD; entropy enters only through EntropyPort; no homemade cryptographic primitives; raw secrets never enter .fbat .vpak WorldImage ordinary receipts proof manifests logs Debug or Display", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-054", class: DecisionClass::ImplementationPosture, gates: &[GateId::G2], disposition: Disposition::Defer, subject: "Password-derived key material", successor: "V1 accepts no human password or passphrase as key material; no password KDF is part of the V1 runtime contract; a KDF enters only if a later explicit password-derived-key feature earns one through the amendment path", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-056", class: DecisionClass::Enforcement, gates: &[GateId::G3, GateId::G9], disposition: Disposition::Lock, subject: "Public API ownership and semver", successor: "TestPak owns public API baselines semver classification MSRV qualification and target profile qualification; every publishable package gets a generated baseline dependency-type leakage scan semver classification downstream compile fixture and deprecation disposition; a public removal requires successor migration example deprecation interval downstream audit decision receipt and baseline update; delete-and-discover public API change is refused", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-057", class: DecisionClass::Enforcement, gates: &[GateId::G3], disposition: Disposition::Lock, subject: "CI lanes versus proof ownership", successor: "TestPak owns what must be proven; CI chooses where and when the lanes execute; release consumes fresh matching receipts; exact GitHub Actions filenames and job layouts are a projection of TestPak lane policy not authority", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-058", class: DecisionClass::Enforcement, gates: &[GateId::G9], disposition: Disposition::Lock, subject: "Release seal and refusal", successor: "A release receipt binds source tree toolchain dependency graph generated facts compatibility corpus test mutation fuzz and benchmark dispositions unsafe and dependency ledgers package contents public API SBOM license and proof freshness; a release is refused on an unclassified denominator row a stale receipt an unresolved semver classification a compatibility reader without a removal receipt or a package-content license or SBOM gap; the library crate is batpak and the product binary is batpak-cli", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-059", class: DecisionClass::Compatibility, gates: &[GateId::G2], disposition: Disposition::Lock, subject: "Compatibility scope", successor: "Compatibility applies to durable legacy data and intentionally preserved public contracts; it does not require keeping superseded internal crate topology HostBat a standalone Bat VM a separate storage-format package an OS-backend Bvisor matrix or dual execution models alive; semver is not a hostage negotiator for dead architecture", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-060", class: DecisionClass::Capability, gates: &[GateId::G4], disposition: Disposition::Lock, subject: "Typed arithmetic and rounding law", successor: "BatQL arithmetic is dimensionally typed with spec/operators.rs OperatorSpec as the concrete operator fact authority: same-unit addition and subtraction; multiplication requires a dimensionless operand; division of like dimensions yields Ratio; Money times Money and cross-currency operations are rejected; every scale-reducing conversion names one of six canonical rounding modes HalfEven HalfAwayFromZero TowardZero AwayFromZero Floor Ceiling, and surface spellings HALF_EVEN HALF_UP DOWN UP lower to the first four; overflow division-by-zero and unsupported scale yield INVALID; illegal units are a compile-time type error; currency conversion needs an explicit function and a receipted rate source; the exact-versus-approximate authority boundary is owned by DEC-069 and docs/37", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-061", class: DecisionClass::Capability, gates: &[GateId::G2], disposition: Disposition::Lock, subject: "Deterministic HLC query ordering and range law", successor: "HLC is causal chronological evidence never journal progress authority; ORDER BY HLC lowers to a total key HLC then GlobalSequence within one journal and HLC then StoreId then GlobalSequence across journals; DURING HLC ranges are half-open; HLC is forbidden for durability coverage cursor resume frontier advancement commit identity deadline measurement and implicit causation; when causal HLC is absent the result is Unavailable and ObservedWallTime is never promoted into Hlc", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-062", class: DecisionClass::Capability, gates: &[GateId::G4], disposition: Disposition::Lock, subject: "Kernel identity and binding policy", successor: "FROM KERNEL refers to a canonical KernelManifest never a display name Rust path or function pointer; KernelContractId KernelInterfaceHash KernelImplementationId and KernelQualificationReceiptId are distinct; WorldImage binding is either ExactImplementation pinning KernelImplementationId or QualifiedInterface pinning KernelContractId plus KernelInterfaceHash with an accepted qualification receipt; PakVM never resolves a kernel by string name and the AttemptReceipt records the exact KernelImplementationId used", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-063", class: DecisionClass::ImplementationPosture, gates: &[GateId::G2, GateId::G8], disposition: Disposition::Lock, subject: "V1 compression posture", successor: "V1 .fbat authority frames and .vpak canonical sections are uncompressed; large payloads use ArtifactRef; derived tiles may use an explicit versioned compression profile; transparent compression is forbidden; a future compressed profile requires CompressionId canonical parameters bounded decompression a maximum expansion ratio a digest-coverage law compatibility rows hostile fixtures and a measured adopter and must state whether identity covers compressed bytes uncompressed bytes or both; no compression algorithm is selected now", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-064", class: DecisionClass::Architecture, gates: &[GateId::G2], disposition: Disposition::Lock, subject: "Version identities remain distinct", successor: "BatQlLanguageVersion ProgramImageVersion WorldImageVersion PakVmIsaVersion FbatFormatVersion BatTaggedRecordVersion NetBatProtocolVersion KernelManifestVersion ReceiptSchemaVersion and SchemaVersion are distinct types; no generic Version crosses subsystem boundaries; canonical bytes carry their owning version; ProgramImageId commits to canonical bytes including version and is independent of compiler provenance so identical bytes from two qualified compilers share an id; NetBat protocol negotiation is independent of PakVM ISA and WorldImage versions", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-065", class: DecisionClass::Architecture, gates: &[GateId::G0, GateId::G5], disposition: Disposition::Lock, subject: "no_std and alloc realization matrix", successor: "batpak and syncbat realize their no_std plus alloc semantic surfaces not merely assert them; std and browser adapters own filesystem mapping threads sockets clock entropy keychain and web APIs; default-features false is compile-proven and a green default build is not sufficient evidence; collections use Vec bounded arenas BTreeMap ordered maps and sorted catalogs while hash maps are derived caches whose iteration never influences canonical identity formatting diagnostics execution order or receipts; the qualification matrix covers batpak no_std syncbat no_std native std default threaded browser encryption and interop; every qualified profile preserves program semantics so the same program over the same inputs yields the same canonical observables on native and browser alike, with an adapter supplying mechanism and evidence only and profile-owned differences confined to mechanism performance and available capability never to program-observable results", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-066", class: DecisionClass::Capability, gates: &[GateId::G5, GateId::G6], disposition: Disposition::Lock, subject: "Typed resource exhaustion and no-partial-publication", successor: "BudgetExceeded and ResourceExhausted are distinct outcomes never collapsed into each other a string or INVALID; INVALID means a value violated its contract while resource exhaustion is an execution failure; every attacker-influenced allocation decodes the declared length checks arithmetic enforces the semantic bound try_reserves initializes and publishes only after completion; failure never panics aborts wraps or leaves a partial value event artifact or checkpoint; this covers .fbat .vpak BatQL PakVM arenas group and match state NetBat framing proof bundles artifact staging and tile materialization", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-026", class: DecisionClass::Architecture, gates: &[GateId::G2], disposition: Disposition::Lock, subject: "Immutable accepted history", successor: "Corrections are later events", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-027", class: DecisionClass::Compatibility, gates: &[GateId::G2], disposition: Disposition::Lock, subject: "Read-time schema evolution", successor: "Historical bytes remain unchanged", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-028", class: DecisionClass::Architecture, gates: &[GateId::G6], disposition: Disposition::Lock, subject: "Turn versus Attempt", successor: "Logical and physical execution identities remain distinct", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-029", class: DecisionClass::Architecture, gates: &[GateId::G5, GateId::G6], disposition: Disposition::Lock, subject: "Runtime/Bvisor restart split", successor: "Runtime decides legality; Bvisor performs mechanics", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-030", class: DecisionClass::Capability, gates: &[GateId::G2], disposition: Disposition::Lock, subject: "Availability axes", successor: "Value state, truth, decision, completeness, freshness, proof are separate; numeric sorts exact approximate and interval are orthogonal to these axes per DEC-069 and docs/37", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-031", class: DecisionClass::Capability, gates: &[GateId::G2], disposition: Disposition::Lock, subject: "HLC scope", successor: "Chronology/filtering aid, not durability or universal order", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-032", class: DecisionClass::Architecture, gates: &[GateId::G8], disposition: Disposition::Keep, subject: "ECS/data orientation", successor: "Implementation algebra, not ontology", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-033", class: DecisionClass::ImplementationPosture, gates: &[GateId::G8], disposition: Disposition::Keep, subject: "SIDX successor", successor: "First earned column tile", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-034", class: DecisionClass::Capability, gates: &[GateId::G2], disposition: Disposition::Keep, subject: "One evaluation, many projections", successor: "Value/explanation/evidence/margin/cost share typed evaluation; numeric evaluation projects value margin evidence and explanation per DEC-069 and docs/37", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-035", class: DecisionClass::ImplementationPosture, gates: &[GateId::G2], disposition: Disposition::OpenImplementation, subject: "EventFrameV2 field IDs and exact bytes", successor: "G2", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-036", class: DecisionClass::ImplementationPosture, gates: &[GateId::G5], disposition: Disposition::OpenImplementation, subject: ".vpak section and PakVM opcode numbers", successor: "G5", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-037", class: DecisionClass::ImplementationPosture, gates: &[GateId::G5, GateId::G7], disposition: Disposition::OpenImplementation, subject: "First persistent browser adapter", successor: "G5/G7", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-038", class: DecisionClass::ImplementationPosture, gates: &[GateId::G3, GateId::G8], disposition: Disposition::OpenImplementation, subject: "Performance/work thresholds", successor: "owning gate + TestPak", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-039", class: DecisionClass::ImplementationPosture, gates: &[GateId::G2], disposition: Disposition::Defer, subject: "Public packed-artifact extension", successor: "real adopter required", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-055", class: DecisionClass::ImplementationPosture, gates: &[GateId::G2], disposition: Disposition::OpenImplementation, subject: "Exact cryptographic constants", successor: "G2", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-067", class: DecisionClass::Enforcement, gates: &[GateId::G0], disposition: Disposition::Lock, subject: "Bootstrap lexical debt scan and generated lint posture", successor: "seedcheck lexically scans production source under crates apps and examples after stripping comments and strings for the panic unwrap expect and dbg tokens while test-owned paths tests benches fixtures corpus and fuzz are exempt; the generated workspace denies wildcard_enum_match_arm cast_possible_truncation cast_sign_loss missing_errors_doc large_enum_variant clone_on_ref_ptr and needless_pass_by_value but never globally denies expect_used and never blanket-bans as casts; pointer and layout casts belong to the compiler-assumption ledger and the TestPak AST gate", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-068", class: DecisionClass::Enforcement, gates: &[GateId::G1, GateId::G3], disposition: Disposition::Lock, subject: "TestPak AST enforcement gate", successor: "The authoritative Rust classification is a TestPak AST gate implemented at G3 that detects function and closure-local domain types unledgered unsafe pointer and narrowing casts lint suppressions production panic unwrap expect and dbg dependency-owned public types drawer modules stale aliases and canonical-order dependence on hash-map iteration; production violations are hard findings while test-only contextual expect is permitted and dangerous mechanisms require a compiler-assumption ledger entry; the bootstrap lexical scan is defense in depth and the gate does not exist yet", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-069", class: DecisionClass::Capability, gates: &[GateId::G2, GateId::G3, GateId::G5], disposition: Disposition::Lock, subject: "Exact Authority and Qualified Approximation", successor: "Ordinary unqualified IEEE floats are rejected as authority values; first-class Qualified Approximation is accepted only with explicit FloatFormatId classification provenance and interval or error evidence and crosses into authority only through a receipted Quantize or IntervalDecision; Fixed128 a signed i128 coefficient with explicit scale unit and numeric profile is the canonical inline fixed-decimal authority representation while ExactInteger and ExactRatio retain their own canonical exact forms; wide exact is a qualified profile seam not ordinary inline V1 authority; approximation crosses to authority through QuantizePoint to a fixed-decimal point or QuantizeInterval to an enclosing exact interval never through a silently invented point; this refines DEC-030 DEC-034 and DEC-060 and is owned by docs/37", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-070", class: DecisionClass::Enforcement, gates: &[GateId::G0], disposition: Disposition::Lock, subject: "Guarantee classification and derived Guarantee Graph", successor: "SEED LEG DEC architecture and qualification facts retain their native authority and schemas; guarantee classification exposes their kind lifetime ownership gates witnesses failure posture and explicit relations through a generated derived view; the Guarantee Graph is a derived structural index not normative authority and cannot replace or silently revise an owning fact; the locked fork is separate authored fact families plus one generated derived graph rather than one hand-authored universal ledger or several unrelated ledgers with no lifecycle relationship; lifetime active-or-closed status compatibility disposition and deletion condition remain orthogonal", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-071", class: DecisionClass::Capability, gates: &[GateId::G2, GateId::G9], disposition: Disposition::Lock, subject: "Authenticated-history profiles and witness policy", successor: "V1 exposes InternalConsistency SignedHistory and ExternallyAnchoredHistory as explicit authenticated-history profiles; witness policy is typed and constrained by profile so Required appears only with ExternallyAnchoredHistory and InternalConsistency permits only None; required external anchoring fails closed on an absent stale conflicting unverifiable cryptographically invalid lineage-mismatched generation-mismatched or accumulator-mismatched witness; internal consistency and signed history alone do not prove that the selected generation is the newest history ever acknowledged because that freshness claim requires an independent monotonic witness; an optional witness is optional to supply but once supplied is mandatory to validate and a supplied invalid witness refuses rather than degrading to absence; no verification result receipt release or public claim may assert stronger integrity authenticity freshness or rollback resistance than the selected profile and verified witness posture support; the typed matrix is owned by spec/architecture.rs and the threat and claims by docs/19", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-072", class: DecisionClass::Enforcement, gates: &[GateId::G0, GateId::G9], disposition: Disposition::Lock, subject: "Typed decision classification and gate binding", successor: "Every decision declares one typed DecisionClass; every implementation-bearing decision names at least one typed implementation or qualification GateId through the single spec/gates.rs identity; Naming and HistoricalReceipt decisions may remain ungated; bootstrap audit and seedcheck reject missing duplicate unknown noncanonical documentary-mismatched or class-incompatible gate bindings; documentary decision views and Guarantee Graph decision metadata must equal the typed DecisionSpec facts; the class not the title ID range document section or keyword decides whether a gate is required", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-073", class: DecisionClass::Capability, gates: &[GateId::G4, GateId::G5, GateId::G8, GateId::G9], disposition: Disposition::Lock, subject: "Adaptive residual specialization", successor: "PakVM's reference interpreter remains the executable semantic authority for admitted programs; V1 may derive a SpecializedPlan through compile-time or bounded first-use residual specialization over explicitly identified static facts; every SpecializedPlan is content-addressed bound to a complete specialization key independently verifiable against that key and treated only as derived optimization material; a missing refused expired corrupt incompatible or mismatched residual plan is discarded and execution falls back to the reference interpreter; deleting every specialization cache changes performance and WorkObservation only never meaning authority proof posture effect legality or receipt semantics; first-use specialization is bounded by an explicit work budget and the absolute monotonic deadline executes no application effect and never bypasses Bvisor admission; specialization may discharge only checks proven static under the complete key and recorded as discharged; the scalar Column SelectionMask ScanKernel and LateMaterialization path is the reference behavior and no optimized kernel is the sole oracle; V1 does not require native-code generation executable memory deoptimization machinery nightly Rust unsafe intrinsics or a SIMD runtime dependency; this refines DEC-032 and DEC-033 and adds no public BatQL syntax", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
    DecisionSpec { id: "DEC-074", class: DecisionClass::Enforcement, gates: &[GateId::G3, GateId::G9], disposition: Disposition::Lock, subject: "Proof-policy anti-weakening", successor: "TestPak owns one explicit proof-policy anti-weakening gate; every change to an owned proof-policy surface declares one typed ProofPolicyChangeClass of Strengthening Neutral or Weakening and an unclassified proof-policy change is refused; a Neutral classification requires parity evidence because a refactor is not automatically neutral; a Weakening requires explicit DEC or supersession authority rationale affected guarantee references the old and new boundary a replacement-proof or accepted-risk disposition hostile qualification proving the new boundary is enforced release-visible disclosure and an auditable receipt, and a generic issue link is not decision authority while a commit message is not a weakening receipt; the gate does not claim to infer semantic truth from arbitrary source diffs but proves that proof-policy changes are explicitly classified authorized qualified and receipted rather than entering as invisible cleanup; no test mutation waiver threshold freshness selection promotion or release-blocking policy becomes weaker merely because its implementation was reorganized; weakening the anti-weakening gate itself requires the same complete authority package", stale_aliases: &[], stale_allowed_contexts: &[], replacement_contract: None },
];
