//! Frozen bootstrap invariants. Stable IDs become TestPak contract IDs.
//!
//! Each SEED fact carries its own guarantee classification (DEC-070): kind,
//! lifetime, owner, gates, witness, source-native failure disposition, and
//! explicit relations. Shared types live in `spec/guarantees.rs`; this file is
//! the sole owner of the SEED facts and their classification.

use crate::gates::GateId;
use crate::guarantees::{GuaranteeKind, GuaranteeLifetime, GuaranteeRef};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct InvariantSpec {
    pub id: &'static str,
    pub statement: &'static str,
    pub kind: GuaranteeKind,
    pub lifetime: GuaranteeLifetime,
    pub owner: &'static str,
    pub gates: &'static [GateId],
    pub witness: &'static str,
    pub failure_disposition: &'static str,
    /// Typed relations (5.5E2): a reference names its family in the type, so
    /// a decision cited as a legacy obligation has no spelling. Whether each
    /// reference resolves to a declared row is an executed seedcheck law.
    pub derives_from: &'static [GuaranteeRef],
    pub refines: &'static [GuaranteeRef],
    pub discharges: &'static [GuaranteeRef],
    pub supersedes: &'static [GuaranteeRef],
}

pub const INVARIANTS: &[InvariantSpec] = &[
    InvariantSpec { id: "SEED-ONE-OWNER", statement: "Every stable semantic concept has one canonical owner.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/00_CONSTITUTION.md", gates: &[GateId::G0], witness: "audit.py contract-id uniqueness; docs/28 self-explaining repository", failure_disposition: "hard structural finding: duplicate ownership", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-SYNCBAT-ONE-HEARTBEAT", statement: "SyncBat contains the runtime, PakVM, Bvisor, world, and port planes as modules of one runtime crate.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/03_REPOSITORY_AND_PACKAGES.md", gates: &[GateId::G0], witness: "spec/architecture.rs SYNCBAT_REQUIRED_PLANES; audit.py", failure_disposition: "hard finding: standalone plane package", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-STANDALONE-VM", statement: "No standalone bat-vm, vpak, pakvm, or bvisor package exists in the target graph.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/03_REPOSITORY_AND_PACKAGES.md", gates: &[GateId::G0], witness: "spec/architecture.rs PACKAGES; audit.py forbidden paths", failure_disposition: "hard finding: standalone VM package", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-FBAT-CORE", statement: ".fbat is BatPak journal authority and does not imply a FileBat package.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/05_STORAGE_FBAT_AND_TILES.md", gates: &[GateId::G2], witness: "stale-vocabulary scan; audit.py", failure_disposition: "hard finding: FileBat package reintroduced", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-PAKVM-NAME", statement: "PakVM names the machine; .vpak names the executable package profile; ProgramImage and WorldImage name semantic values.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/07_PAKVM_ISA.md", gates: &[GateId::G0, GateId::G5], witness: "stale-vocabulary scan; audit.py", failure_disposition: "hard finding: name laundering", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-DUAL-PRODUCT", statement: "HostBat and platform-backend product models do not coexist with WorldImage, PakVM, and Bvisor.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/02_SYSTEM_MODEL.md", gates: &[GateId::G0], witness: "stale-vocabulary scan; docs/31", failure_disposition: "hard finding: dual product model", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-AMBIENT-AUTHORITY", statement: "PakVM programs have no syscall, host path, raw descriptor, ambient clock, entropy, environment, or process instruction.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/07_PAKVM_ISA.md", gates: &[GateId::G5], witness: "LEG-066; BP-GAUNTLET-1 capability enforcement", failure_disposition: "hard finding: ambient-authority instruction", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-SEMANTIC-ZERO-LEAKAGE", statement: "Dependency-owned mechanism types do not define ordinary public BatPak semantics.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/20_DEPENDENCY_SOVEREIGNTY.md", gates: &[GateId::G0], witness: "seedcheck production-token scan; DEC-068 AST gate", failure_disposition: "hard finding: dependency type in public semantics", derives_from: &[GuaranteeRef::dec("DEC-068")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-SYNC-FIRST", statement: "Production semantic APIs require no hidden async runtime, hidden thread, or hidden executor.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/08_SYNCBAT_RUNTIME.md", gates: &[GateId::G0, GateId::G5], witness: "LEG-080; seedcheck no-tokio", failure_disposition: "hard finding: hidden executor", derives_from: &[], refines: &[GuaranteeRef::leg("LEG-080")], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-STD-SEMANTIC-PROFILES", statement: "BatPak and SyncBat qualify their semantic profiles under no_std + alloc; std and browser host mechanisms remain explicit adapters.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/20_DEPENDENCY_SOVEREIGNTY.md", gates: &[GateId::G0, GateId::G5], witness: "DEC-065 qualification matrix", failure_disposition: "hard finding: std in semantic profile", derives_from: &[GuaranteeRef::dec("DEC-065")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-CONCEPT-SPINE", statement: "Primary semantic types live in root concept files paired with same-name implementation directories; no universal _types drawer exists.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/04_TYPE_SYSTEM_AND_SOURCE_LAYOUT.md", gates: &[GateId::G0], witness: "DEC-068 AST gate; seedcheck", failure_disposition: "hard finding: universal types drawer", derives_from: &[GuaranteeRef::dec("DEC-068")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-INLINE-DOMAIN-TYPES", statement: "No domain-significant named type is declared inside a function or hidden in an unrelated algorithm file.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/04_TYPE_SYSTEM_AND_SOURCE_LAYOUT.md", gates: &[GateId::G1, GateId::G3], witness: "DEC-068 AST gate", failure_disposition: "hard finding: inline domain type", derives_from: &[GuaranteeRef::dec("DEC-068")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-EXPLICIT-EFFECTS", statement: "Every effect crosses a named capability terminal and produces a typed outcome.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/08_SYNCBAT_RUNTIME.md", gates: &[GateId::G6], witness: "LEG-036; LEG-061; BP-GAUNTLET-1", failure_disposition: "hard finding: effect without capability terminal", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-INDEPENDENT-ORACLE", statement: "No optimized or generated subsystem is its own only oracle.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/24_GAUNTLET.md", gates: &[GateId::G3, GateId::G8], witness: "LEG-079; LEG-049", failure_disposition: "hard finding: self-blessing oracle", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-AUDITED-DENOMINATOR", statement: "Every planned proof unit terminates with an explicit disposition.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/24_GAUNTLET.md", gates: &[GateId::G3, GateId::G9], witness: "LEG-049; docs/34 coverage; audit.py declaration parity", failure_disposition: "hard finding: unclassified proof unit", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-MUTERPRATER-SCOPE", statement: "Muterprater owns mutation testing only and lives inside TestPak.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/12_TESTPAK.md", gates: &[GateId::G3], witness: "DEC-015", failure_disposition: "hard finding: Muterprater outside TestPak", derives_from: &[GuaranteeRef::dec("DEC-015")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-BOUNDED-PUSH", statement: "Long-lived push is bounded per message, batch, buffer, and retained window and has a durable pull recovery path.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/17_DELIVERY_AND_CONCURRENCY.md", gates: &[GateId::G6], witness: "LEG-032; LEG-060", failure_disposition: "hard finding: unbounded push", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-AVAILABILITY-AXES", statement: "Value availability, K3 truth, decision, completeness, freshness, and proof disposition are distinct axes.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/04_TYPE_SYSTEM_AND_SOURCE_LAYOUT.md", gates: &[GateId::G2], witness: "DEC-030; docs/37", failure_disposition: "hard finding: collapsed availability axis", derives_from: &[GuaranteeRef::dec("DEC-030")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-TIME-AXES", statement: "Observed wall time, monotonic deadline, HLC, commit order, stream position, and causality remain distinct types.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/16_IDENTITY_TIME_AND_NAVIGATION.md", gates: &[GateId::G2], witness: "DEC-061; LEG-025; LEG-073", failure_disposition: "hard finding: timestamp laundering", derives_from: &[GuaranteeRef::dec("DEC-061")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-DOC-STATUS", statement: "Every normative document declares status, contract ID, authority scope, supersession, and reconciliation date.", kind: GuaranteeKind::BootstrapAssertion, lifetime: GuaranteeLifetime::Permanent, owner: "docs/00_CONSTITUTION.md", gates: &[GateId::G0], witness: "audit.py front-matter check", failure_disposition: "hard finding: missing front-matter", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-PLACEHOLDER-LAW", statement: "Normative target documents contain no TBD, implementation-decides, or unnamed future-cleanup clauses.", kind: GuaranteeKind::BootstrapAssertion, lifetime: GuaranteeLifetime::Permanent, owner: "docs/00_CONSTITUTION.md", gates: &[GateId::G0], witness: "audit.py placeholder scan", failure_disposition: "hard finding: normative placeholder", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-LEGACY-OBLIGATION", statement: "Legacy behavior is deleted only after a named successor obligation and independent witness exist.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/21_LEGACY_SEMANTIC_OBLIGATIONS.md", gates: &[GateId::G0, GateId::G9], witness: "docs/34 coverage; audit.py LEG parity", failure_disposition: "hard finding: legacy deleted without successor and witness", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-ECS-NOT-ONTOLOGY", statement: "ECS is a typed table/system implementation algebra; Contract remains the semantic primitive and Tile the physical materialization primitive.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/18_DATA_ORIENTED_ECS.md", gates: &[GateId::G8], witness: "docs/18; docs/31", failure_disposition: "hard finding: ECS treated as ontology", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-BVISOR-HONESTY", statement: "Bvisor may report only established postconditions and never decides semantic restart legality.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/09_BVISOR.md", gates: &[GateId::G5], witness: "LEG-042; LEG-043", failure_disposition: "hard finding: Bvisor overclaim", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-BATQL-FROZEN", statement: "BatQL 1.0 conceptual grammar is frozen except for defects proven by parser, type, or conformance work.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "companion/BATQL_LANGUAGE.md", gates: &[GateId::G4], witness: "companion 13 language-change law; DEC-060", failure_disposition: "hard finding: unproven grammar change", derives_from: &[GuaranteeRef::dec("DEC-060")], refines: &[], discharges: &[], supersedes: &[] },
];
