//! Frozen bootstrap invariants. Stable IDs become TestPak contract IDs.
//!
//! Each SEED fact carries its own guarantee classification (DEC-070): kind,
//! lifetime, owner, gates, witness, source-native failure disposition, and
//! explicit relations. Shared types live in `spec/guarantees.rs`; this file is
//! the sole owner of the SEED facts and their classification.

use crate::gates::GateId;
use crate::guarantees::{BootstrapToolId, GuaranteeKind, GuaranteeLifetime, GuaranteeRef, WitnessRef};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct InvariantSpec {
    pub id: &'static str,
    pub statement: &'static str,
    pub kind: GuaranteeKind,
    pub lifetime: GuaranteeLifetime,
    pub owner: &'static str,
    pub gates: &'static [GateId],
    /// Typed witness citations (5.5E2): WHICH owned evidence obligations this
    /// law depends on. Every reference resolves or the row is refused.
    pub witnesses: &'static [WitnessRef],
    /// How a human should understand the cited evidence. May be empty.
    pub witness_note: &'static str,
    pub failure_disposition: &'static str,
    /// Typed relations (5.5E2): a reference names its family in the type, so
    /// a decision cited as a legacy obligation has no spelling. Whether each
    /// reference resolves to a declared row is an executed seedcheck law.
    pub derives_from: &'static [GuaranteeRef],
    pub refines: &'static [GuaranteeRef],
    pub discharges: &'static [GuaranteeRef],
    pub supersedes: &'static [GuaranteeRef],
}

pub const INVARIANTS: &[InvariantSpec] = &[
    InvariantSpec { id: "SEED-ONE-OWNER", statement: "Every stable semantic concept has one canonical owner.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/00_CONSTITUTION.md", gates: &[GateId::G0], witnesses: &[WitnessRef::BootstrapTool(BootstrapToolId::AuditPy), WitnessRef::contract("BP-SELF-EXPLAINING-1")], witness_note: "contract-id uniqueness scan; the self-explaining-repository law", failure_disposition: "hard structural finding: duplicate ownership", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-SYNCBAT-ONE-HEARTBEAT", statement: "SyncBat contains the runtime, PakVM, Bvisor, world, and port planes as modules of one runtime crate.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/03_REPOSITORY_AND_PACKAGES.md", gates: &[GateId::G0], witnesses: &[WitnessRef::BootstrapTool(BootstrapToolId::Seedcheck), WitnessRef::BootstrapTool(BootstrapToolId::AuditPy)], witness_note: "SyncBatPlane::ALL plane-file checks in both independent derivations", failure_disposition: "hard finding: standalone plane package", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-STANDALONE-VM", statement: "No standalone bat-vm, vpak, pakvm, or bvisor package exists in the target graph.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/03_REPOSITORY_AND_PACKAGES.md", gates: &[GateId::G0], witnesses: &[WitnessRef::BootstrapTool(BootstrapToolId::Seedcheck), WitnessRef::BootstrapTool(BootstrapToolId::AuditPy)], witness_note: "PACKAGES inventory; forbidden-path scan", failure_disposition: "hard finding: standalone VM package", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-FBAT-CORE", statement: ".fbat is BatPak journal authority and does not imply a FileBat package.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/05_STORAGE_FBAT_AND_TILES.md", gates: &[GateId::G2], witnesses: &[WitnessRef::BootstrapTool(BootstrapToolId::AuditPy)], witness_note: "stale-vocabulary scan", failure_disposition: "hard finding: FileBat package reintroduced", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-PAKVM-NAME", statement: "PakVM names the machine; .vpak names the executable package profile; ProgramImage and WorldImage name semantic values.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/07_PAKVM_ISA.md", gates: &[GateId::G0, GateId::G5], witnesses: &[WitnessRef::BootstrapTool(BootstrapToolId::AuditPy)], witness_note: "stale-vocabulary scan", failure_disposition: "hard finding: name laundering", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-DUAL-PRODUCT", statement: "HostBat and platform-backend product models do not coexist with WorldImage, PakVM, and Bvisor.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/02_SYSTEM_MODEL.md", gates: &[GateId::G0], witnesses: &[WitnessRef::BootstrapTool(BootstrapToolId::AuditPy), WitnessRef::contract("BP-FINAL-AUDIT-1")], witness_note: "stale-vocabulary scan; final contradiction audit", failure_disposition: "hard finding: dual product model", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-AMBIENT-AUTHORITY", statement: "PakVM programs have no syscall, host path, raw descriptor, ambient clock, entropy, environment, or process instruction.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/07_PAKVM_ISA.md", gates: &[GateId::G5], witnesses: &[WitnessRef::leg("LEG-066"), WitnessRef::contract("BP-GAUNTLET-1")], witness_note: "capability enforcement", failure_disposition: "hard finding: ambient-authority instruction", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-SEMANTIC-ZERO-LEAKAGE", statement: "Dependency-owned mechanism types do not define ordinary public BatPak semantics.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/20_DEPENDENCY_SOVEREIGNTY.md", gates: &[GateId::G0], witnesses: &[WitnessRef::BootstrapTool(BootstrapToolId::Seedcheck), WitnessRef::dec("DEC-068")], witness_note: "production-token scan; the AST gate", failure_disposition: "hard finding: dependency type in public semantics", derives_from: &[GuaranteeRef::dec("DEC-068")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-SYNC-FIRST", statement: "Production semantic APIs require no hidden async runtime, hidden thread, or hidden executor.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/08_SYNCBAT_RUNTIME.md", gates: &[GateId::G0, GateId::G5], witnesses: &[WitnessRef::leg("LEG-080"), WitnessRef::BootstrapTool(BootstrapToolId::Seedcheck)], witness_note: "no-tokio scan", failure_disposition: "hard finding: hidden executor", derives_from: &[], refines: &[GuaranteeRef::leg("LEG-080")], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-STD-SEMANTIC-PROFILES", statement: "BatPak and SyncBat qualify their semantic profiles under no_std + alloc; std and browser host mechanisms remain explicit adapters.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/20_DEPENDENCY_SOVEREIGNTY.md", gates: &[GateId::G0, GateId::G5], witnesses: &[WitnessRef::dec("DEC-065")], witness_note: "qualification matrix", failure_disposition: "hard finding: std in semantic profile", derives_from: &[GuaranteeRef::dec("DEC-065")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-CONCEPT-SPINE", statement: "Primary semantic types live in root concept files paired with same-name implementation directories; no universal _types drawer exists.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/04_TYPE_SYSTEM_AND_SOURCE_LAYOUT.md", gates: &[GateId::G0], witnesses: &[WitnessRef::dec("DEC-068"), WitnessRef::BootstrapTool(BootstrapToolId::Seedcheck)], witness_note: "the AST gate", failure_disposition: "hard finding: universal types drawer", derives_from: &[GuaranteeRef::dec("DEC-068")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-INLINE-DOMAIN-TYPES", statement: "No domain-significant named type is declared inside a function or hidden in an unrelated algorithm file.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/04_TYPE_SYSTEM_AND_SOURCE_LAYOUT.md", gates: &[GateId::G1, GateId::G3], witnesses: &[WitnessRef::dec("DEC-068")], witness_note: "the AST gate", failure_disposition: "hard finding: inline domain type", derives_from: &[GuaranteeRef::dec("DEC-068")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-EXPLICIT-EFFECTS", statement: "Every effect crosses a named capability terminal and produces a typed outcome.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/08_SYNCBAT_RUNTIME.md", gates: &[GateId::G6], witnesses: &[WitnessRef::leg("LEG-036"), WitnessRef::leg("LEG-061"), WitnessRef::contract("BP-GAUNTLET-1")], witness_note: "", failure_disposition: "hard finding: effect without capability terminal", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-INDEPENDENT-ORACLE", statement: "No optimized or generated subsystem is its own only oracle.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/24_GAUNTLET.md", gates: &[GateId::G3, GateId::G8], witnesses: &[WitnessRef::leg("LEG-079"), WitnessRef::leg("LEG-049")], witness_note: "", failure_disposition: "hard finding: self-blessing oracle", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-AUDITED-DENOMINATOR", statement: "Every planned proof unit terminates with an explicit disposition.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/24_GAUNTLET.md", gates: &[GateId::G3, GateId::G9], witnesses: &[WitnessRef::leg("LEG-049"), WitnessRef::contract("BP-LEGACY-INVARIANT-COVERAGE-1"), WitnessRef::BootstrapTool(BootstrapToolId::AuditPy)], witness_note: "coverage table; declaration parity", failure_disposition: "hard finding: unclassified proof unit", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-MUTERPRATER-SCOPE", statement: "Muterprater owns mutation testing only and lives inside TestPak.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/12_TESTPAK.md", gates: &[GateId::G3], witnesses: &[WitnessRef::dec("DEC-015")], witness_note: "", failure_disposition: "hard finding: Muterprater outside TestPak", derives_from: &[GuaranteeRef::dec("DEC-015")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-BOUNDED-PUSH", statement: "Long-lived push is bounded per message, batch, buffer, and retained window and has a durable pull recovery path.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/17_DELIVERY_AND_CONCURRENCY.md", gates: &[GateId::G6], witnesses: &[WitnessRef::leg("LEG-032"), WitnessRef::leg("LEG-060")], witness_note: "", failure_disposition: "hard finding: unbounded push", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-AVAILABILITY-AXES", statement: "Value availability, K3 truth, decision, completeness, freshness, and proof disposition are distinct axes.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/04_TYPE_SYSTEM_AND_SOURCE_LAYOUT.md", gates: &[GateId::G2], witnesses: &[WitnessRef::dec("DEC-030"), WitnessRef::contract("BP-NUMERIC-1")], witness_note: "", failure_disposition: "hard finding: collapsed availability axis", derives_from: &[GuaranteeRef::dec("DEC-030")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-TIME-AXES", statement: "Observed wall time, monotonic deadline, HLC, commit order, stream position, and causality remain distinct types.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/16_IDENTITY_TIME_AND_NAVIGATION.md", gates: &[GateId::G2], witnesses: &[WitnessRef::dec("DEC-061"), WitnessRef::leg("LEG-025"), WitnessRef::leg("LEG-073")], witness_note: "", failure_disposition: "hard finding: timestamp laundering", derives_from: &[GuaranteeRef::dec("DEC-061")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-DOC-STATUS", statement: "Every normative document declares status, contract ID, authority scope, supersession, reconciliation date, and its ReconciliationEpoch corpus membership.", kind: GuaranteeKind::BootstrapAssertion, lifetime: GuaranteeLifetime::Permanent, owner: "docs/00_CONSTITUTION.md", gates: &[GateId::G0], witnesses: &[WitnessRef::BootstrapTool(BootstrapToolId::AuditPy)], witness_note: "front-matter check", failure_disposition: "hard finding: missing front-matter", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-NO-PLACEHOLDER-LAW", statement: "Normative target documents contain no TBD, implementation-decides, or unnamed future-cleanup clauses.", kind: GuaranteeKind::BootstrapAssertion, lifetime: GuaranteeLifetime::Permanent, owner: "docs/00_CONSTITUTION.md", gates: &[GateId::G0], witnesses: &[WitnessRef::BootstrapTool(BootstrapToolId::AuditPy)], witness_note: "placeholder scan", failure_disposition: "hard finding: normative placeholder", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-LEGACY-OBLIGATION", statement: "Legacy behavior is deleted only after a named successor obligation and independent witness exist.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/21_LEGACY_SEMANTIC_OBLIGATIONS.md", gates: &[GateId::G0, GateId::G9], witnesses: &[WitnessRef::contract("BP-LEGACY-INVARIANT-COVERAGE-1"), WitnessRef::BootstrapTool(BootstrapToolId::AuditPy)], witness_note: "coverage table; LEG declaration parity", failure_disposition: "hard finding: legacy deleted without successor and witness", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-ECS-NOT-ONTOLOGY", statement: "ECS is a typed table/system implementation algebra; Contract remains the semantic primitive and Tile the physical materialization primitive.", kind: GuaranteeKind::ArchitectureConstraint, lifetime: GuaranteeLifetime::Permanent, owner: "docs/18_DATA_ORIENTED_ECS.md", gates: &[GateId::G8], witnesses: &[WitnessRef::contract("BP-ECS-1"), WitnessRef::contract("BP-FINAL-AUDIT-1")], witness_note: "", failure_disposition: "hard finding: ECS treated as ontology", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-BVISOR-HONESTY", statement: "Bvisor may report only established postconditions and never decides semantic restart legality.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/09_BVISOR.md", gates: &[GateId::G5], witnesses: &[WitnessRef::leg("LEG-042"), WitnessRef::leg("LEG-043")], witness_note: "", failure_disposition: "hard finding: Bvisor overclaim", derives_from: &[], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-BATQL-FROZEN", statement: "BatQL 1.0 conceptual grammar is frozen except for defects proven by parser, type, or conformance work.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "companion/BATQL_LANGUAGE.md", gates: &[GateId::G4], witnesses: &[WitnessRef::contract("BP-BATQL-LANGUAGE-1"), WitnessRef::dec("DEC-060")], witness_note: "section 13 language-change law", failure_disposition: "hard finding: unproven grammar change", derives_from: &[GuaranteeRef::dec("DEC-060")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-LAYERED-DYNAMIC-VERIFICATION", statement: "Verification basis, method, claim, coverage, enforcement posture, freshness, and result remain separate typed axes; no aggregate assurance ladder substitutes for them.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/38_DYNAMIC_VERIFICATION_AND_CONFORMANCE.md", gates: &[GateId::G0, GateId::G3, GateId::G9], witnesses: &[WitnessRef::dec("DEC-077"), WitnessRef::contract("BP-DYNAMIC-VERIFICATION-1")], witness_note: "layered verification axes; no assurance ladder", failure_disposition: "hard finding: aggregate assurance ladder", derives_from: &[GuaranteeRef::dec("DEC-077")], refines: &[GuaranteeRef::seed("SEED-AVAILABILITY-AXES")], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-MODEL-TRACE-SEPARATION", statement: "Contract projections, independent references, direct independent boundaries, and runtime observations remain distinct; a generated projection or self-observation cannot be the sole independent oracle.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/38_DYNAMIC_VERIFICATION_AND_CONFORMANCE.md", gates: &[GateId::G3, GateId::G6, GateId::G9], witnesses: &[WitnessRef::dec("DEC-077"), WitnessRef::contract("BP-DYNAMIC-VERIFICATION-1")], witness_note: "model/trace separation; projection is not the sole oracle", failure_disposition: "hard finding: projection as sole independent oracle", derives_from: &[GuaranteeRef::dec("DEC-077")], refines: &[GuaranteeRef::seed("SEED-INDEPENDENT-ORACLE")], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-RUNTIME-CONFORMANCE-NO-REWRITE", statement: "Runtime verification may refuse before an admitted irreversible boundary or append conformance evidence, but it never rewrites semantic law, durable history, or proof disposition.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/38_DYNAMIC_VERIFICATION_AND_CONFORMANCE.md", gates: &[GateId::G3, GateId::G6, GateId::G9], witnesses: &[WitnessRef::dec("DEC-078"), WitnessRef::contract("BP-DYNAMIC-VERIFICATION-1")], witness_note: "refuse-or-append conformance; never rewrite law, history, or disposition", failure_disposition: "hard finding: runtime conformance rewrites law or history", derives_from: &[GuaranteeRef::dec("DEC-078")], refines: &[GuaranteeRef::dec("DEC-075")], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-CANDIDATE-NOT-AUTHORITY", statement: "A generated, machine-assisted, searched, transferred, repaired, or human-authored candidate remains noncanonical until exact qualification and promotion; candidate origin confers no authority.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/39_SPROUTING_NURSERY_AND_PROMOTION.md", gates: &[GateId::G3, GateId::G8, GateId::G9], witnesses: &[WitnessRef::dec("DEC-079"), WitnessRef::dec("DEC-080"), WitnessRef::contract("BP-SPROUTING-1")], witness_note: "candidate noncanonical until qualified; origin confers no authority", failure_disposition: "hard finding: candidate origin claims authority", derives_from: &[GuaranteeRef::dec("DEC-079"), GuaranteeRef::dec("DEC-080")], refines: &[GuaranteeRef::seed("SEED-ONE-OWNER")], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-BOUNDED-SEARCH", statement: "Every candidate search declares finite candidate, logical-work, memory, and monotonic-deadline bounds and receipts the actual work performed.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/39_SPROUTING_NURSERY_AND_PROMOTION.md", gates: &[GateId::G3, GateId::G8, GateId::G9], witnesses: &[WitnessRef::dec("DEC-081"), WitnessRef::contract("BP-SPROUTING-1")], witness_note: "declared search bounds; work receipts", failure_disposition: "hard finding: unbounded or unreceipted search", derives_from: &[GuaranteeRef::dec("DEC-081")], refines: &[], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-HOLDOUT-INDEPENDENCE", statement: "Search, qualification, holdout, and regression inputs carry explicit evaluation-set roles; holdout evidence for a campaign cannot reuse its search inputs.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/39_SPROUTING_NURSERY_AND_PROMOTION.md", gates: &[GateId::G3, GateId::G8, GateId::G9], witnesses: &[WitnessRef::dec("DEC-081"), WitnessRef::contract("BP-SPROUTING-1")], witness_note: "evaluation-set roles; holdout cannot reuse search inputs", failure_disposition: "hard finding: holdout reuses search inputs", derives_from: &[GuaranteeRef::dec("DEC-081")], refines: &[GuaranteeRef::seed("SEED-INDEPENDENT-ORACLE")], discharges: &[], supersedes: &[] },
    InvariantSpec { id: "SEED-GENERATE-WIDE-QUALIFY-DEEP", statement: "A complete speculative implementation tree may be generated before implementation gates close, but authority advances only through dependency-ordered qualification; later green cannot bless an unresolved earlier frontier, and candidate work cannot modify its frozen judge or prior evidence.", kind: GuaranteeKind::SemanticLaw, lifetime: GuaranteeLifetime::Permanent, owner: "docs/39_SPROUTING_NURSERY_AND_PROMOTION.md", gates: &[GateId::G0, GateId::G3, GateId::G9], witnesses: &[WitnessRef::dec("DEC-082"), WitnessRef::contract("BP-SPROUTING-1")], witness_note: "dependency-ordered frontier; later green cannot bless earlier red; frozen judge", failure_disposition: "hard finding: authority advances out of dependency order or judge mutated", derives_from: &[GuaranteeRef::dec("DEC-082")], refines: &[GuaranteeRef::dec("DEC-048"), GuaranteeRef::dec("DEC-075")], discharges: &[], supersedes: &[] },
];
