//! Frozen clean-room legacy semantic obligation facts.

use crate::gates::GateId;

/// Whether a retained obligation still gates clean-room implementation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObligationStatus {
    /// Still gating: a clean successor must discharge it at its gate.
    Active,
    /// Discharged; retained as historical evidence and no longer gating.
    Closed,
}

/// The cross-version / cross-format compatibility burden an obligation carries.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CompatibilityDisposition {
    /// Pure semantic law with no durable-byte or wire compatibility burden.
    None,
    /// Must keep decoding older accepted bytes through explicit migration.
    ReadOlderAccepted,
    /// Every persisted format/version pair resolves to one canonical open or typed refusal.
    CanonicalOrTypedRefusal,
    /// Canonical identity, bytes, or goldens are frozen and versioned.
    FrozenCanonicalIdentity,
}

/// The condition under which the obligation may retire from active gating.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DeletionCondition {
    /// Permanent constitutional law; keeps gating regardless of implementation progress.
    Never,
    /// Dischargeable once the named clean successor closes at its gate.
    OnSuccessorGateClosure,
    /// Additionally bound: cannot retire until its declared compatibility window closes.
    OnCompatibilityWindowExpiry,
}

/// The witness ROUTE for one obligation (5.5E4d): a posture, not proof
/// evidence. `CanonicalProofRows` means the required witness identities are
/// obtained from active `spec/proof.rs` rows whose guarantee is this exact
/// LEG identity - no free-text plan substitutes for those rows. `Planned`
/// means no canonical active proof row has yet been admitted, and the
/// nonempty text states the required future evidence route; it is never
/// counted as an active proof row and is not release evidence. Moving from
/// Planned to CanonicalProofRows is atomic with real row admission, docs/24
/// meaning, typed bindings, projection targets, and hostile fixtures.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LegacyWitnessRequirement {
    CanonicalProofRows,
    Planned(&'static str),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LegacyObligation {
    pub id: &'static str,
    pub law: &'static str,
    /// The legacy evidence pointer docs/21 previously authored (5.5E4d).
    pub legacy_evidence: &'static str,
    pub clean_owner: &'static str,
    /// The mechanism disposition docs/21 previously authored (5.5E4d).
    pub mechanism_disposition: &'static str,
    /// The one witness route for this obligation.
    pub witness_requirement: LegacyWitnessRequirement,
    pub gates: &'static [GateId],
    pub compatibility_disposition: CompatibilityDisposition,
    pub deletion_condition: DeletionCondition,
    pub active_or_closed_status: ObligationStatus,
}

pub const OBLIGATIONS: &[LegacyObligation] = &[
    LegacyObligation { id: "LEG-001", law: "One live writer and one physical commit order per journal", legacy_evidence: "03_INVARIANTS.md, store writer runtime", clean_owner: "batpak::store", mechanism_disposition: "Reimplement cleanly", witness_requirement: LegacyWitnessRequirement::Planned("concurrency model + duplicate-writer refusal"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-002", law: "Accepted event bytes are immutable; shape evolves on read", legacy_evidence: "03_INVARIANTS.md, event migration tests", clean_owner: "batpak::event", mechanism_disposition: "Preserve readers, replace codec authority", witness_requirement: LegacyWitnessRequirement::Planned("historical vectors + future-version refusal"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::ReadOlderAccepted, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-003", law: "Batch append is atomically visible", legacy_evidence: "batch invariants/tests", clean_owner: "batpak::store", mechanism_disposition: "Reimplement", witness_requirement: LegacyWitnessRequirement::Planned("concurrent reader + mutation + crash model"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-004", law: "Incomplete batch is discarded or canonically refused after crash/rotation", legacy_evidence: "cold-start and batch recovery tests", clean_owner: "batpak::store", mechanism_disposition: "Reimplement", witness_requirement: LegacyWitnessRequirement::Planned("cross-segment crash matrix"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-005", law: "Physical durability and per-lane logical frontiers remain distinct", legacy_evidence: "lane frontier model/invariants", clean_owner: "batpak::frontier", mechanism_disposition: "Preserve semantics, redesign types", witness_requirement: LegacyWitnessRequirement::Planned("algebra + crash/reopen"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-006", law: "Visibility fences can leave durable events hidden and that state survives reopen/export", legacy_evidence: "visibility fence code/invariants", clean_owner: "batpak::visibility", mechanism_disposition: "Reimplement without copied topology", witness_requirement: LegacyWitnessRequirement::Planned("cancel/reopen/snapshot fixtures"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-007", law: "Durable idempotency returns original receipt after reopen within retention law", legacy_evidence: "idempotency authority tests", clean_owner: "batpak::store", mechanism_disposition: "Preserve authority, new representation allowed", witness_requirement: LegacyWitnessRequirement::Planned("reopen, compaction, export/restore, damage refusal"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-008", law: "Store lineage and authority generation reject foreign mutable state", legacy_evidence: "store identity/generation issue work", clean_owner: "batpak::store", mechanism_disposition: "Strengthen", witness_requirement: LegacyWitnessRequirement::Planned("transplant/fork/restore fixtures"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-009", law: "Compaction publication and namespace durability are separate from content writes", legacy_evidence: "compaction ADRs/tests", clean_owner: "batpak::compaction", mechanism_disposition: "Reimplement", witness_requirement: LegacyWitnessRequirement::Planned("phase fault matrix + directory durability"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-010", law: "Recovery terminal is committed prefix, rollback, or typed refusal", legacy_evidence: "SimFs/ShadowFs recovery corpus", clean_owner: "batpak::recovery", mechanism_disposition: "Preserve model; rewrite mechanism", witness_requirement: LegacyWitnessRequirement::Planned("independent crash oracle"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-011", law: "Fork may share immutable sealed data but never mutable authorities", legacy_evidence: "fork invariants and hostile filesystem tests", clean_owner: "batpak::lifecycle", mechanism_disposition: "Reimplement", witness_requirement: LegacyWitnessRequirement::Planned("parent/fork isolation + crash matrix"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-012", law: "Snapshot binds exact source cut and evidence, not later frontier", legacy_evidence: "snapshot report ADR/tests", clean_owner: "batpak::lifecycle", mechanism_disposition: "Preserve semantics", witness_requirement: LegacyWitnessRequirement::Planned("concurrent append/source-stamp oracle"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-013", law: "Import preserves source content while assigning destination-local identity/order", legacy_evidence: "import recovery/model", clean_owner: "batpak::lifecycle", mechanism_disposition: "Reimplement", witness_requirement: LegacyWitnessRequirement::Planned("content parity + identity distinction"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-014", law: "Restore distinguishes missing cache, missing authority, lineage mismatch, and corruption", legacy_evidence: "recovery manifests/tests", clean_owner: "batpak::recovery", mechanism_disposition: "Strengthen taxonomy", witness_requirement: LegacyWitnessRequirement::Planned("hostile artifact matrix"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-015", law: "Crypto shredding destroys plaintext authority without rewriting accepted ciphertext/history", legacy_evidence: "keyscope and delivery tests", clean_owner: "batpak::secret", mechanism_disposition: "Preserve law; new key representation allowed", witness_requirement: LegacyWitnessRequirement::Planned("sibling-scope, tamper, reopen, compaction"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-016", law: "Storage adapters satisfy one handle/transaction/crash conformance corpus", legacy_evidence: "StoreFs conformance, ADR-0034", clean_owner: "batpak::storage_port", mechanism_disposition: "Rename/rebuild interface as needed", witness_requirement: LegacyWitnessRequirement::Planned("native + memory + hostile adapter corpus"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-017", law: "Fast-start checkpoint/mmap/SIDX artifacts are derived and never source authority", legacy_evidence: "cold-start ADRs/invariants", clean_owner: "batpak::tile", mechanism_disposition: "Supersede with generation-bound tiles", witness_requirement: LegacyWitnessRequirement::Planned("delete/corrupt/transplant/rebuild"), gates: &[GateId::G2, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-018", law: "SIDX has explicit fixed layout and independent frame-scan fallback", legacy_evidence: "store/segment/sidx.rs", clean_owner: "batpak::tile", mechanism_disposition: "First ColumnTile adopter", witness_requirement: LegacyWitnessRequirement::Planned("simple scan equivalence + byte goldens"), gates: &[GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-019", law: "Derived cache cannot authenticate itself: SIDX and other unauthenticated derived material may accelerate locate or describe suspicion but cannot authenticate themselves, and an independently corroborated derived row proves only that exact row-to-authoritative-frame relationship while authenticating neither sibling rows nor table row count nor table ordering nor a claimed tail boundary nor middle or trailing completeness nor absence nor loss nor the authority of the table itself; unauthenticated derived material cannot prove safety and cannot prove loss, so a discrepancy may cause suspicion a derived-state rebuild a fallback to authoritative storage or a typed refusal where stronger evidence is required but never an authoritative proven-loss or proven-safety conclusion from derived material alone; there is no trusted-local SIDX authority, permissive compatibility mode, corroborated-table authority, or derived proof of absence", legacy_evidence: "untrusted-manifest ADR/invariants", clean_owner: "batpak::integrity", mechanism_disposition: "Keep as constitutional law", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::Never, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-020", law: "Complexity regressions require work/count evidence, not noisy stopwatch alone", legacy_evidence: "complexity invariant/bench gates", clean_owner: "testpak::bench", mechanism_disposition: "Strengthen", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G3, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-021", law: "Coordinate names a logical context stream, not a filesystem/network shard", legacy_evidence: "model/invariants", clean_owner: "batpak::coordinate", mechanism_disposition: "Keep name and law", witness_requirement: LegacyWitnessRequirement::Planned("normalization/bounds/round-trip"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-022", law: "Commit pagination, ancestry, delivery cursor, projection path, and world path are distinct axes", legacy_evidence: "traversal invariant and issues #199-#206/#208", clean_owner: "batpak::navigation", mechanism_disposition: "Strengthen type separation", witness_requirement: LegacyWitnessRequirement::Planned("cursor transplant + ordering oracles"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-023", law: "Content digest, event commitment, predecessor topology, signature, inclusion, and anchor are separate claims: ContentDigest equality proves payload-content equality only within its declared digest scope and never proves EventCommitment equality, EventCommitment binds the complete event identity and committed semantic envelope required by the storage contract while its exact fields and bytes remain G2 format constants, predecessor verification requires the exact immediate predecessor for the canonical stream identity so an event appearing somewhere in a verified set is not thereby the immediate predecessor, legal genesis occurs only at the lawful stream head, and a derived index may locate candidate authority bytes but may not select the expected authority bytes and then use those selected bytes to authenticate its own selection; lane isolation is owned by LEG-050 and visible linearization by LEG-067 and this row cites rather than absorbs them", legacy_evidence: "authenticated-store issue family", clean_owner: "batpak::integrity", mechanism_disposition: "Strengthen", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-024", law: "Event kind allocation and parsing are total, bounded, and collision-checked", legacy_evidence: "EventKind tests/registry", clean_owner: "batpak::event", mechanism_disposition: "Supersede ambient registry with explicit composition", witness_requirement: LegacyWitnessRequirement::Planned("compile/composition collision fixtures"), gates: &[GateId::G1, GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-025", law: "HLC chronology does not replace global commit order, stream position, or causality", legacy_evidence: "clock/order issue #208", clean_owner: "batpak::time", mechanism_disposition: "Repair contradictory legacy naming", witness_requirement: LegacyWitnessRequirement::Planned("algebra + deterministic simulation"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-026", law: "Entity-local aggregate and selector-backed region materialization are different contracts", legacy_evidence: "issue #199", clean_owner: "batpak::projection", mechanism_disposition: "Implement cleanly", witness_requirement: LegacyWitnessRequirement::Planned("coordinate-bearing replay/source-stamp tests"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-027", law: "Typed path/collation identity is versioned, bounded, locale-independent, and non-coercing", legacy_evidence: "issue #200", clean_owner: "batpak::path", mechanism_disposition: "Implement cleanly", witness_requirement: LegacyWitnessRequirement::Planned("independent comparator/encoder"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::FrozenCanonicalIdentity, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-028", law: "Sparse projection trees are disposable views with bounded get/children/scan whose item limit and work budget constrain discovery before decode allocation or materialization, and whose cursors bind store lineage generation source cut direction selector and filters so a transplanted or stale cursor fails closed rather than resuming against a different traversal", legacy_evidence: "issue #201", clean_owner: "batpak::projection", mechanism_disposition: "Implement cleanly", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-029", law: "Projection query authority binds contract, selector, shape, bounds, source stamp, completeness, and proof, and every page carries ordered entries a completeness posture a lawful next cursor a source stamp a WorkObservation and a proof result, so concatenated valid pages equal a one-shot reference traversal without gaps duplicates or reordering and no page claims completeness merely by filling its requested size", legacy_evidence: "issue #202", clean_owner: "batpak::projection_query", mechanism_disposition: "Implement end-to-end", witness_requirement: LegacyWitnessRequirement::Planned("cross-layer equivalence oracle"), gates: &[GateId::G2, GateId::G6, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-030", law: "Full and incremental projection application agree at the same cut", legacy_evidence: "projection tests", clean_owner: "batpak::projection", mechanism_disposition: "Preserve", witness_requirement: LegacyWitnessRequirement::Planned("differential and mutation"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-031", law: "Fold fusion equals separate folds over one frozen traversal", legacy_evidence: "projection fusion laws", clean_owner: "batpak::projection", mechanism_disposition: "Optimize later", witness_requirement: LegacyWitnessRequirement::Planned("banana-split oracle"), gates: &[GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-032", law: "Lossy push is awareness; durable cursor pull is at-least-once replay truth", legacy_evidence: "ADR-0011", clean_owner: "batpak::delivery", mechanism_disposition: "Preserve distinction", witness_requirement: LegacyWitnessRequirement::Planned("lag/overrun and restart fixtures"), gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-033", law: "Reaction output is typed, atomically staged, and dropped structurally on handler error", legacy_evidence: "ReactionBatch and typed reactor tests", clean_owner: "syncbat::runtime", mechanism_disposition: "Generalize into EffectBatch", witness_requirement: LegacyWitnessRequirement::Planned("error/no-partial and causation fixtures"), gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-034", law: "Durable cursor checkpoint, at-least-once witness, panic recovery, restart budget, and explicit join errors remain visible", legacy_evidence: "reactor/cursor worker", clean_owner: "syncbat::runtime", mechanism_disposition: "Reimplement as ProcessContract runtime", witness_requirement: LegacyWitnessRequirement::Planned("deterministic schedule/reopen"), gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-035", law: "Cooperative and threaded drivers preserve one logical transition protocol", legacy_evidence: "writer/spawn seam", clean_owner: "syncbat::runtime", mechanism_disposition: "Preserve, simplify", witness_requirement: LegacyWitnessRequirement::Planned("trace equivalence"), gates: &[GateId::G3, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-036", law: "Declared effect row must contain observed effects and receipt payload", legacy_evidence: "current SyncBat", clean_owner: "syncbat::runtime", mechanism_disposition: "Preserve, compile from contracts", witness_requirement: LegacyWitnessRequirement::Planned("denial-before-effect + omission mutants"), gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-037", law: "Atomic typed batch append is one runtime effect, not a bypass: heterogeneous typed publication commands join one atomic group only where the admitting capability owns their common authority boundary, input order and receipt order correspond exactly, an admitted atomic group never publishes a partial durable subset, and this is not an arbitrary distributed transaction across unrelated ports or authorities", legacy_evidence: "issue #229", clean_owner: "batpak::effect", mechanism_disposition: "Implement", witness_requirement: LegacyWitnessRequirement::Planned("single/batch equivalence + failure atomicity"), gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-038", law: "External effects record requested/attempted/completed/failed/outcome-unknown and recovery class", legacy_evidence: "outbox/reactor/attempt work", clean_owner: "syncbat::runtime", mechanism_disposition: "Generalize", witness_requirement: LegacyWitnessRequirement::Planned("crash between external call and receipt"), gates: &[GateId::G5, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-039", law: "Public async integration does not leak raw Flume semantics or require an executor", legacy_evidence: "issue #209", clean_owner: "syncbat::runtime", mechanism_disposition: "Supersede public mechanism", witness_requirement: LegacyWitnessRequirement::Planned("wait/poll/browser adapter parity"), gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-040", law: "Schemas have language-neutral identity, versions, canonical bytes, and goldens; Rust paths are diagnostic", legacy_evidence: "HostBat schema work", clean_owner: "batpak::schema", mechanism_disposition: "Keep semantics, dissolve shell", witness_requirement: LegacyWitnessRequirement::Planned("composition/golden fixtures"), gates: &[GateId::G2, GateId::G5], compatibility_disposition: CompatibilityDisposition::FrozenCanonicalIdentity, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-041", law: "Composition identity is deterministic and changes with interface authority", legacy_evidence: "HostBat fingerprints", clean_owner: "batpak::world", mechanism_disposition: "Supersede", witness_requirement: LegacyWitnessRequirement::Planned("order-independence and collision tests"), gates: &[GateId::G5], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-042", law: "One AttemptId binds start, execution, report, and reconciliation and distinguishes cancellation before admission from cancellation after admission, so a cancelled admitted attempt is never read as proof of non-commit and a retry of the same logical operation receives a new AttemptId without erasing prior attempt evidence", legacy_evidence: "Bvisor issue #187", clean_owner: "syncbat::bvisor", mechanism_disposition: "Keep and strengthen", witness_requirement: LegacyWitnessRequirement::Planned("stale report cross-attempt rejection"), gates: &[GateId::G5], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-043", law: "Reports state established postconditions, not planned mechanisms", legacy_evidence: "Bvisor issue #218", clean_owner: "syncbat::bvisor", mechanism_disposition: "Keep general law; archive native-exec details", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G5], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-044", law: "Admission decision circuits are bounded, canonical, and independently cross-checked", legacy_evidence: "existing AdmissionProgram", clean_owner: "syncbat::pakvm", mechanism_disposition: "Demote to specialized lowering", witness_requirement: LegacyWitnessRequirement::Planned("typed evaluator vs circuit differential"), gates: &[GateId::G3, GateId::G5], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-045", law: "Transport is bounded, domain-thin, and cannot launder proof", legacy_evidence: "NetBat", clean_owner: "netbat", mechanism_disposition: "Preserve, regenerate contracts", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-046", law: "One declaration becomes one typed Contract IR and generated lowerings whose typed effect routing is closed and exhaustive: a missing duplicate or unknown route identity a decoder that does not match the declared type a missing effect capability or a missing receipt projection fails closed, route discovery is never ambient linker registration startup constructors or process-global registries, and the generated router owns structure and glue rather than application domain transition logic", legacy_evidence: "issue #214/current MacBat", clean_owner: "macbat-compiler", mechanism_disposition: "Keep, rewrite cleanly", witness_requirement: LegacyWitnessRequirement::Planned("snapshots, origins, compile-fail, parity"), gates: &[GateId::G1], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-047", law: "Error handling class and public error shape do not drift into side tables", legacy_evidence: "error census/issues", clean_owner: "macbat-compiler", mechanism_disposition: "Generate from declaration", witness_requirement: LegacyWitnessRequirement::Planned("variant addition compile failure/mutant"), gates: &[GateId::G1, GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-048", law: "Repo facts, dependency roles, proof obligations, and mutations have one normalized fact plane", legacy_evidence: "issues #207/#211/#213", clean_owner: "testpak::repo", mechanism_disposition: "Implement cleanly", witness_requirement: LegacyWitnessRequirement::Planned("duplicate/omitted fact fixtures"), gates: &[GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-049", law: "Proof inventories require hostile semantic closure, rule qualification, and freshness", legacy_evidence: "issue #197", clean_owner: "testpak::gauntlet", mechanism_disposition: "Keep and strengthen", witness_requirement: LegacyWitnessRequirement::Planned("planted self-blessing/omission cases"), gates: &[GateId::G3, GateId::G9], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-050", law: "Per-entity lane heads, clocks, compare-and-set state, predecessor links, and branch queries remain lane-isolated while unfiltered reads preserve the all-lane timeline", legacy_evidence: "lane branch and CAS invariants", clean_owner: "batpak::event", mechanism_disposition: "Preserve law, redesign representation", witness_requirement: LegacyWitnessRequirement::Planned("deterministic schedule + cold-start lane reconstruction"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-051", law: "An append durability/visibility gate timeout reports the unmet wait guarantee without pretending the already-committed event was rolled back", legacy_evidence: "frontier append-gate invariant", clean_owner: "batpak::store", mechanism_disposition: "Preserve exact outcome taxonomy", witness_requirement: LegacyWitnessRequirement::Planned("timeout with committed/queryable event fixture"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-052", law: "Open typestate implies a live writer; sync/drop failures surface honestly; read-only open never mints or appends authority/lifecycle state", legacy_evidence: "store lifecycle and open-report invariants", clean_owner: "batpak::store", mechanism_disposition: "Reimplement cleanly", witness_requirement: LegacyWitnessRequirement::Planned("writer-start failure, close failure, read-only no-side-effect fixtures"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-053", law: "Every persisted format/version pair has one canonical open or typed refusal; corrupt regenerable caches may rebuild while damaged authority fails closed", legacy_evidence: "compatibility matrix and future-version invariants", clean_owner: "batpak::compatibility", mechanism_disposition: "Replace matrix format, retain law", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::CanonicalOrTypedRefusal, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-054", law: "Cross-journal or cross-directory consistency is product/runtime composition, never an implicit single-journal guarantee", legacy_evidence: "cross-directory invariant", clean_owner: "syncbat::runtime", mechanism_disposition: "Keep boundary explicit", witness_requirement: LegacyWitnessRequirement::Planned("two-journal failure/interleaving model"), gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-055", law: "Supplying an injected clock makes ambient wall/monotonic time unreachable through open, append, sync, close, and runtime transitions", legacy_evidence: "injected-clock invariant", clean_owner: "batpak::time", mechanism_disposition: "Preserve and strengthen with no_std profile", witness_requirement: LegacyWitnessRequirement::Planned("trapping ambient-clock adapter + deterministic trace"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-056", law: "Visibility publication occurs only after every active index/tile view for the sequence range is populated", legacy_evidence: "multi-view publication invariant", clean_owner: "batpak::store", mechanism_disposition: "Generalize beyond legacy indexes", witness_requirement: LegacyWitnessRequirement::Planned("concurrent reader + planted omitted-view mutant"), gates: &[GateId::G2, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-057", law: "Group-commit admission requires stable item idempotency so replay cannot duplicate a partially acknowledged group", legacy_evidence: "group-commit idempotency invariant", clean_owner: "batpak::store", mechanism_disposition: "Preserve semantics", witness_requirement: LegacyWitnessRequirement::Planned("missing-key refusal + replay/original-receipt test"), gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-058", law: "Dropping an unsubmitted output/effect buffer publishes nothing; only explicit submit/commit crosses the durable boundary", legacy_evidence: "outbox drop-safety invariant", clean_owner: "syncbat::runtime", mechanism_disposition: "Generalize into EffectBatch", witness_requirement: LegacyWitnessRequirement::Planned("drop-without-submit and destructor-order fixtures"), gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-059", law: "Receipts are constructed only by the owning gate/runtime; unknown operations do not fabricate receipts; receipt-sink failure cannot report success", legacy_evidence: "receipt sealing and SyncBat receipt invariants", clean_owner: "batpak::receipt", mechanism_disposition: "Preserve, unify receipt constructors", witness_requirement: LegacyWitnessRequirement::Planned("forged-constructor, unknown-call, rejecting-sink fixtures"), gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-060", law: "Subscription sessions have explicit open/receive/close/overrun terminals and never fabricate delivery after producer closure", legacy_evidence: "subscription state-machine invariant", clean_owner: "syncbat::runtime", mechanism_disposition: "Reimplement over bounded push/durable pull", witness_requirement: LegacyWitnessRequirement::Planned("state-machine model + disconnect/overrun corpus"), gates: &[GateId::G6, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-061", law: "Required capabilities are checked before program/handler execution and concrete observed effects remain a subset of declaration, world imports, instance grants, and budget", legacy_evidence: "SyncBat capability/effect-row invariants", clean_owner: "syncbat::bvisor", mechanism_disposition: "Preserve, compile from contracts", witness_requirement: LegacyWitnessRequirement::Planned("denial-before-execution + undeclared-effect mutants"), gates: &[GateId::G5, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-062", law: "Durable runtime registration/composition state folds in journal order, rejects malformed/conflicting transitions, and rebuilds identically after reopen", legacy_evidence: "SyncBat register-catalog invariant", clean_owner: "syncbat::world", mechanism_disposition: "Supersede catalog with WorldImage/process lifecycle facts", witness_requirement: LegacyWitnessRequirement::Planned("full/reopen equivalence + conflicting transition fixture"), gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-063", law: "Public traversal and transport terminals expose domain-neutral substrate metadata, never downstream workflow entities or decoded application semantics", legacy_evidence: "substrate traversal invariant", clean_owner: "batpak::navigation", mechanism_disposition: "Preserve at generated interface boundary", witness_requirement: LegacyWitnessRequirement::Planned("API surface scan + hostile schema fixture"), gates: &[GateId::G2, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-064", law: "Public wire, ID, event, cursor, and receipt values round-trip every valid case, reject malformed bytes without partial success, and enforce exact declared lengths", legacy_evidence: "wire totality and payload-length invariants", clean_owner: "testpak::oracle", mechanism_disposition: "Preserve as shared conformance law", witness_requirement: LegacyWitnessRequirement::Planned("generated round-trip + truncation/overlength corpus"), gates: &[GateId::G2, GateId::G7], compatibility_disposition: CompatibilityDisposition::FrozenCanonicalIdentity, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-065", law: "Fault injection, poison levers, allocator faults, and dangerous frontier mutation are absent from default production profiles", legacy_evidence: "dangerous-hook invariants", clean_owner: "testpak::repo", mechanism_disposition: "Preserve profile containment", witness_requirement: LegacyWitnessRequirement::Planned("package/API scan under default and test profiles"), gates: &[GateId::G0, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::Never, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-066", law: "Platform adapters may emit evidence and enforce mechanisms but cannot define durability, replay, visibility, admission, deadline, or proof meaning: a relative inactivity timeout never substitutes for an absolute monotonic deadline, the lowest mechanism able to extend work enforces the remaining absolute deadline, and a retry never resets the overall deadline", legacy_evidence: "platform-evidence invariant", clean_owner: "batpak::port", mechanism_disposition: "Strengthen through semantic profiles", witness_requirement: LegacyWitnessRequirement::Planned("cross-adapter semantic trace equivalence"), gates: &[GateId::G2, GateId::G5, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-067", law: "Visible journal history is a dense single-writer linearization: no gap below the visible high-water, monotonic rereads, convergent readers, and no return-order inversion", legacy_evidence: "single-writer linearizability invariant", clean_owner: "batpak::store", mechanism_disposition: "Preserve and prove independently", witness_requirement: LegacyWitnessRequirement::Planned("seeded concurrent operation model + pure history checker"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-068", law: "Cache prefetch, acceleration, and retained-window behavior is discoverable through an explicit capability or configuration surface; no hidden cache policy changes semantics", legacy_evidence: "cache-capability invariant", clean_owner: "batpak::tile", mechanism_disposition: "Preserve law, redesign surface", witness_requirement: LegacyWitnessRequirement::Planned("capability discovery + disabled/enabled trace equivalence"), gates: &[GateId::G2, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-069", law: "The default clock adapter produces positive advancing wall observations, while an injected clock owns every observation and makes ambient time unreachable", legacy_evidence: "live-clock and injected-clock invariants", clean_owner: "batpak::time", mechanism_disposition: "Preserve as two explicit adapter contracts", witness_requirement: LegacyWitnessRequirement::Planned("live-adapter progression + trapping injected adapter"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-070", law: "Applied progress is the minimum reflected frontier across every required registered projection; one lagging projection prevents an overclaimed applied frontier", legacy_evidence: "applied-frontier invariant", clean_owner: "batpak::frontier", mechanism_disposition: "Preserve semantics with repaired time/order types", witness_requirement: LegacyWitnessRequirement::Planned("two-projection lag model + zero-projection bootstrap"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-071", law: "After reopen, the durable frontier honestly covers every visible recovered event without claiming which unacknowledged in-flight events had to survive", legacy_evidence: "recovered-durable-frontier invariant", clean_owner: "batpak::frontier", mechanism_disposition: "Preserve", witness_requirement: LegacyWitnessRequirement::Planned("honest/lying durability fault matrix + recovered-prefix oracle"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-072", law: "Frontier and checkpoint waits succeed only after observing the target on the same state transition that wakes them; spurious wakeups never satisfy progress", legacy_evidence: "frontier-wait invariant", clean_owner: "batpak::frontier", mechanism_disposition: "Preserve independent of synchronization mechanism", witness_requirement: LegacyWitnessRequirement::Planned("deterministic spurious-wakeup schedule + threshold model"), gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-073", law: "HLC causal merge remains a bounded commutative, associative, idempotent join with an explicit bottom; it never substitutes for commit or stream order", legacy_evidence: "HLC semilattice invariant and issue #208", clean_owner: "batpak::time", mechanism_disposition: "Preserve algebra, repair names and uses", witness_requirement: LegacyWitnessRequirement::Planned("independent algebra/property model"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-074", law: "Import interrupted at any durability boundary is safely retryable through stable import identity and cannot duplicate already-applied source events", legacy_evidence: "import crash-idempotency invariant", clean_owner: "batpak::lifecycle", mechanism_disposition: "Preserve", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-075", law: "Same-journal import freezes its source visible ceiling before appending and cannot ingest its own newly created output", legacy_evidence: "import no-runaway invariant", clean_owner: "batpak::lifecycle", mechanism_disposition: "Preserve", witness_requirement: LegacyWitnessRequirement::Planned("tiny-page/rotation self-import fixture"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-076", law: "Compiler-generated integer narrowing is preceded by an explicit bound check and produces a source diagnostic instead of truncation or panic", legacy_evidence: "macro bounded-cast invariant", clean_owner: "macbat-compiler", mechanism_disposition: "Generalize across compiler lowerings", witness_requirement: LegacyWitnessRequirement::Planned("boundary compile-fail corpus + narrowing mutants"), gates: &[GateId::G1], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-077", law: "Caller position hints may provide only contract-authorized branch hints; writer-owned commit point, HLC, stream position, and sequence remain authoritative and survive every qualified representation", legacy_evidence: "position-hint invariant", clean_owner: "batpak::event", mechanism_disposition: "Preserve with repaired position taxonomy", witness_requirement: LegacyWitnessRequirement::Planned("live/reopen/cache/full-rebuild equivalence"), gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-078", law: "Prepared or cached batch staging is an optimization only; it must commit, recover, publish, and receipt identically to fresh construction", legacy_evidence: "prepared-batch equivalence invariant", clean_owner: "batpak::store", mechanism_disposition: "Preserve", witness_requirement: LegacyWitnessRequirement::Planned("fresh/prepared differential under crash and reopen"), gates: &[GateId::G2, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-079", law: "Any two profiles or representations claiming semantic equivalence produce identical visible observables at one frozen cut; disagreement is a hard finding, never a tolerated optimization delta", legacy_evidence: "semantic-diff invariant", clean_owner: "testpak::oracle", mechanism_disposition: "Strengthen across native and browser profiles", witness_requirement: LegacyWitnessRequirement::Planned("seeded cross-profile semantic differential"), gates: &[GateId::G3, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::Never, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-080", law: "The public store/runtime surface remains sync-first with no hidden executor; async and browser hosts own suspension and resume outside the semantic API", legacy_evidence: "sync-only and no-runtime invariants", clean_owner: "syncbat::port", mechanism_disposition: "Preserve, expose explicit adapters only", witness_requirement: LegacyWitnessRequirement::Planned("dependency scan + native/browser trace parity"), gates: &[GateId::G0, GateId::G5, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::Never, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-081", law: "Secret-authority deletion is durable and anti-rollback: a shred is acknowledged only after the owning key backend durably destroys the required material; secret authority binds StoreId AuthorityGeneration KeyGeneration key-scope and shred-transition identity; no foreign stale or pre-shred keyset restores readability to a newer store generation; Shredded Unavailable and KeysetMissing stay distinct; snapshot fork WorldImage artifact bundles and ordinary receipts carry no raw key material by default; an external key backend preserves the same deletion durability generation and anti-rollback semantics", legacy_evidence: "keyscope and delivery tests; key-backend durability and anti-rollback issues #194/#195", clean_owner: "batpak::secret", mechanism_disposition: "Preserve law; new key representation and backend allowed", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-082", law: "Compaction namespace publication is crash-atomic and accepted only when the pending marker, store metadata commit record, and authority image agree on the published generation", legacy_evidence: "issue #189 compaction namespace commit invariant", clean_owner: "batpak::compaction", mechanism_disposition: "Reimplement", witness_requirement: LegacyWitnessRequirement::Planned("marker/meta/image agreement crash matrix"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-083", law: "Idempotency-authority export and restore are fail-closed, lineage-bound, generation-bound, and publish a fresh destination AuthorityImageId through the destination authority chain", legacy_evidence: "GAUNT-IDEMPOTENCY-AUTHORITY #189 export/restore invariant", clean_owner: "batpak::store", mechanism_disposition: "Preserve authority, new representation allowed", witness_requirement: LegacyWitnessRequirement::Planned("corrupt/future-version/stale/foreign/diverged/over-coverage refusal corpus"), gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-084", law: "Public and user write surfaces cannot mint internal lifecycle, effect, transaction-envelope, authority, or recovery-control event classes", legacy_evidence: "ADR-0033 reserved-kind write-surface family", clean_owner: "batpak::event", mechanism_disposition: "Validate authority before frame construction or durable staging", witness_requirement: LegacyWitnessRequirement::Planned("append/batch/import/dynamic-kind/submit/try-submit reserved-class rejection fixtures"), gates: &[GateId::G1, GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-085", law: "Signed-history compaction changes the physical segment set only through a proof-preserving rewrite of the same ordered logical commitments or an authorized retention transition binding prior and resulting roots, retained and removed commitment sets, retention policy, and replacement seals; inputs are not retired before the transition and replacement evidence are durably recoverable under an old-or-new protocol", legacy_evidence: "issue #193 GAUNT-SEGMENT-SEALS", clean_owner: "batpak::store", mechanism_disposition: "Reimplement cleanly", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G2, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-086", law: "Projection replay classifies a wrong event kind as a normal filter while a matched kind with decode or apply failure is a typed terminal; full replay, incremental replay, cache rebuild, and checkpoint restore agree on the first failing event and failure class, and no cache or checkpoint downgrades the failure to a miss or a silent skip", legacy_evidence: "issue #184 projection fallible replay", clean_owner: "batpak::projection", mechanism_disposition: "Reimplement cleanly", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-087", law: "An injected non-host storage backend makes ambient host filesystem access unreachable, including diagnostics and evidence collection; no probe, fallback, or evidence path touches the host filesystem when the storage port is virtual", legacy_evidence: "issue #171 MemFs ambient filesystem", clean_owner: "batpak::storage_port", mechanism_disposition: "Reimplement cleanly", witness_requirement: LegacyWitnessRequirement::CanonicalProofRows, gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
];

/// The one lawful LEG lifetime derivation (5.5C1a), executed in Rust since
/// the 5.5E2 bake. A LEG row names a clean owner and gates but no typed
/// successor GuaranteeRef, so an active gate-closed obligation is `UntilGate`
/// (`UntilSuccessor` requires a resolved typed successor, which the LEG
/// schema does not provide); a closed row is retained evidence; a
/// compatibility-bound row cannot retire before its window.
pub const fn legacy_lifetime(
    status: ObligationStatus,
    deletion: DeletionCondition,
) -> crate::guarantees::GuaranteeLifetime {
    use crate::guarantees::GuaranteeLifetime;
    match (status, deletion) {
        (ObligationStatus::Closed, _) => GuaranteeLifetime::ClosedEvidence,
        (ObligationStatus::Active, DeletionCondition::OnCompatibilityWindowExpiry) => {
            GuaranteeLifetime::UntilCompatibilityExpiry
        }
        (ObligationStatus::Active, DeletionCondition::Never)
        | (ObligationStatus::Active, DeletionCondition::OnSuccessorGateClosure) => {
            GuaranteeLifetime::UntilGate
        }
    }
}
