//! Frozen coverage of the live legacy invariant catalog.

pub const LEGACY_SOURCE_COMMIT: &str = "6c4a46f8994528f0aeddfeb192868d084a73d1d8";
pub const EXPECTED_COVERAGE_ROWS: usize = 107;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CoverageDisposition {
    Preserve,
    Supersede,
    Demote,
    Kill,
    Requalify,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LegacyInvariantCoverage {
    pub legacy_id: &'static str,
    pub disposition: CoverageDisposition,
    pub successor: &'static str,
    pub rationale: &'static str,
}

pub const COVERAGE: &[LegacyInvariantCoverage] = &[
    LegacyInvariantCoverage { legacy_id: "INV-ALLOW-IS-DESIGN", disposition: CoverageDisposition::Supersede, successor: "BP-AGENT-GUIDE and BP-GAUNTLET-1", rationale: "Keep the zero-silencer law; replace the legacy checker implementation." },
    LegacyInvariantCoverage { legacy_id: "INV-BATCH-ATOMIC-VISIBILITY", disposition: CoverageDisposition::Preserve, successor: "LEG-003", rationale: "Atomic visibility is durable journal law." },
    LegacyInvariantCoverage { legacy_id: "INV-BATCH-CRASH-RECOVERY", disposition: CoverageDisposition::Preserve, successor: "LEG-004", rationale: "Incomplete batch recovery remains mandatory." },
    LegacyInvariantCoverage { legacy_id: "INV-BIDIRECTIONAL-SUBSTRATE-LANE", disposition: CoverageDisposition::Preserve, successor: "LEG-063", rationale: "Every committing boundary retains bounded domain-neutral replay access." },
    LegacyInvariantCoverage { legacy_id: "INV-BUILD-FAIL-FAST", disposition: CoverageDisposition::Supersede, successor: "BP-BOOTSTRAP-1 and TestPak structural gates", rationale: "Fail-fast construction remains; the legacy build.rs mechanism does not." },
    LegacyInvariantCoverage { legacy_id: "INV-CACHE-CAPABILITIES-EXPLICIT", disposition: CoverageDisposition::Preserve, successor: "LEG-068", rationale: "Acceleration policy remains discoverable and explicit." },
    LegacyInvariantCoverage { legacy_id: "INV-CANONICAL-CONTAINER-CI", disposition: CoverageDisposition::Requalify, successor: "BP-GAUNTLET-1 target profiles", rationale: "Canonical environments are qualified per target rather than universal Linux product law." },
    LegacyInvariantCoverage { legacy_id: "INV-CANONICAL-PATCH-STABILITY", disposition: CoverageDisposition::Preserve, successor: "LEG-040", rationale: "Versioned canonical evidence bytes and goldens remain stable." },
    LegacyInvariantCoverage { legacy_id: "INV-CHAOS-LINUX-ONLY", disposition: CoverageDisposition::Requalify, successor: "BP-GAUNTLET-1 target-qualified durability evidence", rationale: "Linux chaos evidence remains useful but cannot claim cross-target proof." },
    LegacyInvariantCoverage { legacy_id: "INV-CHECKPOINT-V2-INTERNED", disposition: CoverageDisposition::Supersede, successor: "LEG-017 and LEG-018", rationale: "Derived-cache compactness is retained; exact v2 interner layout is legacy mechanism." },
    LegacyInvariantCoverage { legacy_id: "INV-CLOCK-NOW-US-LIVE", disposition: CoverageDisposition::Preserve, successor: "LEG-069", rationale: "The default clock adapter must be live and typed." },
    LegacyInvariantCoverage { legacy_id: "INV-COLD-START-ARTIFACTS", disposition: CoverageDisposition::Preserve, successor: "LEG-017, LEG-052, and LEG-053", rationale: "Open/reopen artifacts and authority distinctions remain explicit." },
    LegacyInvariantCoverage { legacy_id: "INV-COLUMNAR-REPLACES-DASHMAP", disposition: CoverageDisposition::Supersede, successor: "LEG-018 and DEC-033", rationale: "The SIDX successor earns column tiles; the old overlay topology is not frozen." },
    LegacyInvariantCoverage { legacy_id: "INV-COMPLEXITY-EXPONENT-BOUNDED", disposition: CoverageDisposition::Preserve, successor: "LEG-020", rationale: "Asymptotic and work-count gates remain anti-vacuous." },
    LegacyInvariantCoverage { legacy_id: "INV-CONCURRENCY-SCHEDULE-PROOF", disposition: CoverageDisposition::Preserve, successor: "BP-TESTPAK-1 deterministic schedule plane", rationale: "Schedule exploration remains required across idempotency, CAS, supervision, and compaction." },
    LegacyInvariantCoverage { legacy_id: "INV-CONTEXT-VIEWS-DERIVED-FROM-HISTORY", disposition: CoverageDisposition::Preserve, successor: "LEG-017 and LEG-026", rationale: "Views remain disposable derivations of accepted history." },
    LegacyInvariantCoverage { legacy_id: "INV-COORDINATE-IS-LOGICAL-STREAM", disposition: CoverageDisposition::Preserve, successor: "LEG-021", rationale: "Coordinate keeps its logical-stream meaning." },
    LegacyInvariantCoverage { legacy_id: "INV-CROSS-DIRECTORY-CONSISTENCY-PRODUCT-OWNED", disposition: CoverageDisposition::Preserve, successor: "LEG-054", rationale: "Cross-journal consistency remains runtime/product composition." },
    LegacyInvariantCoverage { legacy_id: "INV-CRYPTO-SHRED-SCOPE-DESTROYS-PLAINTEXT", disposition: CoverageDisposition::Preserve, successor: "LEG-015", rationale: "Erasure destroys plaintext authority without rewriting history." },
    LegacyInvariantCoverage { legacy_id: "INV-DANGEROUS-TEST-HOOKS-NONDEFAULT", disposition: CoverageDisposition::Preserve, successor: "LEG-065", rationale: "Dangerous levers remain absent from production profiles." },
    LegacyInvariantCoverage { legacy_id: "INV-DELIVERY-AT-LEAST-ONCE-WITNESS", disposition: CoverageDisposition::Preserve, successor: "LEG-034", rationale: "Checkpoint-backed at-least-once evidence remains explicit." },
    LegacyInvariantCoverage { legacy_id: "INV-DEPENDENCY-DIRECTION", disposition: CoverageDisposition::Preserve, successor: "BP-REPOSITORY-PACKAGES-1 and spec/architecture.rs", rationale: "The graph remains acyclic and direction-checked." },
    LegacyInvariantCoverage { legacy_id: "INV-DOCS-CATALOG-VIEW-CURRENT", disposition: CoverageDisposition::Supersede, successor: "BP-STATUS-1 plus typed spec facts and audit.py", rationale: "Generated views remain current, but the old catalog implementation is replaced." },
    LegacyInvariantCoverage { legacy_id: "INV-DST-CORPUS-CURRENCY", disposition: CoverageDisposition::Supersede, successor: "BP-GAUNTLET-1 corpus and receipt freshness", rationale: "Corpus replay currency survives under TestPak receipts." },
    LegacyInvariantCoverage { legacy_id: "INV-DST-RECOVERY-LEGAL", disposition: CoverageDisposition::Preserve, successor: "LEG-010", rationale: "Recovery legality remains prefix, rollback, or canonical refusal." },
    LegacyInvariantCoverage { legacy_id: "INV-EVENT-PAYLOAD-DECODE-BACKCOMPAT", disposition: CoverageDisposition::Preserve, successor: "LEG-002", rationale: "Historical bytes remain readable through explicit migration." },
    LegacyInvariantCoverage { legacy_id: "INV-EVENTKIND-PARSE-ROUNDTRIP", disposition: CoverageDisposition::Preserve, successor: "LEG-024", rationale: "Event-kind parsing remains total and collision-checked." },
    LegacyInvariantCoverage { legacy_id: "INV-EXAMPLES-OBSERVABLE-OUTPUT", disposition: CoverageDisposition::Demote, successor: "BP-AGENT-GUIDE example observability rule", rationale: "Observable examples remain desirable; the exact stdout macro policy is not semantic law." },
    LegacyInvariantCoverage { legacy_id: "INV-EXTERNAL-REPLAY-NO-SIDECAR-TRUTH", disposition: CoverageDisposition::Preserve, successor: "LEG-017 and LEG-019", rationale: "Caches may accelerate but never authenticate replay." },
    LegacyInvariantCoverage { legacy_id: "INV-FAULT-INJECT-GATED", disposition: CoverageDisposition::Preserve, successor: "LEG-065", rationale: "Fault controls remain test-profile only." },
    LegacyInvariantCoverage { legacy_id: "INV-FENCE-CANCELLED-STAYS-HIDDEN", disposition: CoverageDisposition::Preserve, successor: "LEG-006", rationale: "Cancelled visibility remains durable hidden authority." },
    LegacyInvariantCoverage { legacy_id: "INV-FORK-CRASH-ATOMIC", disposition: CoverageDisposition::Preserve, successor: "LEG-011", rationale: "Fork publication remains crash-atomic." },
    LegacyInvariantCoverage { legacy_id: "INV-FORK-HOSTILE-FS-REFUSAL", disposition: CoverageDisposition::Preserve, successor: "LEG-011", rationale: "Hostile destinations cannot publish a half-fork." },
    LegacyInvariantCoverage { legacy_id: "INV-FORK-ISOLATION", disposition: CoverageDisposition::Preserve, successor: "LEG-011", rationale: "Mutable authorities never alias across fork." },
    LegacyInvariantCoverage { legacy_id: "INV-FRONTIER-APPEND-GATE-HONORED", disposition: CoverageDisposition::Preserve, successor: "LEG-051", rationale: "Wait timeout reports an unmet gate, not rollback." },
    LegacyInvariantCoverage { legacy_id: "INV-FRONTIER-APPLIED-MIN", disposition: CoverageDisposition::Preserve, successor: "LEG-070", rationale: "Applied progress cannot outrun a lagging required projection." },
    LegacyInvariantCoverage { legacy_id: "INV-FRONTIER-DURABLE-COVERS-RECOVERED", disposition: CoverageDisposition::Preserve, successor: "LEG-071", rationale: "Recovered durability claims remain honest." },
    LegacyInvariantCoverage { legacy_id: "INV-FRONTIER-FAULT-ORDINALS", disposition: CoverageDisposition::Supersede, successor: "G2 fault schedule under BP-GAUNTLET-1", rationale: "Fault points remain ordered and observable; exact legacy names are not frozen." },
    LegacyInvariantCoverage { legacy_id: "INV-FRONTIER-MONOTONIC", disposition: CoverageDisposition::Preserve, successor: "LEG-005", rationale: "Every frontier remains monotonic." },
    LegacyInvariantCoverage { legacy_id: "INV-FRONTIER-OPEN-MONOTONIC", disposition: CoverageDisposition::Preserve, successor: "LEG-005 and LEG-052", rationale: "Open progress cannot move behind recovered or closed history." },
    LegacyInvariantCoverage { legacy_id: "INV-FRONTIER-ORDERING", disposition: CoverageDisposition::Preserve, successor: "LEG-005", rationale: "Accepted, written, durable, visible, applied, and emitted ordering remains explicit." },
    LegacyInvariantCoverage { legacy_id: "INV-FRONTIER-TORN-FREE", disposition: CoverageDisposition::Preserve, successor: "LEG-005 and LEG-056", rationale: "Published frontier views cannot expose torn multi-field state." },
    LegacyInvariantCoverage { legacy_id: "INV-FRONTIER-WAIT-MONOTONIC", disposition: CoverageDisposition::Preserve, successor: "LEG-072", rationale: "Spurious wakeups cannot satisfy progress." },
    LegacyInvariantCoverage { legacy_id: "INV-GAUNTLET-FOLD-FUSION", disposition: CoverageDisposition::Preserve, successor: "LEG-031 and LEG-048", rationale: "Proof-plane fusion must equal separate passes." },
    LegacyInvariantCoverage { legacy_id: "INV-GENERATED-WITNESS-PIN", disposition: CoverageDisposition::Preserve, successor: "LEG-024 and LEG-046", rationale: "Generated collision and ownership witnesses remain bound to declarations." },
    LegacyInvariantCoverage { legacy_id: "INV-GROUP-COMMIT-IDEMPOTENCY", disposition: CoverageDisposition::Preserve, successor: "LEG-057", rationale: "Grouped admission requires stable idempotency." },
    LegacyInvariantCoverage { legacy_id: "INV-HASH-CHAIN-INTEGRITY", disposition: CoverageDisposition::Preserve, successor: "LEG-023", rationale: "Reorder, deletion, and mutation remain detectable." },
    LegacyInvariantCoverage { legacy_id: "INV-HLC-JOIN-SEMILATTICE", disposition: CoverageDisposition::Preserve, successor: "LEG-073", rationale: "The causal HLC algebra remains lawful and separate from commit order." },
    LegacyInvariantCoverage { legacy_id: "INV-IDEMPOTENCY-AUTHORITY-ATOMIC-COMPACTION", disposition: CoverageDisposition::Preserve, successor: "LEG-007 and LEG-009", rationale: "Authority and namespace publication remain one recoverable transition." },
    LegacyInvariantCoverage { legacy_id: "INV-IDEMPOTENCY-DURABLE-WINDOW", disposition: CoverageDisposition::Preserve, successor: "LEG-007", rationale: "Within-window retries remain durable no-ops." },
    LegacyInvariantCoverage { legacy_id: "INV-IMPORT-CONTENT-ISOMORPHISM", disposition: CoverageDisposition::Preserve, successor: "LEG-013", rationale: "Import preserves content/provenance while assigning destination identity." },
    LegacyInvariantCoverage { legacy_id: "INV-IMPORT-CRASH-IDEMPOTENT", disposition: CoverageDisposition::Preserve, successor: "LEG-074", rationale: "Interrupted import remains safely retryable." },
    LegacyInvariantCoverage { legacy_id: "INV-IMPORT-NO-RUNAWAY", disposition: CoverageDisposition::Preserve, successor: "LEG-075", rationale: "Same-journal import freezes its source ceiling." },
    LegacyInvariantCoverage { legacy_id: "INV-INDEX-FILTER-COMPOSES", disposition: CoverageDisposition::Preserve, successor: "LEG-017 and LEG-079", rationale: "Optimized filters must equal authoritative scan semantics." },
    LegacyInvariantCoverage { legacy_id: "INV-INJECTED-CLOCK-OWNS-TIMEKEEPING", disposition: CoverageDisposition::Preserve, successor: "LEG-055 and LEG-069", rationale: "Injected time excludes ambient access." },
    LegacyInvariantCoverage { legacy_id: "INV-INVARIANT-WITNESS-TEST", disposition: CoverageDisposition::Preserve, successor: "BP-GAUNTLET-1 audited denominator", rationale: "Named witnesses must resolve to executable proof." },
    LegacyInvariantCoverage { legacy_id: "INV-JOURNAL-SINGLE-LIVE-OWNER", disposition: CoverageDisposition::Preserve, successor: "LEG-001", rationale: "One journal has one live owner." },
    LegacyInvariantCoverage { legacy_id: "INV-JOURNAL-WRITER-SERIALIZES-COMMITS", disposition: CoverageDisposition::Preserve, successor: "LEG-001", rationale: "All commits share one writer-owned order." },
    LegacyInvariantCoverage { legacy_id: "INV-LANE-BRANCH-ISOLATION", disposition: CoverageDisposition::Preserve, successor: "LEG-050", rationale: "Lane heads and CAS state remain isolated." },
    LegacyInvariantCoverage { legacy_id: "INV-LINEARIZABILITY-SINGLE-WRITER", disposition: CoverageDisposition::Preserve, successor: "LEG-067", rationale: "Visible history remains a dense single-writer linearization." },
    LegacyInvariantCoverage { legacy_id: "INV-LITERAL-REGEX-UNWRAP-SAFE", disposition: CoverageDisposition::Kill, successor: "No general exception in final code doctrine", rationale: "The legacy tool-specific unwrap exception does not become target architecture." },
    LegacyInvariantCoverage { legacy_id: "INV-MACRO-BOUNDED-CAST", disposition: CoverageDisposition::Preserve, successor: "LEG-076", rationale: "Compiler narrowing remains checked and diagnostic." },
    LegacyInvariantCoverage { legacy_id: "INV-MMAP-SEALED-READS", disposition: CoverageDisposition::Demote, successor: "BP-STORAGE-TILES-1 native adapter option", rationale: "Memory mapping remains an optional mechanism subject to workload proof." },
    LegacyInvariantCoverage { legacy_id: "INV-MULTI-VIEW-PUBLISH-AFTER-VIEW-SYNC", disposition: CoverageDisposition::Preserve, successor: "LEG-056", rationale: "Visibility follows every active view update." },
    LegacyInvariantCoverage { legacy_id: "INV-NATIVE-DELETE-IDEMPOTENT", disposition: CoverageDisposition::Supersede, successor: "BP-STORAGE-TILES-1 cache/artifact deletion conformance", rationale: "Idempotent deletion survives if the successor exposes the operation; NativeCache does not." },
    LegacyInvariantCoverage { legacy_id: "INV-NETBAT-BOUNDARY-THIN", disposition: CoverageDisposition::Preserve, successor: "LEG-045", rationale: "Transport remains bounded and domain-thin." },
    LegacyInvariantCoverage { legacy_id: "INV-NETBAT-LINE-PROTOCOL-STABLE", disposition: CoverageDisposition::Demote, successor: "BP-NETBAT-1 compatibility inventory at G7", rationale: "NETBAT/1 is legacy compatibility evidence, not the native target protocol." },
    LegacyInvariantCoverage { legacy_id: "INV-NO-DEAD-CODE-SILENCERS", disposition: CoverageDisposition::Preserve, successor: "BP-AGENT-GUIDE and BP-GAUNTLET-1", rationale: "Dead code is deleted, gated, or re-owned rather than silenced." },
    LegacyInvariantCoverage { legacy_id: "INV-NO-TOKIO-PROD", disposition: CoverageDisposition::Preserve, successor: "LEG-080", rationale: "No hidden executor enters the semantic runtime." },
    LegacyInvariantCoverage { legacy_id: "INV-OBSERVABILITY-FAILURE-PATHS", disposition: CoverageDisposition::Preserve, successor: "BP-RECEIPTS-1", rationale: "Success, degraded, causal, and failure paths remain distinguishable." },
    LegacyInvariantCoverage { legacy_id: "INV-ONDISK-FORWARD-COMPAT-CANONICAL", disposition: CoverageDisposition::Preserve, successor: "LEG-053", rationale: "Every version pair has one canonical success or refusal." },
    LegacyInvariantCoverage { legacy_id: "INV-OPEN-REPORT-RECEIPT", disposition: CoverageDisposition::Preserve, successor: "LEG-052 and LEG-059", rationale: "Open/recovery behavior remains receipted and read-only opens remain side-effect free." },
    LegacyInvariantCoverage { legacy_id: "INV-OUTBOX-DROP-SAFETY", disposition: CoverageDisposition::Preserve, successor: "LEG-058", rationale: "Unsubmitted buffers publish nothing." },
    LegacyInvariantCoverage { legacy_id: "INV-OUTCOME-FUNCTOR-COMPOSITION", disposition: CoverageDisposition::Demote, successor: "Reference-law corpus if equivalent combinators are retained", rationale: "The algebra is useful evidence but does not force the legacy public combinator API." },
    LegacyInvariantCoverage { legacy_id: "INV-PAYLOAD-LENGTH-EXACT", disposition: CoverageDisposition::Preserve, successor: "LEG-064", rationale: "Encoded lengths remain exact and bounded before allocation." },
    LegacyInvariantCoverage { legacy_id: "INV-PAYLOAD-VERSION-NONZERO", disposition: CoverageDisposition::Supersede, successor: "LEG-002 and LEG-053 under EventFrameV2", rationale: "Typed/current and legacy frames remain distinguishable; exact sentinel layout is selected at G2." },
    LegacyInvariantCoverage { legacy_id: "INV-PER-LANE-FRONTIER", disposition: CoverageDisposition::Preserve, successor: "LEG-005", rationale: "One physical durability axis and lane-scoped logical progress remain separate." },
    LegacyInvariantCoverage { legacy_id: "INV-PERFORMANCE-GATES-ENFORCED", disposition: CoverageDisposition::Preserve, successor: "BP-COMMAND-PLANE-1 and BP-TESTPAK-1", rationale: "Hardware-sensitive gates remain explicit TestPak commands." },
    LegacyInvariantCoverage { legacy_id: "INV-PLATFORM-EVIDENCE-NOT-MEANING", disposition: CoverageDisposition::Preserve, successor: "LEG-066", rationale: "Adapters provide mechanism and evidence, never semantic law." },
    LegacyInvariantCoverage { legacy_id: "INV-POSITION-HINT-PERSISTENCE", disposition: CoverageDisposition::Preserve, successor: "LEG-077", rationale: "Hints cannot replace writer-owned positions and must survive qualified representations." },
    LegacyInvariantCoverage { legacy_id: "INV-PREPARED-BATCH-STAGING-EQUIVALENCE", disposition: CoverageDisposition::Preserve, successor: "LEG-078", rationale: "Prepared staging remains an optimization only." },
    LegacyInvariantCoverage { legacy_id: "INV-PROJECTION-FUSION-EQUIVALENCE", disposition: CoverageDisposition::Preserve, successor: "LEG-031", rationale: "Fused folds equal separate folds." },
    LegacyInvariantCoverage { legacy_id: "INV-PROJECTION-FUSION-EQUIVALENT", disposition: CoverageDisposition::Preserve, successor: "LEG-031 and LEG-079", rationale: "Runtime fused replay preserves per-projection filtering and frontiers." },
    LegacyInvariantCoverage { legacy_id: "INV-RECEIPT-SEALED", disposition: CoverageDisposition::Preserve, successor: "LEG-059", rationale: "Only the owning gate/runtime constructs receipts." },
    LegacyInvariantCoverage { legacy_id: "INV-RECOVERY-ORACLE-LEGAL", disposition: CoverageDisposition::Preserve, successor: "LEG-010 and LEG-071", rationale: "Crash recovery remains independently classified and deterministic." },
    LegacyInvariantCoverage { legacy_id: "INV-REPLAY-LANE-SELECTION", disposition: CoverageDisposition::Demote, successor: "LegacyMessagePack compatibility reader under LEG-002", rationale: "The old raw-MessagePack lane is evidence; native codec/layout selection supersedes it." },
    LegacyInvariantCoverage { legacy_id: "INV-SCHEMA-VERSION-ISOLATION", disposition: CoverageDisposition::Preserve, successor: "LEG-017 and LEG-028", rationale: "Derived state remains schema/version/generation isolated." },
    LegacyInvariantCoverage { legacy_id: "INV-SEMANTIC-DIFF-EQUIVALENCE", disposition: CoverageDisposition::Preserve, successor: "LEG-079", rationale: "Equivalent profiles must expose identical observables." },
    LegacyInvariantCoverage { legacy_id: "INV-SIDX-TIMESTAMP-US-APPROXIMATION", disposition: CoverageDisposition::Kill, successor: "Explicit time precision in the SIDX successor", rationale: "The millisecond approximation is legacy evidence, not target law." },
    LegacyInvariantCoverage { legacy_id: "INV-STORE-ERROR-TAXONOMY", disposition: CoverageDisposition::Preserve, successor: "LEG-047", rationale: "Failures remain structured and generated from owned declarations." },
    LegacyInvariantCoverage { legacy_id: "INV-STORE-ISOMORPHISM-LAWS", disposition: CoverageDisposition::Preserve, successor: "LEG-064 and LEG-079", rationale: "Durable identity seams retain round-trip/isomorphism proof." },
    LegacyInvariantCoverage { legacy_id: "INV-STORE-LIFECYCLE-HONESTY", disposition: CoverageDisposition::Preserve, successor: "LEG-052", rationale: "Writer and shutdown failures cannot report success." },
    LegacyInvariantCoverage { legacy_id: "INV-STORE-LINEAGE-IDENTITY", disposition: CoverageDisposition::Preserve, successor: "LEG-008", rationale: "Lineage is minted once and mutable authority binds stronger generation/history evidence." },
    LegacyInvariantCoverage { legacy_id: "INV-STORE-SYNC-ONLY", disposition: CoverageDisposition::Preserve, successor: "LEG-080", rationale: "The semantic store/runtime API remains synchronous." },
    LegacyInvariantCoverage { legacy_id: "INV-SUBSCRIPTION-STATE-MACHINE", disposition: CoverageDisposition::Preserve, successor: "LEG-060", rationale: "Subscription lifecycle and closed/overrun terminals remain explicit." },
    LegacyInvariantCoverage { legacy_id: "INV-SUBSTRATE-TRAVERSAL-DOMAIN-NEUTRAL", disposition: CoverageDisposition::Preserve, successor: "LEG-063", rationale: "Substrate traversal never leaks domain semantics." },
    LegacyInvariantCoverage { legacy_id: "INV-SYNCBAT-CAPABILITY-GRANT-ENFORCEMENT", disposition: CoverageDisposition::Preserve, successor: "LEG-061", rationale: "Capabilities are checked before execution." },
    LegacyInvariantCoverage { legacy_id: "INV-SYNCBAT-DISPATCH-RECEIPTS", disposition: CoverageDisposition::Preserve, successor: "LEG-059", rationale: "Resolved calls emit at most one terminal receipt; sink failure is fail-closed." },
    LegacyInvariantCoverage { legacy_id: "INV-SYNCBAT-EFFECT-ROW-ENFORCEMENT", disposition: CoverageDisposition::Preserve, successor: "LEG-036 and LEG-061", rationale: "Observed effects remain a subset of declaration and grants." },
    LegacyInvariantCoverage { legacy_id: "INV-SYNCBAT-REGISTER-CATALOG-DETERMINISTIC", disposition: CoverageDisposition::Preserve, successor: "LEG-062", rationale: "Runtime composition/lifecycle facts rebuild deterministically." },
    LegacyInvariantCoverage { legacy_id: "INV-TEST-PANIC-AS-ASSERTION", disposition: CoverageDisposition::Preserve, successor: "BP-AGENT-GUIDE and BP-TESTPAK-1", rationale: "Tests use explicit assertion semantics without lint suppression." },
    LegacyInvariantCoverage { legacy_id: "INV-TRACEABILITY-COMPLETE", disposition: CoverageDisposition::Preserve, successor: "BP-GAUNTLET-1 and BP-STATUS-1", rationale: "Every important law terminates in owned evidence and every artifact has a role." },
    LegacyInvariantCoverage { legacy_id: "INV-TYPELEVEL-COMBINATOR-LAWS", disposition: CoverageDisposition::Demote, successor: "Reference-law corpus if successor combinators exist", rationale: "The laws remain reusable evidence but do not force legacy API shape." },
    LegacyInvariantCoverage { legacy_id: "INV-TYPESTATE-OPEN-HAS-WRITER", disposition: CoverageDisposition::Preserve, successor: "LEG-052", rationale: "Open typestate cannot exist without the required writer mechanism." },
    LegacyInvariantCoverage { legacy_id: "INV-UNTRUSTED-MANIFEST-NO-AUTHORITY-ESCALATION", disposition: CoverageDisposition::Preserve, successor: "LEG-019", rationale: "Untrusted cache/manifest rows cannot become recovery authority." },
    LegacyInvariantCoverage { legacy_id: "INV-WIRE-ROUNDTRIP-TOTALITY", disposition: CoverageDisposition::Preserve, successor: "LEG-064", rationale: "Wire surfaces remain total on valid values and reject malformed bytes atomically." },
    LegacyInvariantCoverage { legacy_id: "INV-WORKSPACE-DAG-ACYCLIC", disposition: CoverageDisposition::Preserve, successor: "spec/architecture.rs, seedcheck.rs, and audit.py", rationale: "The workspace graph remains independently derived and acyclic." },
];
