//! Frozen clean-room legacy semantic obligation facts.

use crate::gates::GateId;

/// Whether a retained obligation still gates clean-room implementation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObligationStatus {
    /// Still gating: a clean successor must discharge it at its gate.
    Active,
    /// Discharged; retained as historical evidence and no longer gating.
    Closed,
}

/// The cross-version / cross-format compatibility burden an obligation carries.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CompatibilityDisposition {
    /// Pure semantic law with no durable-byte or wire compatibility burden.
    None,
    /// Must keep decoding older accepted bytes through explicit migration.
    ReadOlderAccepted,
    /// Every persisted format/version pair resolves to one canonical open or typed refusal.
    CanonicalOrTypedRefusal,
    /// Canonical identity, bytes, or goldens are frozen and versioned.
    FrozenCanonicalIdentity,
}

/// The condition under which the obligation may retire from active gating.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DeletionCondition {
    /// Permanent constitutional law; keeps gating regardless of implementation progress.
    Never,
    /// Dischargeable once the named clean successor closes at its gate.
    OnSuccessorGateClosure,
    /// Additionally bound: cannot retire until its declared compatibility window closes.
    OnCompatibilityWindowExpiry,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LegacyObligation {
    pub id: &'static str,
    pub law: &'static str,
    pub clean_owner: &'static str,
    pub gates: &'static [GateId],
    pub compatibility_disposition: CompatibilityDisposition,
    pub deletion_condition: DeletionCondition,
    pub active_or_closed_status: ObligationStatus,
}

pub const OBLIGATIONS: &[LegacyObligation] = &[
    LegacyObligation { id: "LEG-001", law: "One live writer and one physical commit order per journal", clean_owner: "batpak::store", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-002", law: "Accepted event bytes are immutable; shape evolves on read", clean_owner: "batpak::event", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::ReadOlderAccepted, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-003", law: "Batch append is atomically visible", clean_owner: "batpak::store", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-004", law: "Incomplete batch is discarded or canonically refused after crash/rotation", clean_owner: "batpak::store", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-005", law: "Physical durability and per-lane logical frontiers remain distinct", clean_owner: "batpak::frontier", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-006", law: "Visibility fences can leave durable events hidden and that state survives reopen/export", clean_owner: "batpak::visibility", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-007", law: "Durable idempotency returns original receipt after reopen within retention law", clean_owner: "batpak::store", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-008", law: "Store lineage and authority generation reject foreign mutable state", clean_owner: "batpak::store", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-009", law: "Compaction publication and namespace durability are separate from content writes", clean_owner: "batpak::compaction", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-010", law: "Recovery terminal is committed prefix, rollback, or typed refusal", clean_owner: "batpak::recovery", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-011", law: "Fork may share immutable sealed data but never mutable authorities", clean_owner: "batpak::lifecycle", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-012", law: "Snapshot binds exact source cut and evidence, not later frontier", clean_owner: "batpak::lifecycle", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-013", law: "Import preserves source content while assigning destination-local identity/order", clean_owner: "batpak::lifecycle", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-014", law: "Restore distinguishes missing cache, missing authority, lineage mismatch, and corruption", clean_owner: "batpak::recovery", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-015", law: "Crypto shredding destroys plaintext authority without rewriting accepted ciphertext/history", clean_owner: "batpak::secret", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-016", law: "Storage adapters satisfy one handle/transaction/crash conformance corpus", clean_owner: "batpak::storage_port", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-017", law: "Fast-start checkpoint/mmap/SIDX artifacts are derived and never source authority", clean_owner: "batpak::tile", gates: &[GateId::G2, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-018", law: "SIDX has explicit fixed layout and independent frame-scan fallback", clean_owner: "batpak::tile", gates: &[GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-019", law: "Derived cache cannot authenticate itself: SIDX and other unauthenticated derived material may accelerate locate or describe suspicion but cannot authenticate themselves, and an independently corroborated derived row proves only that exact row-to-authoritative-frame relationship while authenticating neither sibling rows nor table row count nor table ordering nor a claimed tail boundary nor middle or trailing completeness nor absence nor loss nor the authority of the table itself; unauthenticated derived material cannot prove safety and cannot prove loss, so a discrepancy may cause suspicion a derived-state rebuild a fallback to authoritative storage or a typed refusal where stronger evidence is required but never an authoritative proven-loss or proven-safety conclusion from derived material alone; there is no trusted-local SIDX authority, permissive compatibility mode, corroborated-table authority, or derived proof of absence", clean_owner: "batpak::integrity", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::Never, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-020", law: "Complexity regressions require work/count evidence, not noisy stopwatch alone", clean_owner: "testpak::bench", gates: &[GateId::G3, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-021", law: "Coordinate names a logical context stream, not a filesystem/network shard", clean_owner: "batpak::coordinate", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-022", law: "Commit pagination, ancestry, delivery cursor, projection path, and world path are distinct axes", clean_owner: "batpak::navigation", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-023", law: "Content digest, event commitment, predecessor topology, signature, inclusion, and anchor are separate claims: ContentDigest equality proves payload-content equality only within its declared digest scope and never proves EventCommitment equality, EventCommitment binds the complete event identity and committed semantic envelope required by the storage contract while its exact fields and bytes remain G2 format constants, predecessor verification requires the exact immediate predecessor for the canonical stream identity so an event appearing somewhere in a verified set is not thereby the immediate predecessor, legal genesis occurs only at the lawful stream head, and a derived index may locate candidate authority bytes but may not select the expected authority bytes and then use those selected bytes to authenticate its own selection; lane isolation is owned by LEG-050 and visible linearization by LEG-067 and this row cites rather than absorbs them", clean_owner: "batpak::integrity", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-024", law: "Event kind allocation and parsing are total, bounded, and collision-checked", clean_owner: "batpak::event", gates: &[GateId::G1, GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-025", law: "HLC chronology does not replace global commit order, stream position, or causality", clean_owner: "batpak::time", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-026", law: "Entity-local aggregate and selector-backed region materialization are different contracts", clean_owner: "batpak::projection", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-027", law: "Typed path/collation identity is versioned, bounded, locale-independent, and non-coercing", clean_owner: "batpak::path", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::FrozenCanonicalIdentity, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-028", law: "Sparse projection trees are disposable views with bounded get/children/scan whose item limit and work budget constrain discovery before decode allocation or materialization, and whose cursors bind store lineage generation source cut direction selector and filters so a transplanted or stale cursor fails closed rather than resuming against a different traversal", clean_owner: "batpak::projection", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-029", law: "Projection query authority binds contract, selector, shape, bounds, source stamp, completeness, and proof, and every page carries ordered entries a completeness posture a lawful next cursor a source stamp a WorkObservation and a proof result, so concatenated valid pages equal a one-shot reference traversal without gaps duplicates or reordering and no page claims completeness merely by filling its requested size", clean_owner: "batpak::projection_query", gates: &[GateId::G2, GateId::G6, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-030", law: "Full and incremental projection application agree at the same cut", clean_owner: "batpak::projection", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-031", law: "Fold fusion equals separate folds over one frozen traversal", clean_owner: "batpak::projection", gates: &[GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-032", law: "Lossy push is awareness; durable cursor pull is at-least-once replay truth", clean_owner: "batpak::delivery", gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-033", law: "Reaction output is typed, atomically staged, and dropped structurally on handler error", clean_owner: "syncbat::runtime", gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-034", law: "Durable cursor checkpoint, at-least-once witness, panic recovery, restart budget, and explicit join errors remain visible", clean_owner: "syncbat::runtime", gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-035", law: "Cooperative and threaded drivers preserve one logical transition protocol", clean_owner: "syncbat::runtime", gates: &[GateId::G3, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-036", law: "Declared effect row must contain observed effects and receipt payload", clean_owner: "syncbat::runtime", gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-037", law: "Atomic typed batch append is one runtime effect, not a bypass: heterogeneous typed publication commands join one atomic group only where the admitting capability owns their common authority boundary, input order and receipt order correspond exactly, an admitted atomic group never publishes a partial durable subset, and this is not an arbitrary distributed transaction across unrelated ports or authorities", clean_owner: "batpak::effect", gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-038", law: "External effects record requested/attempted/completed/failed/outcome-unknown and recovery class", clean_owner: "syncbat::runtime", gates: &[GateId::G5, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-039", law: "Public async integration does not leak raw Flume semantics or require an executor", clean_owner: "syncbat::runtime", gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-040", law: "Schemas have language-neutral identity, versions, canonical bytes, and goldens; Rust paths are diagnostic", clean_owner: "batpak::schema", gates: &[GateId::G2, GateId::G5], compatibility_disposition: CompatibilityDisposition::FrozenCanonicalIdentity, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-041", law: "Composition identity is deterministic and changes with interface authority", clean_owner: "batpak::world", gates: &[GateId::G5], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-042", law: "One AttemptId binds start, execution, report, and reconciliation and distinguishes cancellation before admission from cancellation after admission, so a cancelled admitted attempt is never read as proof of non-commit and a retry of the same logical operation receives a new AttemptId without erasing prior attempt evidence", clean_owner: "syncbat::bvisor", gates: &[GateId::G5], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-043", law: "Reports state established postconditions, not planned mechanisms", clean_owner: "syncbat::bvisor", gates: &[GateId::G5], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-044", law: "Admission decision circuits are bounded, canonical, and independently cross-checked", clean_owner: "syncbat::pakvm", gates: &[GateId::G3, GateId::G5], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-045", law: "Transport is bounded, domain-thin, and cannot launder proof", clean_owner: "netbat", gates: &[GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-046", law: "One declaration becomes one typed Contract IR and generated lowerings whose typed effect routing is closed and exhaustive: a missing duplicate or unknown route identity a decoder that does not match the declared type a missing effect capability or a missing receipt projection fails closed, route discovery is never ambient linker registration startup constructors or process-global registries, and the generated router owns structure and glue rather than application domain transition logic", clean_owner: "macbat-compiler", gates: &[GateId::G1], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-047", law: "Error handling class and public error shape do not drift into side tables", clean_owner: "macbat-compiler", gates: &[GateId::G1, GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-048", law: "Repo facts, dependency roles, proof obligations, and mutations have one normalized fact plane", clean_owner: "testpak::repo", gates: &[GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-049", law: "Proof inventories require hostile semantic closure, rule qualification, and freshness", clean_owner: "testpak::gauntlet", gates: &[GateId::G3, GateId::G9], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-050", law: "Per-entity lane heads, clocks, compare-and-set state, predecessor links, and branch queries remain lane-isolated while unfiltered reads preserve the all-lane timeline", clean_owner: "batpak::event", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-051", law: "An append durability/visibility gate timeout reports the unmet wait guarantee without pretending the already-committed event was rolled back", clean_owner: "batpak::store", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-052", law: "Open typestate implies a live writer; sync/drop failures surface honestly; read-only open never mints or appends authority/lifecycle state", clean_owner: "batpak::store", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-053", law: "Every persisted format/version pair has one canonical open or typed refusal; corrupt regenerable caches may rebuild while damaged authority fails closed", clean_owner: "batpak::compatibility", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::CanonicalOrTypedRefusal, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-054", law: "Cross-journal or cross-directory consistency is product/runtime composition, never an implicit single-journal guarantee", clean_owner: "syncbat::runtime", gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-055", law: "Supplying an injected clock makes ambient wall/monotonic time unreachable through open, append, sync, close, and runtime transitions", clean_owner: "batpak::time", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-056", law: "Visibility publication occurs only after every active index/tile view for the sequence range is populated", clean_owner: "batpak::store", gates: &[GateId::G2, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-057", law: "Group-commit admission requires stable item idempotency so replay cannot duplicate a partially acknowledged group", clean_owner: "batpak::store", gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-058", law: "Dropping an unsubmitted output/effect buffer publishes nothing; only explicit submit/commit crosses the durable boundary", clean_owner: "syncbat::runtime", gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-059", law: "Receipts are constructed only by the owning gate/runtime; unknown operations do not fabricate receipts; receipt-sink failure cannot report success", clean_owner: "batpak::receipt", gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-060", law: "Subscription sessions have explicit open/receive/close/overrun terminals and never fabricate delivery after producer closure", clean_owner: "syncbat::runtime", gates: &[GateId::G6, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-061", law: "Required capabilities are checked before program/handler execution and concrete observed effects remain a subset of declaration, world imports, instance grants, and budget", clean_owner: "syncbat::bvisor", gates: &[GateId::G5, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-062", law: "Durable runtime registration/composition state folds in journal order, rejects malformed/conflicting transitions, and rebuilds identically after reopen", clean_owner: "syncbat::world", gates: &[GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-063", law: "Public traversal and transport terminals expose domain-neutral substrate metadata, never downstream workflow entities or decoded application semantics", clean_owner: "batpak::navigation", gates: &[GateId::G2, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-064", law: "Public wire, ID, event, cursor, and receipt values round-trip every valid case, reject malformed bytes without partial success, and enforce exact declared lengths", clean_owner: "testpak::oracle", gates: &[GateId::G2, GateId::G7], compatibility_disposition: CompatibilityDisposition::FrozenCanonicalIdentity, deletion_condition: DeletionCondition::OnCompatibilityWindowExpiry, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-065", law: "Fault injection, poison levers, allocator faults, and dangerous frontier mutation are absent from default production profiles", clean_owner: "testpak::repo", gates: &[GateId::G0, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::Never, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-066", law: "Platform adapters may emit evidence and enforce mechanisms but cannot define durability, replay, visibility, admission, deadline, or proof meaning: a relative inactivity timeout never substitutes for an absolute monotonic deadline, the lowest mechanism able to extend work enforces the remaining absolute deadline, and a retry never resets the overall deadline", clean_owner: "batpak::port", gates: &[GateId::G2, GateId::G5, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-067", law: "Visible journal history is a dense single-writer linearization: no gap below the visible high-water, monotonic rereads, convergent readers, and no return-order inversion", clean_owner: "batpak::store", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-068", law: "Cache prefetch, acceleration, and retained-window behavior is discoverable through an explicit capability or configuration surface; no hidden cache policy changes semantics", clean_owner: "batpak::tile", gates: &[GateId::G2, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-069", law: "The default clock adapter produces positive advancing wall observations, while an injected clock owns every observation and makes ambient time unreachable", clean_owner: "batpak::time", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-070", law: "Applied progress is the minimum reflected frontier across every required registered projection; one lagging projection prevents an overclaimed applied frontier", clean_owner: "batpak::frontier", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-071", law: "After reopen, the durable frontier honestly covers every visible recovered event without claiming which unacknowledged in-flight events had to survive", clean_owner: "batpak::frontier", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-072", law: "Frontier and checkpoint waits succeed only after observing the target on the same state transition that wakes them; spurious wakeups never satisfy progress", clean_owner: "batpak::frontier", gates: &[GateId::G2, GateId::G6], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-073", law: "HLC causal merge remains a bounded commutative, associative, idempotent join with an explicit bottom; it never substitutes for commit or stream order", clean_owner: "batpak::time", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-074", law: "Import interrupted at any durability boundary is safely retryable through stable import identity and cannot duplicate already-applied source events", clean_owner: "batpak::lifecycle", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-075", law: "Same-journal import freezes its source visible ceiling before appending and cannot ingest its own newly created output", clean_owner: "batpak::lifecycle", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-076", law: "Compiler-generated integer narrowing is preceded by an explicit bound check and produces a source diagnostic instead of truncation or panic", clean_owner: "macbat-compiler", gates: &[GateId::G1], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-077", law: "Caller position hints may provide only contract-authorized branch hints; writer-owned commit point, HLC, stream position, and sequence remain authoritative and survive every qualified representation", clean_owner: "batpak::event", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-078", law: "Prepared or cached batch staging is an optimization only; it must commit, recover, publish, and receipt identically to fresh construction", clean_owner: "batpak::store", gates: &[GateId::G2, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-079", law: "Any two profiles or representations claiming semantic equivalence produce identical visible observables at one frozen cut; disagreement is a hard finding, never a tolerated optimization delta", clean_owner: "testpak::oracle", gates: &[GateId::G3, GateId::G8], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::Never, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-080", law: "The public store/runtime surface remains sync-first with no hidden executor; async and browser hosts own suspension and resume outside the semantic API", clean_owner: "syncbat::port", gates: &[GateId::G0, GateId::G5, GateId::G7], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::Never, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-081", law: "Secret-authority deletion is durable and anti-rollback: a shred is acknowledged only after the owning key backend durably destroys the required material; secret authority binds StoreId AuthorityGeneration KeyGeneration key-scope and shred-transition identity; no foreign stale or pre-shred keyset restores readability to a newer store generation; Shredded Unavailable and KeysetMissing stay distinct; snapshot fork WorldImage artifact bundles and ordinary receipts carry no raw key material by default; an external key backend preserves the same deletion durability generation and anti-rollback semantics", clean_owner: "batpak::secret", gates: &[GateId::G2, GateId::G3], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-082", law: "Compaction namespace publication is crash-atomic and accepted only when the pending marker, store metadata commit record, and authority image agree on the published generation", clean_owner: "batpak::compaction", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-083", law: "Idempotency-authority export and restore are fail-closed, lineage-bound, generation-bound, and publish a fresh destination AuthorityImageId through the destination authority chain", clean_owner: "batpak::store", gates: &[GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
    LegacyObligation { id: "LEG-084", law: "Public and user write surfaces cannot mint internal lifecycle, effect, transaction-envelope, authority, or recovery-control event classes", clean_owner: "batpak::event", gates: &[GateId::G1, GateId::G2], compatibility_disposition: CompatibilityDisposition::None, deletion_condition: DeletionCondition::OnSuccessorGateClosure, active_or_closed_status: ObligationStatus::Active },
];
