//! Frozen clean-room BatQL operator facts (V1 operator surface).
//!
//! OperatorSpec is the single source of concrete operator relationships:
//! spelling, arity, fixity, precedence, associativity, sorts, exactness, and
//! the projected precedence / grammar / formatting / spoken tables generated by
//! `bootstrap/project.py`. It owns operator-related grammar fragments and tables
//! only. It does NOT own function, MATCH, declaration, or the general lexical
//! grammar, which remain authored in `companion/BATQL_LANGUAGE.md`.
//!
//! DEC-060 remains the authored arithmetic and operator decision; OperatorSpec
//! is the concrete fact table that decision points to. V1 exposes no
//! approximate-number sorts and no approximate-literal syntax: those arrive with
//! 5.5B2 (Qualified Approximation), which will extend this table.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OperatorClass {
    Arithmetic,
    Comparison,
    Logical,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Arity {
    Unary,
    Binary,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Fixity {
    Prefix,
    Infix,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Associativity {
    Left,
    Right,
    NonAssociative,
}

/// V1 numeric authority is exact. `NotApplicable` marks operators that do not
/// carry an exact/approximate distinction (the truth operators). No `Approximate`
/// variant exists until 5.5B2.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Exactness {
    Exact,
    NotApplicable,
}

/// Per-operator numeric authority-support posture. Exact arithmetic is always
/// supported (DEC-060); approximate arithmetic through `+ - * /` is never
/// automatic and is admitted only when a qualified profile defines sound error
/// or interval propagation. No `Approximate` value exists until a profile ships.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NumericSupport {
    /// Exact operands admitted directly; approximate operands must Quantize first
    /// or use a qualified profile.
    ExactSupported,
    /// Admitted only inside a qualified numeric profile.
    QualifiedProfileOnly,
    /// Not admitted for numeric operands.
    Unsupported,
    /// Not an arithmetic/numeric operator (logical truth operators).
    NotApplicable,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct OperatorSpec {
    pub id: &'static str,
    pub class: OperatorClass,
    /// Canonical word spelling (or the canonical symbol where arithmetic has no word form).
    pub word_surface: &'static str,
    /// Symbol alias, or "" when the canonical spelling is already the symbol.
    pub symbol_surface: &'static str,
    pub semantic_op: &'static str,
    pub arity: Arity,
    pub fixity: Fixity,
    /// Higher binds tighter.
    pub precedence: u8,
    pub associativity: Associativity,
    pub input_sorts: &'static str,
    pub result_sort: &'static str,
    pub exactness: Exactness,
    pub overflow: &'static str,
    pub exception: &'static str,
    pub formatting: &'static str,
    pub spoken: &'static str,
    pub mutation_classes: &'static str,
    pub numeric_support: NumericSupport,
}

pub const OPERATORS: &[OperatorSpec] = &[
    OperatorSpec { id: "OP-MUL", class: OperatorClass::Arithmetic, word_surface: "*", symbol_surface: "", semantic_op: "multiply", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 70, associativity: Associativity::Left, input_sorts: "exact dimensional times exact dimensionless", result_sort: "exact dimensional", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "a non-dimensionless multiplicand is a type error", formatting: "*", spoken: "times", mutation_classes: "precedence, associativity, constant-folding, parenthesis, scale-adjustment", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-DIV", class: OperatorClass::Arithmetic, word_surface: "/", symbol_surface: "", semantic_op: "divide", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 70, associativity: Associativity::Left, input_sorts: "exact over exact like-dimension", result_sort: "Ratio or scaled exact", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "division by zero is INVALID; unlike dimensions are a type error", formatting: "/", spoken: "divided by", mutation_classes: "precedence, associativity, constant-folding, parenthesis, division-by-zero, scale-adjustment", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-ADD", class: OperatorClass::Arithmetic, word_surface: "+", symbol_surface: "", semantic_op: "add", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 60, associativity: Associativity::Left, input_sorts: "exact same-unit pair", result_sort: "exact same-unit", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "cross-unit operands are a type error", formatting: "+", spoken: "plus", mutation_classes: "precedence, associativity, constant-folding, parenthesis, unit-checking", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-SUB", class: OperatorClass::Arithmetic, word_surface: "-", symbol_surface: "", semantic_op: "subtract", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 60, associativity: Associativity::Left, input_sorts: "exact same-unit pair", result_sort: "exact same-unit", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "cross-unit operands are a type error", formatting: "-", spoken: "minus", mutation_classes: "precedence, associativity, constant-folding, parenthesis, unit-checking", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-EQ", class: OperatorClass::Comparison, word_surface: "IS", symbol_surface: "=", semantic_op: "equal", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS", spoken: "is", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-NE", class: OperatorClass::Comparison, word_surface: "IS NOT", symbol_surface: "!=", semantic_op: "not-equal", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS NOT", spoken: "is not", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-LT", class: OperatorClass::Comparison, word_surface: "IS LESS THAN", symbol_surface: "<", semantic_op: "less-than", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS LESS THAN", spoken: "is less than", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-LE", class: OperatorClass::Comparison, word_surface: "IS AT MOST", symbol_surface: "<=", semantic_op: "at-most", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS AT MOST", spoken: "is at most", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-GT", class: OperatorClass::Comparison, word_surface: "IS MORE THAN", symbol_surface: ">", semantic_op: "more-than", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS MORE THAN", spoken: "is more than", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-GE", class: OperatorClass::Comparison, word_surface: "IS AT LEAST", symbol_surface: ">=", semantic_op: "at-least", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS AT LEAST", spoken: "is at least", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-NOT", class: OperatorClass::Logical, word_surface: "NOT", symbol_surface: "", semantic_op: "logical-not", arity: Arity::Unary, fixity: Fixity::Prefix, precedence: 40, associativity: Associativity::NonAssociative, input_sorts: "truth value", result_sort: "Truth", exactness: Exactness::NotApplicable, overflow: "none", exception: "none; K3 total", formatting: "NOT", spoken: "not", mutation_classes: "precedence, parenthesis", numeric_support: NumericSupport::NotApplicable },
    OperatorSpec { id: "OP-AND", class: OperatorClass::Logical, word_surface: "AND", symbol_surface: "", semantic_op: "logical-and", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 30, associativity: Associativity::Left, input_sorts: "truth values", result_sort: "Truth", exactness: Exactness::NotApplicable, overflow: "none", exception: "none; K3 total", formatting: "AND", spoken: "and", mutation_classes: "precedence, associativity, parenthesis", numeric_support: NumericSupport::NotApplicable },
    OperatorSpec { id: "OP-OR", class: OperatorClass::Logical, word_surface: "OR", symbol_surface: "", semantic_op: "logical-or", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 20, associativity: Associativity::Left, input_sorts: "truth values", result_sort: "Truth", exactness: Exactness::NotApplicable, overflow: "none", exception: "none; K3 total", formatting: "OR", spoken: "or", mutation_classes: "precedence, associativity, parenthesis", numeric_support: NumericSupport::NotApplicable },
];
