//! Frozen clean-room BatQL operator facts (V1 operator surface).
//!
//! OperatorSpec is the single source of concrete operator relationships:
//! spelling, arity, fixity, precedence, associativity, sorts, exactness, and
//! the projected precedence / grammar / formatting / spoken tables generated by
//! `bootstrap/project.py`. It owns operator-related grammar fragments and tables
//! only. It does NOT own function, MATCH, declaration, or the general lexical
//! grammar, which remain authored in `companion/BATQL_LANGUAGE.md`.
//!
//! DEC-060 remains the authored arithmetic and operator decision; OperatorSpec
//! is the concrete fact table that decision points to. V1 exposes no
//! approximate-number sorts and no approximate-literal syntax: those arrive with
//! 5.5B2 (Qualified Approximation), which will extend this table.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OperatorClass {
    Arithmetic,
    Comparison,
    Logical,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Arity {
    Unary,
    Binary,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Fixity {
    Prefix,
    Infix,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Associativity {
    Left,
    Right,
    NonAssociative,
}

/// V1 numeric authority is exact. `NotApplicable` marks operators that do not
/// carry an exact/approximate distinction (the truth operators). No `Approximate`
/// variant exists until 5.5B2.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Exactness {
    Exact,
    NotApplicable,
}

/// Per-operator numeric authority-support posture. Exact arithmetic is always
/// supported (DEC-060); approximate arithmetic through `+ - * /` is never
/// automatic and is admitted only when a qualified profile defines sound error
/// or interval propagation. No `Approximate` value exists until a profile ships.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NumericSupport {
    /// Exact operands admitted directly; approximate operands must Quantize first
    /// or use a qualified profile.
    ExactSupported,
    /// Admitted only inside a qualified numeric profile.
    QualifiedProfileOnly,
    /// Not admitted for numeric operands.
    Unsupported,
    /// Not an arithmetic/numeric operator (logical truth operators).
    NotApplicable,
}

/// One legal operand→result shape for an operator (5.5E1 ruling). The
/// vocabulary is closed: a combination not derivable from an operator's rules
/// is a compile-time type error, and the companion's §5.2a legality matrix is
/// a generated projection of these rules — a hand-authored exception hiding in
/// prose is exactly how `DecimalMoney` and `SignedDuration` were born, two
/// phantom sorts no authority owned, deleted by this ruling.
///
/// An operator's rules are matched in DECLARATION ORDER and the first rule
/// whose operand shape matches decides: `PercentDifference` precedes
/// `SameUnit` on subtraction, so `Percent - Percent` yields
/// `PercentagePoints`, never a bare same-unit `Percent`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OperatorTypingRule {
    /// Exact same-unit pair → the same unit (`Money<USD> + Money<USD>`;
    /// cross-unit operands are a type error).
    SameUnit,
    /// Exact dimensional × exact dimensionless → the dimensional operand's
    /// sort (`Money<USD> * Percent → Money<USD>`), exact by scale increase
    /// where representable; scale reduction requires an explicit named
    /// rounding mode (DEC-060). There is no `DecimalMoney` result sort.
    DimensionalByDimensionless,
    /// Exact like-dimension pair → `Ratio` (`Money<USD> / Money<USD>`,
    /// `Duration / Duration`; unlike dimensions are a type error).
    LikeDimensionRatio,
    /// `Percent - Percent → PercentagePoints`: the difference of two rates is
    /// a point difference, not a rate.
    PercentDifference,
    /// `Percent ± PercentagePoints → Percent` (addition in either order): a
    /// point offset applied to a rate yields a rate.
    PercentAdjustment,
    /// `ObservedWallTime - ObservedWallTime → TimeDelta`: a signed diagnostic
    /// difference between two physical observations. A negative value is
    /// lawful evidence of wall-clock regression. `TimeDelta` is never
    /// `Duration`, `MonotonicDeadline`, HLC, journal progress, stream
    /// position, causal authority, commit identity, cursor authority, or
    /// durability evidence, satisfies no budget or timeout law, and converts
    /// only through an explicitly named conversion (docs/16, DEC-061).
    WallObservationDifference,
    /// Exact same-sort pair → `Truth` with `TypedMargin` (cross-sort
    /// comparison is a type error).
    SameSortComparison,
    /// `Truth → Truth`, K3 total.
    TruthUnary,
    /// `Truth × Truth → Truth`, K3 total.
    TruthBinary,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct OperatorSpec {
    pub id: &'static str,
    pub class: OperatorClass,
    /// Canonical word spelling (or the canonical symbol where arithmetic has no word form).
    pub word_surface: &'static str,
    /// Symbol alias, or "" when the canonical spelling is already the symbol.
    pub symbol_surface: &'static str,
    pub semantic_op: &'static str,
    pub arity: Arity,
    pub fixity: Fixity,
    /// Higher binds tighter.
    pub precedence: u8,
    pub associativity: Associativity,
    /// The closed legality rules for this operator, in match order. These are
    /// the operand→result AUTHORITY; `input_sorts`/`result_sort` remain the
    /// spoken/display description of the same law and may not disagree.
    pub typing: &'static [OperatorTypingRule],
    pub input_sorts: &'static str,
    pub result_sort: &'static str,
    pub exactness: Exactness,
    pub overflow: &'static str,
    pub exception: &'static str,
    pub formatting: &'static str,
    pub spoken: &'static str,
    pub mutation_classes: &'static str,
    pub numeric_support: NumericSupport,
}

pub const OPERATORS: &[OperatorSpec] = &[
    OperatorSpec { id: "OP-MUL", class: OperatorClass::Arithmetic, word_surface: "*", symbol_surface: "", semantic_op: "multiply", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 70, associativity: Associativity::Left, typing: &[OperatorTypingRule::DimensionalByDimensionless], input_sorts: "exact dimensional times exact dimensionless", result_sort: "exact dimensional", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "a non-dimensionless multiplicand is a type error", formatting: "*", spoken: "times", mutation_classes: "precedence, associativity, constant-folding, parenthesis, scale-adjustment", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-DIV", class: OperatorClass::Arithmetic, word_surface: "/", symbol_surface: "", semantic_op: "divide", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 70, associativity: Associativity::Left, typing: &[OperatorTypingRule::LikeDimensionRatio, OperatorTypingRule::DimensionalByDimensionless], input_sorts: "exact over exact like-dimension", result_sort: "Ratio or scaled exact", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "division by zero is INVALID; unlike dimensions are a type error", formatting: "/", spoken: "divided by", mutation_classes: "precedence, associativity, constant-folding, parenthesis, division-by-zero, scale-adjustment", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-ADD", class: OperatorClass::Arithmetic, word_surface: "+", symbol_surface: "", semantic_op: "add", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 60, associativity: Associativity::Left, typing: &[OperatorTypingRule::PercentAdjustment, OperatorTypingRule::SameUnit], input_sorts: "exact same-unit pair", result_sort: "exact same-unit", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "cross-unit operands are a type error", formatting: "+", spoken: "plus", mutation_classes: "precedence, associativity, constant-folding, parenthesis, unit-checking", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-SUB", class: OperatorClass::Arithmetic, word_surface: "-", symbol_surface: "", semantic_op: "subtract", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 60, associativity: Associativity::Left, typing: &[OperatorTypingRule::PercentDifference, OperatorTypingRule::PercentAdjustment, OperatorTypingRule::WallObservationDifference, OperatorTypingRule::SameUnit], input_sorts: "exact same-unit pair", result_sort: "exact same-unit", exactness: Exactness::Exact, overflow: "checked; typed INVALID on overflow", exception: "cross-unit operands are a type error", formatting: "-", spoken: "minus", mutation_classes: "precedence, associativity, constant-folding, parenthesis, unit-checking", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-EQ", class: OperatorClass::Comparison, word_surface: "IS", symbol_surface: "=", semantic_op: "equal", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS", spoken: "is", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-NE", class: OperatorClass::Comparison, word_surface: "IS NOT", symbol_surface: "!=", semantic_op: "not-equal", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS NOT", spoken: "is not", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-LT", class: OperatorClass::Comparison, word_surface: "IS LESS THAN", symbol_surface: "<", semantic_op: "less-than", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS LESS THAN", spoken: "is less than", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-LE", class: OperatorClass::Comparison, word_surface: "IS AT MOST", symbol_surface: "<=", semantic_op: "at-most", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS AT MOST", spoken: "is at most", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-GT", class: OperatorClass::Comparison, word_surface: "IS MORE THAN", symbol_surface: ">", semantic_op: "more-than", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS MORE THAN", spoken: "is more than", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-GE", class: OperatorClass::Comparison, word_surface: "IS AT LEAST", symbol_surface: ">=", semantic_op: "at-least", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 50, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::SameSortComparison], input_sorts: "exact same-sort pair", result_sort: "Truth with TypedMargin", exactness: Exactness::Exact, overflow: "none", exception: "cross-sort comparison is a type error", formatting: "IS AT LEAST", spoken: "is at least", mutation_classes: "precedence, comparison-direction, margin-sign, parenthesis", numeric_support: NumericSupport::ExactSupported },
    OperatorSpec { id: "OP-NOT", class: OperatorClass::Logical, word_surface: "NOT", symbol_surface: "", semantic_op: "logical-not", arity: Arity::Unary, fixity: Fixity::Prefix, precedence: 40, associativity: Associativity::NonAssociative, typing: &[OperatorTypingRule::TruthUnary], input_sorts: "truth value", result_sort: "Truth", exactness: Exactness::NotApplicable, overflow: "none", exception: "none; K3 total", formatting: "NOT", spoken: "not", mutation_classes: "precedence, parenthesis", numeric_support: NumericSupport::NotApplicable },
    OperatorSpec { id: "OP-AND", class: OperatorClass::Logical, word_surface: "AND", symbol_surface: "", semantic_op: "logical-and", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 30, associativity: Associativity::Left, typing: &[OperatorTypingRule::TruthBinary], input_sorts: "truth values", result_sort: "Truth", exactness: Exactness::NotApplicable, overflow: "none", exception: "none; K3 total", formatting: "AND", spoken: "and", mutation_classes: "precedence, associativity, parenthesis", numeric_support: NumericSupport::NotApplicable },
    OperatorSpec { id: "OP-OR", class: OperatorClass::Logical, word_surface: "OR", symbol_surface: "", semantic_op: "logical-or", arity: Arity::Binary, fixity: Fixity::Infix, precedence: 20, associativity: Associativity::Left, typing: &[OperatorTypingRule::TruthBinary], input_sorts: "truth values", result_sort: "Truth", exactness: Exactness::NotApplicable, overflow: "none", exception: "none; K3 total", formatting: "OR", spoken: "or", mutation_classes: "precedence, associativity, parenthesis", numeric_support: NumericSupport::NotApplicable },
];
