//! Negative-fixture runner (Cluster 14).
//!
//! Every `.rs` under `tests/trybuild_negative/` must FAIL to compile. Each covers
//! a distinct Section-C grammar/shape/value/rule rejection across the six front
//! doors — including the FIRST negatives for the Error and VariantInventory
//! surfaces (which shipped none before).
//!
//! The `.stderr` goldens are generated by trybuild's own flow on the first lane
//! run (`TRYBUILD=overwrite`), then committed; they are NOT hand-authored — a
//! hand-faked diagnostic golden would be worthless as proof.
//!
//! CAVEAT (flagged): the Projection/Subscription/Event surfaces emit `::batpak`/
//! `::syncbat` paths and do not resolve in the core-free lane. That is harmless
//! for the grammar/shape/value/rule negatives here because a REJECTED input emits
//! only `compile_error!` and drops all tokens. The lone exception,
//! `projection_handler_wrong_signature.rs`, is accepted by the grammar and fails
//! only at emitted-token typeck; in-lane its golden also carries unresolved
//! `::batpak` paths, so it is a clean handler-signature negative only post-J1.

#[test]
fn negative_fixtures_are_rejected() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/trybuild_negative/*.rs");
}
