use crate::guarantees::{ContractId, GuaranteeRef};
use crate::verification::{
    IndependentEvidenceRouteKind, VerificationBasis, VerificationClaimKind,
    VerificationCoverage, VerificationEnforcementPosture, VerificationLane,
    VerificationMethod, VerificationRequirement,
};

use super::types::*;

/// The COMPLETE proof-identity catalog (5.5E2j): every canonical active
/// proof-row identity docs/24 declares, in document order, followed by every
/// identity that ever stopped being authoritative. spec/proof/ owns
/// identity, lifecycle, succession, guarantee binding, projection membership,
/// claim, and verification-plan membership; docs/24 permanently owns semantic
/// summary, expected observation, and terminal disposition. Execution receipts
/// remain runtime evidence and are not catalog fields.
///
/// This replaced PROOF_ROW_MIGRATIONS, which held retirements alone and
/// validated successors by substring search over the whole of docs/24 — so a
/// successor whose canonical active row was deleted still "existed" as long
/// as its name survived in a migration note or a prose paragraph. A
/// forwarding address must point at the living census, not at a name painted
/// on an old wall: successor resolution and the active/docs equality laws
/// now run against this catalog and the structurally parsed canonical rows.

/// Named verification plans (5.5F2). Each is the exact axis tuple a family
/// of rows demands; rows reference plans by name so the catalog stays
/// readable and the audit can independently parse both. A plan is authored
/// posture — admission and qualification stay sealed in spec/verification/.
pub const PLAN_HOSTILE_BOUNDARY: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::PropertySequence, basis: VerificationBasis::DirectBoundary { route: Some(IndependentEvidenceRouteKind::HostileBoundary) }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];
pub const PLAN_FAULT_INJECTION: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::FaultInjection, basis: VerificationBasis::DirectBoundary { route: Some(IndependentEvidenceRouteKind::HostileBoundary) }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];
pub const PLAN_CRASH_RECOVERY: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::CrashRecovery, basis: VerificationBasis::DirectBoundary { route: Some(IndependentEvidenceRouteKind::HostileBoundary) }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];
pub const PLAN_DIFFERENTIAL: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::DifferentialExecution, basis: VerificationBasis::IndependentReference { route: IndependentEvidenceRouteKind::DifferentialImplementation }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];
pub const PLAN_HISTORY_REPLAY: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::HistoryReplay, basis: VerificationBasis::IndependentReference { route: IndependentEvidenceRouteKind::IndependentHistoryReplay }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];
pub const PLAN_STRUCTURAL: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::StructuralRule, basis: VerificationBasis::DirectBoundary { route: None }, coverage: VerificationCoverage::ExhaustiveWithinDeclaredModel, lane: VerificationLane::PullRequestFast, enforcement: VerificationEnforcementPosture::Blocking }];
pub const PLAN_COMPILE_REFUSAL: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::CompileRefusal, basis: VerificationBasis::DirectBoundary { route: None }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::PullRequestFast, enforcement: VerificationEnforcementPosture::Blocking }];
pub const PLAN_PROPERTY: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::PropertySequence, basis: VerificationBasis::DirectBoundary { route: None }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];
pub const PLAN_COMPLEXITY: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::ComplexityContract, basis: VerificationBasis::DirectBoundary { route: None }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];

/// Composite plans (5.5F3). A row demanding more than one axis tuple lists
/// each requirement literal on its own line; admission and jury still run in
/// spec/verification/, and enforcement posture per requirement is authored
/// here, never observed.
pub const PLAN_RECONCILIATION_REFINEMENT: &[VerificationRequirement] = &[
    VerificationRequirement { method: VerificationMethod::StructuralRule, basis: VerificationBasis::ContractProjection, coverage: VerificationCoverage::ExhaustiveWithinDeclaredModel, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking },
    VerificationRequirement { method: VerificationMethod::DifferentialExecution, basis: VerificationBasis::IndependentReference { route: IndependentEvidenceRouteKind::DifferentialImplementation }, coverage: VerificationCoverage::Bounded, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking },
    VerificationRequirement { method: VerificationMethod::ScheduleExploration, basis: VerificationBasis::DirectBoundary { route: Some(IndependentEvidenceRouteKind::HostileBoundary) }, coverage: VerificationCoverage::Bounded, lane: VerificationLane::Scheduled, enforcement: VerificationEnforcementPosture::Blocking },
];
pub const PLAN_LAW_CHANGE_REFUSAL: &[VerificationRequirement] = &[
    VerificationRequirement { method: VerificationMethod::TranslationValidation, basis: VerificationBasis::IndependentReference { route: IndependentEvidenceRouteKind::DifferentialImplementation }, coverage: VerificationCoverage::Bounded, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking },
    VerificationRequirement { method: VerificationMethod::PropertySequence, basis: VerificationBasis::DirectBoundary { route: Some(IndependentEvidenceRouteKind::HostileBoundary) }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking },
];
pub const PLAN_FRONTIER_EXPLORATION: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::BoundedStateExploration, basis: VerificationBasis::DirectBoundary { route: Some(IndependentEvidenceRouteKind::HostileBoundary) }, coverage: VerificationCoverage::Bounded, lane: VerificationLane::Scheduled, enforcement: VerificationEnforcementPosture::Blocking }];
pub const PLAN_BENCHMARK_ADVISORY: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::BenchmarkEnvelope, basis: VerificationBasis::DirectBoundary { route: None }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Release, enforcement: VerificationEnforcementPosture::Advisory }];
pub const PLAN_HOLDOUT_QUARANTINE: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::DifferentialExecution, basis: VerificationBasis::IndependentReference { route: IndependentEvidenceRouteKind::DifferentialImplementation }, coverage: VerificationCoverage::Bounded, lane: VerificationLane::Scheduled, enforcement: VerificationEnforcementPosture::Quarantine }];

/// F5 campaign-rehearsal plans (R1/R2/R7). Each names the exact axis tuple
/// the mini-supernova rehearsal executes; the rehearsal harness realizes the
/// rows below literally, so every tuple here is executed law, never
/// aspiration, and the adopter-closure law in seedcheck holds every
/// method/coverage/lane/claim variant to a live adopter among these rows.
///
/// The real planted semantic mutant: it compiles, passes the deliberately
/// insufficient happy-path test, changes semantics, and is recorded
/// ACTIVATED; the separately implemented witness executing differentially —
/// the independent reference, never the subject grading itself — kills it.
pub const PLAN_MUTATION: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::Mutation, basis: VerificationBasis::IndependentReference { route: IndependentEvidenceRouteKind::DifferentialImplementation }, coverage: VerificationCoverage::Sampled, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];
/// R2: a genuine bounded generated-trace attack on the real boundary. The
/// generator is a seeded deterministic PRNG and the receipt records the
/// exact seed and bounds, so the candidate run and the confirming run
/// reproduce the identical attack; the witness executes every generated
/// trace against the boundary under test — never a decorative fixture.
pub const PLAN_FUZZING: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::Fuzzing, basis: VerificationBasis::DirectBoundary { route: Some(IndependentEvidenceRouteKind::HostileBoundary) }, coverage: VerificationCoverage::Bounded, lane: VerificationLane::Scheduled, enforcement: VerificationEnforcementPosture::Blocking }];
/// R1: deterministic replay-equality of a FULLY SIMULATED trace of the
/// mini-ledger relation. The distinct observable property is trace
/// replay-equality under full simulation — explicitly not interleaving
/// exploration (that is ScheduleExploration) and not reachable-set
/// exploration (that is BoundedStateExploration). Bounded coverage: a
/// declared bounded set of simulated traces, each replayed to equality.
pub const PLAN_DETERMINISTIC_SIMULATION: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::DeterministicSimulation, basis: VerificationBasis::DirectBoundary { route: None }, coverage: VerificationCoverage::Bounded, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];
/// R7: the ObservedHistory/Runtime cluster, adopted as ONE cluster. The
/// capture requirement records the executing subject's append-only observed
/// history in the runtime lane; in-band observation may state
/// NoDivergenceObserved and never conformance, so its posture is Quarantine
/// — an observed divergence quarantines the candidate and never blocks the
/// running boundary (docs/38 section 6). The offline requirement
/// independently replays that complete recorded history and is the only
/// route to ConformantForObservedHistory, feeding the release envelope's
/// runtime-conformance dispositions. Capture without replay concludes
/// nothing; replay without capture has no history — one plan carries both.
pub const PLAN_RUNTIME_CONFORMANCE: &[VerificationRequirement] = &[
    VerificationRequirement { method: VerificationMethod::PropertySequence, basis: VerificationBasis::RuntimeObservation, coverage: VerificationCoverage::ObservedHistory, lane: VerificationLane::Runtime, enforcement: VerificationEnforcementPosture::Quarantine },
    VerificationRequirement { method: VerificationMethod::HistoryReplay, basis: VerificationBasis::IndependentReference { route: IndependentEvidenceRouteKind::IndependentHistoryReplay }, coverage: VerificationCoverage::ObservedHistory, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking },
];
/// Structural closure over the campaign's typed records, exhaustive within
/// the declared campaign model: every admitted obligation of THIS campaign
/// is walked to its terminal by the independent bundle verification at
/// merge. Coverage of the declared model is not coverage of its law.
pub const PLAN_CAMPAIGN_CLOSURE: &[VerificationRequirement] = &[VerificationRequirement { method: VerificationMethod::StructuralRule, basis: VerificationBasis::DirectBoundary { route: None }, coverage: VerificationCoverage::ExhaustiveWithinDeclaredModel, lane: VerificationLane::Merge, enforcement: VerificationEnforcementPosture::Blocking }];

pub const PROOF_ROWS: &[ProofRowRecord] = &[
    ProofRowRecord { id: ProofRowId("middle_event_deletion_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-023"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("event_reorder_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-023"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("duplicate_payload_splice_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-023"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("cross_lane_predecessor_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-023"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("cross_entity_predecessor_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-023"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("midstream_genesis_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-023"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("forged_index_row_cannot_choose_and_authenticate_bytes"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-023"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("forged_sibling_cannot_cause_false_loss"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-019"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("agreeing_truncated_table_cannot_cause_false_safety"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-019"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("derived_row_cannot_authenticate_siblings"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-019"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("derived_row_cannot_authenticate_table_count"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-019"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("derived_row_cannot_authenticate_order"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-019"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("derived_row_cannot_authenticate_tail_boundary"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-019"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("derived_row_cannot_prove_absence_or_loss"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-019"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("page_limit_bounds_discovery_work_not_only_output"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-028"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::ResourceEnvelope, verification: PLAN_COMPLEXITY } },
    ProofRowRecord { id: ProofRowId("allocation_does_not_scale_with_full_matched_set"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-020"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::ResourceEnvelope, verification: PLAN_COMPLEXITY } },
    ProofRowRecord { id: ProofRowId("descriptor_postcondition_failure_is_not_reported_applied"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-043"), projection_contracts: &[ContractId("BP-BVISOR-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FAULT_INJECTION } },
    ProofRowRecord { id: ProofRowId("fcntl_getfd_failure_fails_closed"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-043"), projection_contracts: &[ContractId("BP-BVISOR-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FAULT_INJECTION } },
    ProofRowRecord { id: ProofRowId("fcntl_setfd_failure_fails_closed"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-043"), projection_contracts: &[ContractId("BP-BVISOR-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FAULT_INJECTION } },
    ProofRowRecord { id: ProofRowId("close_reopen_reimport_returns_zero_new_events"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-074"), projection_contracts: &[ContractId("BP-MIGRATION-1")], claim: VerificationClaimKind::Safety, verification: PLAN_CRASH_RECOVERY } },
    ProofRowRecord { id: ProofRowId("signed_compaction_preserves_or_commits_the_removed_set"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-085"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("compaction_inputs_survive_until_replacement_evidence_is_durable"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-085"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_CRASH_RECOVERY } },
    ProofRowRecord { id: ProofRowId("matched_kind_decode_failure_is_a_typed_terminal"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-086"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("replay_routes_agree_on_first_failure_and_class"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-086"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Refinement, verification: PLAN_DIFFERENTIAL } },
    ProofRowRecord { id: ProofRowId("trapping_host_filesystem_remains_unreached_under_injected_storage"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-087"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FAULT_INJECTION } },
    ProofRowRecord { id: ProofRowId("paired_result_and_receipt_share_one_turn_evaluation"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-075"), projection_contracts: &[ContractId("BP-SYSTEM-MODEL-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("hlc_cannot_substitute_for_commit_sequence"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-075"), projection_contracts: &[ContractId("BP-SYSTEM-MODEL-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("receipt_binds_chronology_and_commit_without_collapsing_them"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-075"), projection_contracts: &[ContractId("BP-SYSTEM-MODEL-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("replay_reconstructs_same_turn_and_returns_original_receipts"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-075"), projection_contracts: &[ContractId("BP-SYSTEM-MODEL-1")], claim: VerificationClaimKind::Determinism, verification: PLAN_HISTORY_REPLAY } },
    ProofRowRecord { id: ProofRowId("lost_acknowledgement_requires_reconciliation_before_retry"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-075"), projection_contracts: &[ContractId("BP-SYSTEM-MODEL-1")], claim: VerificationClaimKind::NonOscillation, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("port_response_cannot_cross_attempts"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-075"), projection_contracts: &[ContractId("BP-SYSTEM-MODEL-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("driver_await_and_cooperative_drive_produce_equivalent_logical_trace"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-075"), projection_contracts: &[ContractId("BP-SYSTEM-MODEL-1")], claim: VerificationClaimKind::Refinement, verification: PLAN_RECONCILIATION_REFINEMENT } },
    ProofRowRecord { id: ProofRowId("checkpoint_gap_does_not_duplicate_committed_effect"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-075"), projection_contracts: &[ContractId("BP-SYSTEM-MODEL-1")], claim: VerificationClaimKind::Safety, verification: PLAN_CRASH_RECOVERY } },
    ProofRowRecord { id: ProofRowId("reconciliation_appends_evidence_without_rewriting_original_observation"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-075"), projection_contracts: &[ContractId("BP-SYSTEM-MODEL-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("shred_ack_waits_for_backend_durability"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-081"), projection_contracts: &[ContractId("BP-CRYPTO-SECRET-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("crash_before_durable_key_delete_does_not_report_shred_success"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-081"), projection_contracts: &[ContractId("BP-CRYPTO-SECRET-1")], claim: VerificationClaimKind::Safety, verification: PLAN_CRASH_RECOVERY } },
    ProofRowRecord { id: ProofRowId("reopen_after_ack_cannot_recover_shredded_plaintext"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-081"), projection_contracts: &[ContractId("BP-CRYPTO-SECRET-1")], claim: VerificationClaimKind::Safety, verification: PLAN_CRASH_RECOVERY } },
    ProofRowRecord { id: ProofRowId("shred_transition_binding_mismatch_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-081"), projection_contracts: &[ContractId("BP-CRYPTO-SECRET-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("stale_or_pre_shred_keyset_restore_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-081"), projection_contracts: &[ContractId("BP-CRYPTO-SECRET-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("foreign_keyset_generation_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-081"), projection_contracts: &[ContractId("BP-CRYPTO-SECRET-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("shredded_unavailable_and_keyset_missing_remain_distinct"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-081"), projection_contracts: &[ContractId("BP-CRYPTO-SECRET-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("snapshot_fork_worldimage_artifact_and_receipt_exports_exclude_raw_keys"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-081"), projection_contracts: &[ContractId("BP-CRYPTO-SECRET-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("external_key_backend_preserves_shred_semantics"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-081"), projection_contracts: &[ContractId("BP-CRYPTO-SECRET-1")], claim: VerificationClaimKind::Refinement, verification: PLAN_DIFFERENTIAL } },
    ProofRowRecord { id: ProofRowId("compressed_fbat_authority_frame_is_rejected_in_v1"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-053"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("compressed_vpak_semantic_section_is_rejected_in_v1"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-053"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("compression_profile_requires_expansion_bound"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-053"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("future_format_version_fails_with_its_own_typed_disposition"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-063"), projection_contracts: &[ContractId("BP-STORAGE-TILES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("program_image_id_is_independent_of_compiler_provenance"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-064"), projection_contracts: &[ContractId("BP-IDENTITY-TIME-NAV-1")], claim: VerificationClaimKind::Determinism, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("distinct_version_types_do_not_typecheck_when_substituted"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-064"), projection_contracts: &[ContractId("BP-IDENTITY-TIME-NAV-1")], claim: VerificationClaimKind::Safety, verification: PLAN_COMPILE_REFUSAL } },
    ProofRowRecord { id: ProofRowId("netbat_version_does_not_upgrade_pakvm_isa"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-064"), projection_contracts: &[ContractId("BP-IDENTITY-TIME-NAV-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("order_by_hlc_uses_commit_tiebreak"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-061"), projection_contracts: &[ContractId("BP-IDENTITY-TIME-NAV-1")], claim: VerificationClaimKind::Determinism, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("cross_store_hlc_order_is_total"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-061"), projection_contracts: &[ContractId("BP-IDENTITY-TIME-NAV-1")], claim: VerificationClaimKind::Determinism, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("hlc_range_is_half_open"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-061"), projection_contracts: &[ContractId("BP-IDENTITY-TIME-NAV-1")], claim: VerificationClaimKind::Conformance, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("frontier_progress_never_uses_hlc_order"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-061"), projection_contracts: &[ContractId("BP-IDENTITY-TIME-NAV-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("observed_wall_time_is_not_promoted_to_hlc"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-061"), projection_contracts: &[ContractId("BP-IDENTITY-TIME-NAV-1")], claim: VerificationClaimKind::Safety, verification: PLAN_COMPILE_REFUSAL } },
    ProofRowRecord { id: ProofRowId("no_std_batpak_has_no_std_dependency_route"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-065"), projection_contracts: &[ContractId("BP-REPOSITORY-PACKAGES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("no_std_syncbat_has_no_std_dependency_route"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-065"), projection_contracts: &[ContractId("BP-REPOSITORY-PACKAGES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("default_std_does_not_enable_threaded_or_browser_adapters"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-065"), projection_contracts: &[ContractId("BP-REPOSITORY-PACKAGES-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("browser_and_native_profiles_preserve_program_semantics"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-065"), projection_contracts: &[ContractId("BP-REPOSITORY-PACKAGES-1")], claim: VerificationClaimKind::Refinement, verification: PLAN_DIFFERENTIAL } },
    ProofRowRecord { id: ProofRowId("hash_map_iteration_cannot_influence_canonical_observables"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-065"), projection_contracts: &[ContractId("BP-TYPE-SYSTEM-1")], claim: VerificationClaimKind::Determinism, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("attacker_length_is_checked_before_reserve"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-066"), projection_contracts: &[ContractId("BP-SYNCBAT-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("allocation_failure_returns_resource_exhausted"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-066"), projection_contracts: &[ContractId("BP-SYNCBAT-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FAULT_INJECTION } },
    ProofRowRecord { id: ProofRowId("declared_work_overrun_returns_budget_exceeded"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-066"), projection_contracts: &[ContractId("BP-SYNCBAT-1")], claim: VerificationClaimKind::ResourceEnvelope, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("resource_exhaustion_never_publishes_partial_event"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-066"), projection_contracts: &[ContractId("BP-SYNCBAT-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FAULT_INJECTION } },
    ProofRowRecord { id: ProofRowId("resource_exhaustion_never_advances_checkpoint"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-066"), projection_contracts: &[ContractId("BP-SYNCBAT-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FAULT_INJECTION } },
    ProofRowRecord { id: ProofRowId("artifact_staging_failure_publishes_no_artifact_ref"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-066"), projection_contracts: &[ContractId("BP-SYNCBAT-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FAULT_INJECTION } },
    ProofRowRecord { id: ProofRowId("pakvm_arena_exhaustion_returns_typed_terminal_disposition"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-066"), projection_contracts: &[ContractId("BP-SYNCBAT-1")], claim: VerificationClaimKind::ResourceEnvelope, verification: PLAN_FAULT_INJECTION } },
    ProofRowRecord { id: ProofRowId("kernel_cannot_resolve_by_display_name"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-062"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("kernel_contract_and_implementation_ids_are_not_interchangeable"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-062"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_COMPILE_REFUSAL } },
    ProofRowRecord { id: ProofRowId("qualified_interface_requires_matching_qualification_receipt"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-062"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("exact_kernel_binding_rejects_another_implementation"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-062"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("attempt_receipt_records_exact_kernel_implementation"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-062"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Conformance, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("local_domain_type_inside_function_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("local_domain_type_inside_closure_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("test_local_nonsemantic_fixture_type_is_allowed"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Conformance, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("production_expect_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("test_expect_with_context_is_allowed"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Conformance, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("unledgered_unsafe_fn_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("unledgered_pointer_cast_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("public_flume_receiver_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("hash_map_iteration_in_canonical_encoder_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("drawer_module_name_requires_explicit_disposition"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-068"), projection_contracts: &[ContractId("BP-TESTPAK-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("raw_batql_is_not_a_netbat_invocation"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-051"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("compiler_port_is_not_available_to_guest_programs"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-051"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("compiler_port_is_absent_from_default_server_profile"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-051"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("compiler_output_still_requires_program_validation"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-051"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("query_program_with_effect_instruction_is_rejected"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-050"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("query_program_cannot_install_process"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-050"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("query_program_cannot_request_write_capability"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-050"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("query_program_over_work_bound_is_denied_before_execution"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-050"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::ResourceEnvelope, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("query_program_result_binds_program_and_grant_identity"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-050"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Conformance, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("entrypoint_receipt_cannot_satisfy_query_program_execution"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-050"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("entrypoint_cannot_substitute_foreign_program_image"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-049"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("entrypoint_effect_must_be_declared_by_world_interface"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-049"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("query_program_receipt_cannot_satisfy_entrypoint_invocation"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-049"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("tls_does_not_upgrade_program_or_proof_authority"), state: ProofRowState::Active { guarantee: GuaranteeRef::leg("LEG-045"), projection_contracts: &[ContractId("BP-WORLD-PORTS-1")], claim: VerificationClaimKind::Safety, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("candidate_origin_confers_no_authority"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-079"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("scaffold_cannot_close_realization"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-079"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Safety, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("qualified_nursery_record_is_not_promoted_source"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-079"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("law_changing_candidate_cannot_enter_realization_preserving_lane"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-080"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Safety, verification: PLAN_LAW_CHANGE_REFUSAL } },
    ProofRowRecord { id: ProofRowId("search_budget_is_declared_and_receipted"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-081"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Conformance, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("search_and_holdout_sets_are_disjoint"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-081"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Conformance, verification: PLAN_STRUCTURAL } },
    ProofRowRecord { id: ProofRowId("failed_holdout_candidate_is_quarantined"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-081"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Refinement, verification: PLAN_HOLDOUT_QUARANTINE } },
    ProofRowRecord { id: ProofRowId("candidate_cannot_modify_frozen_judge"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-082"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Safety, verification: PLAN_HOSTILE_BOUNDARY } },
    ProofRowRecord { id: ProofRowId("later_green_cannot_bless_unresolved_dependency"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-082"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FRONTIER_EXPLORATION } },
    ProofRowRecord { id: ProofRowId("specialized_plan_benchmark_is_advisory_only"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-073"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::ResourceEnvelope, verification: PLAN_BENCHMARK_ADVISORY } },
    // F5 mini-supernova rehearsal rows. Realized literally by the campaign
    // rehearsal harness; docs/24 owns each row's semantic meaning.
    ProofRowRecord { id: ProofRowId("planted_semantic_mutant_is_activated_and_killed"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-081"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Safety, verification: PLAN_MUTATION } },
    ProofRowRecord { id: ProofRowId("bounded_generated_trace_attack_holds_boundary"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-080"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Safety, verification: PLAN_FUZZING } },
    ProofRowRecord { id: ProofRowId("deterministic_replay_equality_of_simulated_trace"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-081"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Determinism, verification: PLAN_DETERMINISTIC_SIMULATION } },
    ProofRowRecord { id: ProofRowId("runtime_capture_appends_observed_history_without_rewrite"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-078"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Safety, verification: PLAN_RUNTIME_CONFORMANCE } },
    ProofRowRecord { id: ProofRowId("offline_replay_concludes_conformance_for_captured_history"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-078"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Conformance, verification: PLAN_RUNTIME_CONFORMANCE } },
    ProofRowRecord { id: ProofRowId("every_admitted_campaign_obligation_reaches_a_terminal"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-080"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Liveness, verification: PLAN_CAMPAIGN_CLOSURE } },
    ProofRowRecord { id: ProofRowId("candidate_search_terminates_within_declared_budget"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-081"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::BoundedResponse, verification: PLAN_COMPLEXITY } },
    ProofRowRecord { id: ProofRowId("bounded_repair_loop_reaches_stable_qualified_frontier"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-082"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Convergence, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("confirming_rerun_changes_no_authoritative_result"), state: ProofRowState::Active { guarantee: GuaranteeRef::dec("DEC-076"), projection_contracts: &[ContractId("BP-SPROUTING-1")], claim: VerificationClaimKind::Stability, verification: PLAN_PROPERTY } },
    ProofRowRecord { id: ProofRowId("pre_shred_keyset_restore_is_rejected"), state: ProofRowState::Retired { successors: &[ProofRowId("stale_or_pre_shred_keyset_restore_is_rejected")] } },
    ProofRowRecord { id: ProofRowId("shredded_and_keyset_missing_remain_distinct"), state: ProofRowState::Retired { successors: &[ProofRowId("shredded_unavailable_and_keyset_missing_remain_distinct")] } },
    ProofRowRecord { id: ProofRowId("snapshot_and_fork_exclude_keys_by_default"), state: ProofRowState::Retired { successors: &[ProofRowId("snapshot_fork_worldimage_artifact_and_receipt_exports_exclude_raw_keys")] } },
    ProofRowRecord { id: ProofRowId("hash_map_iteration_cannot_change_canonical_bytes"), state: ProofRowState::Retired { successors: &[ProofRowId("hash_map_iteration_cannot_influence_canonical_observables")] } },
    ProofRowRecord { id: ProofRowId("attempt_receipt_cannot_cross_invocation_classes"), state: ProofRowState::Retired { successors: &[ProofRowId("entrypoint_receipt_cannot_satisfy_query_program_execution"), ProofRowId("query_program_receipt_cannot_satisfy_entrypoint_invocation")] } },
    ProofRowRecord { id: ProofRowId("test_local_fixture_type_is_classified_correctly"), state: ProofRowState::Retired { successors: &[ProofRowId("test_local_nonsemantic_fixture_type_is_allowed")] } },
];
