use crate::guarantees::BootstrapToolId;
use super::types::{GeneratedViewSpec, GeneratedViewSurface, GeneratedViewTarget};

/// Every generated view the repository carries, in canonical registry order.
/// Completeness is enum-to-ALL equality plus total `spec()` coverage — no
/// numeric count is the law.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GeneratedView {
    OperatorsCatalog,
    OperatorsSurfaces,
    OperatorsGrammar,
    OperatorsProjection,
    OperatorsTyping,
    OperatorsNumeric,
    SeedClassification,
    GuaranteeGraph,
    PakVmSemanticIsa,
    PakVmSignatures,
    SyncBatPlaneOwnership,
    SyncBatAuthorities,
    SyncBatCrossings,
    ReconciliationCoordinates,
    ReconciliationRetry,
    ReleaseSeal,
    ProofTerminals,
    StaleVocabulary,
    GateInventory,
    ContractKinds,
    RustToolchain,
    IdentityCatalog,
    GenerationCatalog,
    BindingCatalog,
    VersionCatalog,
    IdentityResidue,
    ProductCommands,
    TestPakCommands,
    BatQlSourceModes,
    MutationLanes,
    MutationResults,
    PromotionRequirements,
    CompilerAssumptionKinds,
    CorpusReconciliationEpoch,
    CorpusEpochMembership,
    PackageInventory,
    PackageEdges,
    QualificationProfiles,
    BundleInventory,
    Tier0ReceiptDenominator,
    DecisionLedger,
    LegacyInvariantCoverage,
    LegacyObligationLedger,
    GauntletProofRelations,
    SystemModelProofRequirements,
    RepositoryProofRequirements,
    TypeSystemProofRequirements,
    StorageProofRequirements,
    SyncBatProofRequirements,
    BvisorProofRequirements,
    WorldPortsProofRequirements,
    TestPakProofRequirements,
    IdentityTimeProofRequirements,
    MigrationProofRequirements,
    SecretAuthorityProofRequirements,
    Gate0MaterializationPlan,
    VerificationPlans,
    SproutingVocabulary,
    SpecializedPlanCandidatePolicy,
    SproutingProofRequirements,
    GeneratedViewRegistry,
    SpecModuleCatalog,
    BootstrapToolCatalog,
}

impl GeneratedView {
    pub const ALL: &'static [GeneratedView] = &[
        GeneratedView::OperatorsCatalog,
        GeneratedView::OperatorsSurfaces,
        GeneratedView::OperatorsGrammar,
        GeneratedView::OperatorsProjection,
        GeneratedView::OperatorsTyping,
        GeneratedView::OperatorsNumeric,
        GeneratedView::SeedClassification,
        GeneratedView::GuaranteeGraph,
        GeneratedView::PakVmSemanticIsa,
        GeneratedView::PakVmSignatures,
        GeneratedView::SyncBatPlaneOwnership,
        GeneratedView::SyncBatAuthorities,
        GeneratedView::SyncBatCrossings,
        GeneratedView::ReconciliationCoordinates,
        GeneratedView::ReconciliationRetry,
        GeneratedView::ReleaseSeal,
        GeneratedView::ProofTerminals,
        GeneratedView::StaleVocabulary,
        GeneratedView::GateInventory,
        GeneratedView::ContractKinds,
        GeneratedView::RustToolchain,
        GeneratedView::IdentityCatalog,
        GeneratedView::GenerationCatalog,
        GeneratedView::BindingCatalog,
        GeneratedView::VersionCatalog,
        GeneratedView::IdentityResidue,
        GeneratedView::ProductCommands,
        GeneratedView::TestPakCommands,
        GeneratedView::BatQlSourceModes,
        GeneratedView::MutationLanes,
        GeneratedView::MutationResults,
        GeneratedView::PromotionRequirements,
        GeneratedView::CompilerAssumptionKinds,
        GeneratedView::CorpusReconciliationEpoch,
        GeneratedView::CorpusEpochMembership,
        GeneratedView::PackageInventory,
        GeneratedView::PackageEdges,
        GeneratedView::QualificationProfiles,
        GeneratedView::BundleInventory,
        GeneratedView::Tier0ReceiptDenominator,
        GeneratedView::DecisionLedger,
        GeneratedView::LegacyInvariantCoverage,
        GeneratedView::LegacyObligationLedger,
        GeneratedView::GauntletProofRelations,
        GeneratedView::SystemModelProofRequirements,
        GeneratedView::RepositoryProofRequirements,
        GeneratedView::TypeSystemProofRequirements,
        GeneratedView::StorageProofRequirements,
        GeneratedView::SyncBatProofRequirements,
        GeneratedView::BvisorProofRequirements,
        GeneratedView::WorldPortsProofRequirements,
        GeneratedView::TestPakProofRequirements,
        GeneratedView::IdentityTimeProofRequirements,
        GeneratedView::MigrationProofRequirements,
        GeneratedView::SecretAuthorityProofRequirements,
        GeneratedView::Gate0MaterializationPlan,
        GeneratedView::VerificationPlans,
        GeneratedView::SproutingVocabulary,
        GeneratedView::SpecializedPlanCandidatePolicy,
        GeneratedView::SproutingProofRequirements,
        GeneratedView::GeneratedViewRegistry,
        GeneratedView::SpecModuleCatalog,
        GeneratedView::BootstrapToolCatalog,
    ];

    pub const fn name(self) -> &'static str {
        match self {
            GeneratedView::OperatorsCatalog => "OperatorsCatalog",
            GeneratedView::OperatorsSurfaces => "OperatorsSurfaces",
            GeneratedView::OperatorsGrammar => "OperatorsGrammar",
            GeneratedView::OperatorsProjection => "OperatorsProjection",
            GeneratedView::OperatorsTyping => "OperatorsTyping",
            GeneratedView::OperatorsNumeric => "OperatorsNumeric",
            GeneratedView::SeedClassification => "SeedClassification",
            GeneratedView::GuaranteeGraph => "GuaranteeGraph",
            GeneratedView::PakVmSemanticIsa => "PakVmSemanticIsa",
            GeneratedView::PakVmSignatures => "PakVmSignatures",
            GeneratedView::SyncBatPlaneOwnership => "SyncBatPlaneOwnership",
            GeneratedView::SyncBatAuthorities => "SyncBatAuthorities",
            GeneratedView::SyncBatCrossings => "SyncBatCrossings",
            GeneratedView::ReconciliationCoordinates => "ReconciliationCoordinates",
            GeneratedView::ReconciliationRetry => "ReconciliationRetry",
            GeneratedView::ReleaseSeal => "ReleaseSeal",
            GeneratedView::ProofTerminals => "ProofTerminals",
            GeneratedView::StaleVocabulary => "StaleVocabulary",
            GeneratedView::GateInventory => "GateInventory",
            GeneratedView::ContractKinds => "ContractKinds",
            GeneratedView::RustToolchain => "RustToolchain",
            GeneratedView::IdentityCatalog => "IdentityCatalog",
            GeneratedView::GenerationCatalog => "GenerationCatalog",
            GeneratedView::BindingCatalog => "BindingCatalog",
            GeneratedView::VersionCatalog => "VersionCatalog",
            GeneratedView::IdentityResidue => "IdentityResidue",
            GeneratedView::ProductCommands => "ProductCommands",
            GeneratedView::TestPakCommands => "TestPakCommands",
            GeneratedView::BatQlSourceModes => "BatQlSourceModes",
            GeneratedView::MutationLanes => "MutationLanes",
            GeneratedView::MutationResults => "MutationResults",
            GeneratedView::PromotionRequirements => "PromotionRequirements",
            GeneratedView::CompilerAssumptionKinds => "CompilerAssumptionKinds",
            GeneratedView::CorpusReconciliationEpoch => "CorpusReconciliationEpoch",
            GeneratedView::CorpusEpochMembership => "CorpusEpochMembership",
            GeneratedView::PackageInventory => "PackageInventory",
            GeneratedView::PackageEdges => "PackageEdges",
            GeneratedView::QualificationProfiles => "QualificationProfiles",
            GeneratedView::BundleInventory => "BundleInventory",
            GeneratedView::Tier0ReceiptDenominator => "Tier0ReceiptDenominator",
            GeneratedView::DecisionLedger => "DecisionLedger",
            GeneratedView::LegacyInvariantCoverage => "LegacyInvariantCoverage",
            GeneratedView::LegacyObligationLedger => "LegacyObligationLedger",
            GeneratedView::GauntletProofRelations => "GauntletProofRelations",
            GeneratedView::SystemModelProofRequirements => "SystemModelProofRequirements",
            GeneratedView::RepositoryProofRequirements => "RepositoryProofRequirements",
            GeneratedView::TypeSystemProofRequirements => "TypeSystemProofRequirements",
            GeneratedView::StorageProofRequirements => "StorageProofRequirements",
            GeneratedView::SyncBatProofRequirements => "SyncBatProofRequirements",
            GeneratedView::BvisorProofRequirements => "BvisorProofRequirements",
            GeneratedView::WorldPortsProofRequirements => "WorldPortsProofRequirements",
            GeneratedView::TestPakProofRequirements => "TestPakProofRequirements",
            GeneratedView::IdentityTimeProofRequirements => "IdentityTimeProofRequirements",
            GeneratedView::MigrationProofRequirements => "MigrationProofRequirements",
            GeneratedView::SecretAuthorityProofRequirements => "SecretAuthorityProofRequirements",
            GeneratedView::Gate0MaterializationPlan => "Gate0MaterializationPlan",
            GeneratedView::VerificationPlans => "VerificationPlans",
            GeneratedView::SproutingVocabulary => "SproutingVocabulary",
            GeneratedView::SpecializedPlanCandidatePolicy => "SpecializedPlanCandidatePolicy",
            GeneratedView::SproutingProofRequirements => "SproutingProofRequirements",
            GeneratedView::GeneratedViewRegistry => "GeneratedViewRegistry",
            GeneratedView::SpecModuleCatalog => "SpecModuleCatalog",
            GeneratedView::BootstrapToolCatalog => "BootstrapToolCatalog",
        }
    }

    /// The complete generation metadata for one view. Every generator arm is
    /// written explicitly — no wildcard or family default silently blesses a
    /// future generator.
    pub const fn spec(self) -> GeneratedViewSpec {
        match self {
            GeneratedView::OperatorsCatalog => GeneratedViewSpec {
                authority_sources: &["spec/operators/inventory.rs", "spec/operators/types.rs"],
                target: GeneratedViewTarget::Static(&["companion/BATQL_LANGUAGE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("OPERATORS-CATALOG"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::OperatorsSurfaces => GeneratedViewSpec {
                authority_sources: &["spec/operators/inventory.rs", "spec/operators/types.rs"],
                target: GeneratedViewTarget::Static(&["companion/BATQL_LANGUAGE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("OPERATORS-SURFACES"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::OperatorsGrammar => GeneratedViewSpec {
                authority_sources: &["spec/operators/inventory.rs", "spec/operators/types.rs"],
                target: GeneratedViewTarget::Static(&["companion/BATQL_LANGUAGE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("OPERATORS-GRAMMAR"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::OperatorsProjection => GeneratedViewSpec {
                authority_sources: &["spec/operators/inventory.rs", "spec/operators/types.rs"],
                target: GeneratedViewTarget::Static(&["companion/BATQL_LANGUAGE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("OPERATORS-PROJECTION"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::OperatorsTyping => GeneratedViewSpec {
                authority_sources: &["spec/operators/inventory.rs", "spec/operators/types.rs"],
                target: GeneratedViewTarget::Static(&["companion/BATQL_LANGUAGE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("OPERATORS-TYPING"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::OperatorsNumeric => GeneratedViewSpec {
                authority_sources: &["spec/operators/inventory.rs", "spec/operators/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/37_NUMERIC_SEMANTICS_AND_AUTHORITY.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("OPERATORS-NUMERIC"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SeedClassification => GeneratedViewSpec {
                authority_sources: &["spec/invariants/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/23_BOOTSTRAP_AND_SELF_HOSTING.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("SEED-CLASSIFICATION"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::GuaranteeGraph => GeneratedViewSpec {
                authority_sources: &[
                    "spec/invariants/inventory.rs",
                    "spec/legacy_obligations/inventory.rs",
                    "spec/dispositions/inventory.rs",
                    "spec/architecture/inventory.rs",
                    "spec/architecture/types.rs",
                    "spec/guarantees/policy.rs",
                    "spec/gates/inventory.rs",
                ],
                target: GeneratedViewTarget::Static(&["docs/GUARANTEE_GRAPH.generated.md"]),
                surface: GeneratedViewSurface::StandaloneFile,
                marker: None,
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::PakVmSemanticIsa => GeneratedViewSpec {
                authority_sources: &[
                    "spec/pakvm_isa/nodes.rs",
                    "spec/pakvm_isa/policies.rs",
                    "spec/pakvm_isa/types.rs",
                ],
                target: GeneratedViewTarget::Static(&["docs/07_PAKVM_ISA.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PAKVM-SEMANTIC-ISA"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::PakVmSignatures => GeneratedViewSpec {
                authority_sources: &["spec/pakvm_isa/nodes.rs"],
                target: GeneratedViewTarget::Static(&["docs/07_PAKVM_ISA.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PAKVM-SIGNATURES"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SyncBatPlaneOwnership => GeneratedViewSpec {
                authority_sources: &["spec/architecture/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/08_SYNCBAT_RUNTIME.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("SYNCBAT-PLANE-OWNERSHIP"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SyncBatAuthorities => GeneratedViewSpec {
                authority_sources: &["spec/syncbat_firewall/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/08_SYNCBAT_RUNTIME.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("SYNCBAT-AUTHORITIES"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SyncBatCrossings => GeneratedViewSpec {
                authority_sources: &["spec/syncbat_firewall/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/08_SYNCBAT_RUNTIME.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("SYNCBAT-CROSSINGS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::ReconciliationCoordinates => GeneratedViewSpec {
                authority_sources: &["spec/reconciliation/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/02_SYSTEM_MODEL.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("RECONCILIATION-COORDINATES"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::ReconciliationRetry => GeneratedViewSpec {
                authority_sources: &["spec/reconciliation/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/02_SYSTEM_MODEL.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("RECONCILIATION-RETRY"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::ReleaseSeal => GeneratedViewSpec {
                authority_sources: &["spec/architecture/release_seal.rs"],
                target: GeneratedViewTarget::Static(&["docs/36_PUBLIC_API_CI_AND_RELEASE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("RELEASE-SEAL"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::ProofTerminals => GeneratedViewSpec {
                authority_sources: &["spec/proof/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/12_TESTPAK.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-TERMINALS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::StaleVocabulary => GeneratedViewSpec {
                authority_sources: &["spec/dispositions/inventory.rs"],
                target: GeneratedViewTarget::Static(&[
                    "docs/29_STATUS_AND_SUPERSESSION.md",
                    "docs/33_AGENT_FINISH_LINE_CHECKLIST.md",
                ]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("STALE-VOCAB"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::GateInventory => GeneratedViewSpec {
                authority_sources: &["spec/gates/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/25_IMPLEMENTATION_GATES.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("GATE-INVENTORY"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::ContractKinds => GeneratedViewSpec {
                authority_sources: &["spec/contracts/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/06_MACBAT.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("CONTRACT-KINDS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::RustToolchain => GeneratedViewSpec {
                authority_sources: &["spec/toolchain/types.rs"],
                target: GeneratedViewTarget::Static(&["rust-toolchain.toml"]),
                surface: GeneratedViewSurface::StandaloneFile,
                marker: None,
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::IdentityCatalog => GeneratedViewSpec {
                authority_sources: &["spec/identities/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/16_IDENTITY_TIME_AND_NAVIGATION.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("IDENTITY-CATALOG"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::GenerationCatalog => GeneratedViewSpec {
                authority_sources: &["spec/identities/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/16_IDENTITY_TIME_AND_NAVIGATION.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("GENERATION-CATALOG"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::BindingCatalog => GeneratedViewSpec {
                authority_sources: &["spec/identities/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/16_IDENTITY_TIME_AND_NAVIGATION.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("BINDING-CATALOG"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::VersionCatalog => GeneratedViewSpec {
                authority_sources: &["spec/identities/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/16_IDENTITY_TIME_AND_NAVIGATION.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("VERSION-CATALOG"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::IdentityResidue => GeneratedViewSpec {
                authority_sources: &["spec/identities/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/16_IDENTITY_TIME_AND_NAVIGATION.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("IDENTITY-RESIDUE"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::ProductCommands => GeneratedViewSpec {
                authority_sources: &["spec/commands/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/26_COMMAND_PLANE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PRODUCT-COMMANDS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::TestPakCommands => GeneratedViewSpec {
                authority_sources: &["spec/commands/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/26_COMMAND_PLANE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("TESTPAK-COMMANDS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::BatQlSourceModes => GeneratedViewSpec {
                authority_sources: &["spec/commands/types.rs"],
                target: GeneratedViewTarget::Static(&["companion/BATQL_LANGUAGE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("BATQL-SOURCE-MODES"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::MutationLanes => GeneratedViewSpec {
                authority_sources: &["spec/mutation/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/12_TESTPAK.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("MUTATION-LANES"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::MutationResults => GeneratedViewSpec {
                authority_sources: &["spec/mutation/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/12_TESTPAK.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("MUTATION-RESULTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::PromotionRequirements => GeneratedViewSpec {
                authority_sources: &["spec/promotion/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/12_TESTPAK.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROMOTION-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::CompilerAssumptionKinds => GeneratedViewSpec {
                authority_sources: &["spec/compiler_assumptions/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/19_SECURITY_MODEL.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("COMPILER-ASSUMPTION-KINDS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::CorpusReconciliationEpoch => GeneratedViewSpec {
                authority_sources: &["spec/corpus/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/00_CONSTITUTION.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("CORPUS-RECONCILIATION-EPOCH"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::CorpusEpochMembership => GeneratedViewSpec {
                authority_sources: &["spec/corpus/types.rs"],
                target: GeneratedViewTarget::EligibleMarkdownCorpus,
                surface: GeneratedViewSurface::CorpusFrontmatter,
                marker: None,
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::PackageInventory => GeneratedViewSpec {
                authority_sources: &[
                    "spec/architecture/inventory.rs",
                    "spec/architecture/types.rs",
                ],
                target: GeneratedViewTarget::Static(&[
                    "README.md",
                    "docs/03_REPOSITORY_AND_PACKAGES.md",
                ]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PACKAGE-INVENTORY"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::PackageEdges => GeneratedViewSpec {
                authority_sources: &[
                    "spec/architecture/inventory.rs",
                    "spec/architecture/types.rs",
                ],
                target: GeneratedViewTarget::Static(&["docs/03_REPOSITORY_AND_PACKAGES.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PACKAGE-EDGES"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::QualificationProfiles => GeneratedViewSpec {
                authority_sources: &[
                    "spec/architecture/inventory.rs",
                    "spec/architecture/types.rs",
                ],
                target: GeneratedViewTarget::Static(&["docs/03_REPOSITORY_AND_PACKAGES.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("QUALIFICATION-PROFILES"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::BundleInventory => GeneratedViewSpec {
                authority_sources: &[
                    "spec/architecture/inventory.rs",
                    "spec/invariants/inventory.rs",
                    "spec/dispositions/inventory.rs",
                    "spec/legacy_obligations/inventory.rs",
                    "spec/legacy_invariant_coverage/inventory.rs",
                    "spec/operators/inventory.rs",
                    "spec/generated_views/registry.rs",
                ],
                target: GeneratedViewTarget::Static(&["docs/28_SELF_EXPLAINING_REPOSITORY.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("BUNDLE-INVENTORY"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::Tier0ReceiptDenominator => GeneratedViewSpec {
                authority_sources: &["spec/bootstrap_qualification/types.rs"],
                target: GeneratedViewTarget::Static(&["docs/23_BOOTSTRAP_AND_SELF_HOSTING.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("TIER0-RECEIPT-DENOMINATOR"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::DecisionLedger => GeneratedViewSpec {
                authority_sources: &[
                    "spec/dispositions/inventory.rs",
                    "spec/dispositions/types.rs",
                ],
                target: GeneratedViewTarget::Static(&["docs/30_DECISION_AND_REJECTION_LEDGER.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("DECISION-LEDGER"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::LegacyInvariantCoverage => GeneratedViewSpec {
                authority_sources: &["spec/legacy_invariant_coverage/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/34_LEGACY_INVARIANT_COVERAGE.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("LEGACY-INVARIANT-COVERAGE"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::LegacyObligationLedger => GeneratedViewSpec {
                authority_sources: &[
                    "spec/legacy_obligations/inventory.rs",
                    "spec/proof/inventory.rs",
                ],
                target: GeneratedViewTarget::Static(&["docs/21_LEGACY_SEMANTIC_OBLIGATIONS.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("LEGACY-OBLIGATION-LEDGER"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::GauntletProofRelations => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/24_GAUNTLET.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-RELATIONS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SystemModelProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/02_SYSTEM_MODEL.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::RepositoryProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/03_REPOSITORY_AND_PACKAGES.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::TypeSystemProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/04_TYPE_SYSTEM_AND_SOURCE_LAYOUT.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::StorageProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/05_STORAGE_FBAT_AND_TILES.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SyncBatProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/08_SYNCBAT_RUNTIME.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::BvisorProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/09_BVISOR.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::WorldPortsProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/10_WORLD_IMAGES_AND_PORTS.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::TestPakProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/12_TESTPAK.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::IdentityTimeProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/16_IDENTITY_TIME_AND_NAVIGATION.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::MigrationProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/22_MIGRATION_AND_CUTOVER.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SecretAuthorityProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/35_CRYPTO_AND_SECRET_AUTHORITY.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::Gate0MaterializationPlan => GeneratedViewSpec {
                authority_sources: &[
                    "spec/bootstrap_output/types.rs",
                    "spec/architecture/types.rs",
                    "spec/toolchain/types.rs",
                ],
                target: GeneratedViewTarget::Static(&["docs/23_BOOTSTRAP_AND_SELF_HOSTING.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("GATE0-MATERIALIZATION-PLAN"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::VerificationPlans => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs", "spec/verification/types.rs"],
                target: GeneratedViewTarget::Static(&[
                    "docs/38_DYNAMIC_VERIFICATION_AND_CONFORMANCE.md",
                ]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("VERIFICATION-PLANS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SproutingVocabulary => GeneratedViewSpec {
                authority_sources: &["spec/sprouting/types.rs"],
                target: GeneratedViewTarget::Static(&[
                    "docs/39_SPROUTING_NURSERY_AND_PROMOTION.md",
                ]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("SPROUTING-VOCABULARY"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SpecializedPlanCandidatePolicy => GeneratedViewSpec {
                authority_sources: &["spec/sprouting/inventory.rs"],
                target: GeneratedViewTarget::Static(&["docs/07_PAKVM_ISA.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("SPECIALIZED-PLAN-CANDIDATE-POLICY"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SproutingProofRequirements => GeneratedViewSpec {
                authority_sources: &["spec/proof/inventory.rs"],
                target: GeneratedViewTarget::Static(&[
                    "docs/39_SPROUTING_NURSERY_AND_PROMOTION.md",
                ]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("PROOF-REQUIREMENTS"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::GeneratedViewRegistry => GeneratedViewSpec {
                authority_sources: &["spec/generated_views/registry.rs"],
                target: GeneratedViewTarget::Static(&["docs/28_SELF_EXPLAINING_REPOSITORY.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("GENERATED-VIEW-REGISTRY"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::SpecModuleCatalog => GeneratedViewSpec {
                authority_sources: &["spec/lib.rs"],
                target: GeneratedViewTarget::Static(&["spec/README.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("SPEC-MODULE-CATALOG"),
                generator: BootstrapToolId::ProjectPy,
            },
            GeneratedView::BootstrapToolCatalog => GeneratedViewSpec {
                authority_sources: &["spec/guarantees/types.rs"],
                target: GeneratedViewTarget::Static(&["bootstrap/README.md"]),
                surface: GeneratedViewSurface::EmbeddedBlock,
                marker: Some("BOOTSTRAP-TOOL-CATALOG"),
                generator: BootstrapToolId::ProjectPy,
            },
        }
    }
}
